Add console logger for errors
jhipster/jhipster-lite pull request #1014
Opened 2022-03-13 10:35 UTC by Franceq34

- relates https://github.com/jhipster/jhipster-lite/issues/1013

2022-03-13 19:51 UTC, pascalgrimaud commented
I really need someone better in front than me to review this part, as I think it's really important
maybe @nonomoho or @seraphinandrieux ?

2022-03-14 08:25 UTC, nonomoho requested changes

2022-03-14 08:25 UTC, nonomoho commented on src/main/webapp/app/common/secondary/ConsoleLogger.ts
> +export class ConsoleLogger implements Logger {
You can use `export default`

2022-03-14 08:25 UTC, nonomoho commented on src/test/javascript/spec/common/domain/Logger.fixture.ts
> +import { Logger } from '../../../../../main/webapp/app/common/domain/Logger';
use import with @

2022-03-14 08:25 UTC, nonomoho commented on src/test/javascript/spec/common/secondary/ConsoleLogger.spec.ts
> +    const consoleLogger = new ConsoleLogger(logger as any);
Is it mandatory to use `any` here?
You should maybe type your logger line 7: `const logger: Logger = ...`

2022-03-14 08:25 UTC, nonomoho commented on src/test/javascript/spec/springboot/primary/Generator.spec.ts
> +import { Logger } from '../../../../../main/webapp/app/common/domain/Logger';
Use @ import

2022-03-14 09:55 UTC, Franceq34 commented on src/test/javascript/spec/common/secondary/ConsoleLogger.spec.ts
> +    const consoleLogger = new ConsoleLogger(logger as any);
ConsoleLogger needs a Console object from typescript to create.
I can't type my logger as you say by doing `const logger: Console = ...`, unless I create a stub with the 15 attributes of the object Console .. unless there is another solution I didnt see.

2022-03-14 10:27 UTC, seraphinandrieux commented
It's ok on my side

2022-03-16 22:54 UTC, pascalgrimaud approved these changes

2022-03-16 22:55 UTC, merged