Add router into vue app generated
jhipster/jhipster-lite pull request #1071
Opened 2022-03-17 17:01 UTC by seraphinandrieux

- Fix #1018

2022-03-18 08:26 UTC, pascalgrimaud requested changes

2022-03-18 08:26 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/main.ts.mustache
> +// jhipster-needle-import
could you rename to something like: `// jhipster-needle-main-ts-import`

2022-03-18 08:26 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/main.ts.mustache
> +// jhipster-needle-provider
could you rename to something like: `// jhipster-needle-main-ts-provider`

2022-03-18 08:26 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/client/vue/core/application/VueAssert.java
> +    assertFileExist(project, "src/main/webapp/app/router/router.ts");
can use constant MAIN_WEBAPP with getPath

2022-03-18 08:26 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/client/vue/core/application/VueAssert.java
> +    assertFileExist(project, "src/test/javascript/spec/router/Router.spec.ts");
maybe we could add a constant here for src/test/javascript/spec

2022-03-18 21:08 UTC, pascalgrimaud approved these changes

2022-03-18 21:09 UTC, merged

2022-03-21 07:05 UTC, seraphinandrieux commented
bounty claimed : https://opencollective.com/generator-jhipster/expenses/68143

2022-03-21 07:08 UTC, pascalgrimaud commented
@seraphinandrieux : approved, thanks a lot for your work here