handle optional in Jackson
jhipster/jhipster-lite pull request #10781
Opened 2024-09-07 20:42 UTC by fabienpuissant

create bean Jdk8Module and ObjectMapper

Fix #10751

2024-09-07 20:50 UTC, fabienpuissant commented
@DamnClin 
Jackson was not available in the spring boot core module.
In a first version I've just imported jdk8Module from jackson-datatype-jdk8 but in the end, I preferred use the existing starter web

I don't know what do you think about it

2024-09-08 01:51 UTC, fabienpuissant commented
> @DamnClin Jackson was not available in the spring boot core module. In a first version I've just imported jdk8Module from jackson-datatype-jdk8 but in the end, I preferred use the existing starter web
> 
> I don't know what do you think about it

Importing the starter-web leads to side effects (especially with Spring cloud), so I just import jackson-datatype-jdk8

2024-09-08 08:28 UTC, DamnClin commented
> @DamnClin Jackson was not available in the spring boot core module. In a first version I've just imported jdk8Module from jackson-datatype-jdk8 but in the end, I preferred use the existing starter web
> 
> I don't know what do you think about it

This is probably the wrong module to add it so :). There should be a module with this dependency already on and his must be done here.

We can't add the web starter in this module if it wasn't there since SpringBoot can be use for other needs (like batch), my bad on identifying the sweet spot

2024-09-08 20:32 UTC, murdos commented on src/main/resources/generator/dependencies/pom.xml
> +    <jackson-datatype-jdk8.version>2.17.2</jackson-datatype-jdk8.version>
You can remove the changes from this file, they're not used anymore

2024-09-14 15:36 UTC, murdos requested changes

2024-09-14 15:36 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactory.java
> +  private static final JHipsterSource JACKSON_MAIN_SOURCE = from("server/springboot/jackson/main");
You should put the new templates in `server/springboot/mvc/web` (the root of the resources for this module), and thus use below the `SOURCE` constant.

We should try to keep a coherent tree directory between modules and their resources.

2024-09-14 15:36 UTC, murdos commented on src/main/resources/generator/server/springboot/jackson/test/wire/jackson/infrastructure/config/JacksonConfigurationTest.java.mustache
> +    assertThat(objectMapper.writeValueAsString(optional)).isEqualTo("\"test\"");
Here you're just testing the `Jdk8Module` which is an external dependency, so there's no real reason to test it again.
What could be more interesting is an integration test where you inject the ObjectMapper provided by Spring Boot, and assert that it indeed correctly map Optional.

2024-09-14 15:43 UTC, fabienpuissant commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactory.java
> +  private static final JHipsterSource JACKSON_MAIN_SOURCE = from("server/springboot/jackson/main");
even if we use this templates for mvc and webflux ?
I put it in a separate module because of that

2024-09-14 15:46 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactory.java
> +  private static final JHipsterSource JACKSON_MAIN_SOURCE = from("server/springboot/jackson/main");
Ah, sorry, my review was a bit too quick :)
Then it's fine I guess

2024-09-14 18:27 UTC, murdos approved these changes

2024-09-15 03:24 UTC, fabienpuissant commented
To avoid errors, use default spring boot jackson configuration and enrich with jdk8Module
Source : https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java

2024-09-16 20:14 UTC, murdos commented on src/main/resources/generator/server/springboot/jackson/main/wire/jackson/infrastructure/config/JacksonConfiguration.java.mustache
> +  public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder builder) {
I've just tested it, the following code is sufficient and more extensible (since it doesn't overwrite SpringBoot configuration):

```java
@Bean
  Jdk8Module jdk8Module() {
    return new Jdk8Module();
  }
```

2024-09-16 20:18 UTC, murdos commented on src/main/resources/generator/server/springboot/jackson/main/wire/jackson/infrastructure/config/JacksonConfiguration.java.mustache
> +  public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder builder) {
It will be injected in the list of modules here: https://github.com/spring-projects/spring-boot/blob/74ddea416b8a0d2c12e289116e75aace3c70acf2/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java#L179

2024-09-16 20:24 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactory.java
> +  private static final String WIRE_JACKSON_CONFIG = "wire/jackson/infrastructure/config";
Subfolder of `infrastructure` folder are either `primary` or `secondary`:
```suggestion
  private static final String WIRE_JACKSON_CONFIG = "wire/jackson/infrastructure/primary";
```

2024-09-16 20:28 UTC, murdos commented on src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactoryTest.java
> +      .containing("public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder builder)")
Usually we test content of a file when it's a template and we want to check the dynamic content.
Here it's not needed since this is a static content handled in the template.

2024-09-16 20:31 UTC, fabienpuissant commented on src/main/resources/generator/server/springboot/jackson/main/wire/jackson/infrastructure/config/JacksonConfiguration.java.mustache
> +  public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder builder) {
true xD
Kinda dark magic

2024-09-16 21:13 UTC, fabienpuissant commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactory.java
> +  private static final String WIRE_JACKSON_CONFIG = "wire/jackson/infrastructure/config";
![image](https://github.com/user-attachments/assets/025a83f4-3381-45aa-92fb-4d8238cccecd)

2024-09-16 21:20 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcsModulesFactory.java
> +  private static final String WIRE_JACKSON_CONFIG = "wire/jackson/infrastructure/config";
You need the update the JacksonConfiguration.java content too:
`package {{packageName}}.wire.jackson.infrastructure.config;` -> `package {{packageName}}.wire.jackson.infrastructure.primary;`

2024-09-16 21:36 UTC, murdos approved these changes

2024-09-16 22:15 UTC, merged