Create redirection resource to come back into web app
jhipster/jhipster-lite pull request #1087
Opened 2022-03-18 15:26 UTC by seraphinandrieux

- Fix #1028

2022-03-18 16:22 UTC, pascalgrimaud commented on src/main/webapp/app/router/index.ts
> +  },
is it used ?

2022-03-18 16:24 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/technical/infrastructure/primary/redirection/RedirectionResourceIT.java
> +  void shouldNotGetViewFromRedirectionResourceWhenWeCallASpecificApi() throws Exception {
not sure if this test is usefull, because the other integration tests will fail if it's not correct

2022-03-18 17:22 UTC, seraphinandrieux commented on src/main/webapp/app/router/index.ts
> +  },
xd nop at all it was at the begining I removed it in last push

2022-03-18 17:22 UTC, seraphinandrieux commented on src/test/java/tech/jhipster/lite/technical/infrastructure/primary/redirection/RedirectionResourceIT.java
> +  void shouldNotGetViewFromRedirectionResourceWhenWeCallASpecificApi() throws Exception {
You right :)

2022-03-18 17:27 UTC, pascalgrimaud commented
@seraphinandrieux : I think your rebase was wrong, as this PR contains in fact 2 PRs :)

2022-03-18 17:40 UTC, pascalgrimaud requested changes

2022-03-18 17:40 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenDomainService.java
> +    String packageNamePath = project.getPackageNamePath().orElse(getPath("com/mycompany/myapp"));
you can use constant in DefaultConfig

2022-03-18 17:40 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenDomainService.java
> +    String redirectionPath = "technical/infrastructure/primary/redirection";
use getPath + constants for TECHNICAL_INFRASTRUCTURE_PRIMARY, something like

```java
    String redirectionPath = getPath(TECHNICAL_INFRASTRUCTURE_PRIMARY, "redirection");
```

2022-03-18 17:40 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/application/FrontendMavenAssert.java
> +      project.getPackageNamePath().orElse("com/mycompany/myapp"),
use constant in DefaultConfig

2022-03-18 17:40 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/application/FrontendMavenAssert.java
> +      project.getPackageNamePath().orElse("com/mycompany/myapp"),
use constant in DefaultConfig

2022-03-21 07:04 UTC, pascalgrimaud requested changes

2022-03-21 07:04 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/web/test/RedirectionResourceIT.java.mustache
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
```suggestion
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;
import {{packageName}}.IntegrationTest;
```

2022-03-21 07:04 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenDomainServiceTest.java
> +    assertThat(redirectionFilesCaptor.getAllValues()).contains("RedirectionResource.java").contains("RedirectionResourceIT.java");
I think you can use a single contains, something like contains("RedirectionResource.java", "RedirectionResourceIT.java")

2022-03-21 08:18 UTC, seraphinandrieux commented on src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenDomainServiceTest.java
> +    assertThat(redirectionFilesCaptor.getAllValues()).contains("RedirectionResource.java").contains("RedirectionResourceIT.java");
As you prefer :)

2022-03-21 08:34 UTC, pascalgrimaud approved these changes

2022-03-21 09:05 UTC, merged

2022-03-21 09:12 UTC, seraphinandrieux commented
$100 bounty claimed : https://opencollective.com/generator-jhipster/expenses/68167