Add Spring Boot LangChain4j sample
jhipster/jhipster-lite pull request #11335
Opened 2024-11-10 15:44 UTC by anunnakian

2024-11-10 16:14 UTC, anunnakian commented
@pascalgrimaud here is the PR to add a LangChain4j sample ;)

2024-11-10 16:23 UTC, pascalgrimaud requested changes

2024-11-10 16:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/jpapersistence/infrastructure/primary/SampleJpaPersistenceModuleConfiguration.java
> -class SampleJpaPersistenceModuleConfiguration {
Why deleting this file?

2024-11-10 16:23 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/sample/langchain4j/main/infrastructure/primary/ChatResource.java.mustache
> +@RestController
Need to use requestMapping to be under /api, so it will be visibled by springdoc

2024-11-10 16:23 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/sample/langchain4j/main/infrastructure/primary/ChatResource.java.mustache
> +public class ChatResource {
No need to be public

2024-11-10 16:23 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/jpapersistence/domain/SampleLangChain4jModuleFactoryTest.java
> +class SampleLangChain4jModuleFactoryTest {
Wrong dev here

2024-11-10 16:25 UTC, anunnakian commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/jpapersistence/infrastructure/primary/SampleJpaPersistenceModuleConfiguration.java
> -class SampleJpaPersistenceModuleConfiguration {
You are to fast ! it was a mistake :D

2024-11-10 16:26 UTC, anunnakian commented on src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/sample/jpapersistence/domain/SampleLangChain4jModuleFactoryTest.java
> +class SampleLangChain4jModuleFactoryTest {
Yep sorry :D

2024-11-10 16:39 UTC, pascalgrimaud commented
In the last PR, I forgot to tell you to add a new config to test in the CI, the new modules langchain4j

Could you add a new one here?
- https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L232

Then, add it to the CI:
- https://github.com/jhipster/jhipster-lite/blob/main/.github/workflows/github-actions.yml#L232

2024-11-10 16:41 UTC, pascalgrimaud commented
By adding to the CI the generated app, it will show you that the generated app with langchain4j is not totally covered: missing tests for ChatResource

2024-11-10 21:02 UTC, qmonmert commented on tests-ci/generate.sh
> +echo $application
```suggestion
```

2024-11-10 22:26 UTC, pascalgrimaud commented
Cc @renanfranca : what happened when we added a new config in script.sh and it doesn't exist in main branch? The checksum with md5 should be ignored, right?

2024-11-11 01:13 UTC, renanfranca commented
> Cc @renanfranca : what happened when we added a new config in script.sh and it doesn't exist in main branch? The checksum with md5 should be ignored, right?

The pipeline will break because the MD5 checksum is generated after it tries and fails to create the non-existent app in generate.sh in the main branch.

In my previous experience [creating a new app in generate.sh](https://github.com/jhipster/jhipster-lite/pull/11088#issuecomment-2404843543) and adding it to the github-actions.yml matrix, I had to add the new app in generate.sh and merge it with the main branch. Only after that could I add the new app to the matrix.

I saw your comment [here](https://github.com/jhipster/jhipster-lite/pull/11088#issuecomment-2406691288) only today. Yes, i think it should ignored non existing apps.

2024-11-11 02:19 UTC, renanfranca commented
> > I saw your comment [here](https://github.com/jhipster/jhipster-lite/pull/11088#issuecomment-2406691288) only today. Yes, i think it should ignored non existing apps.
> 
> But will it run on main branch CI? I think so...

![Screenshot_20241110_231019_Vivaldi](https://github.com/user-attachments/assets/0900ccc4-6f5f-437a-bb8e-001d8154d652)


I am having second thoughts about the importance of checking out the complete project from the main branch if it's only using the test-ci folder to run commands with the downloaded main jar file, which is not updated and generates an error when adding a new app in generate.sh and including the app in the GitHub Actions matrix in a pull request.

@pascalgrimaud and @murdos : What do you think about checking out from the current branch as well at step name: 'Setup: checkout project from main branch' and keeping everything else unchanged?

2024-11-11 09:00 UTC, pascalgrimaud commented
I created the ticket here https://github.com/jhipster/jhipster-lite/issues/11341

2024-11-11 10:13 UTC, merged