Add backend for zipped application generation
jhipster/jhipster-lite pull request #1146
Opened 2022-03-24 14:53 UTC by matthieulapatate

- Related to #1132 
One part of this issue is dealed in this PR. It relies to springboot generation and API response with zip file.
A bounded countext has been created and a method has been added to ProjectRepository Interface.

2022-03-24 17:28 UTC, pascalgrimaud commented on pom.xml
> +      <version>2.11.0</version>
version should not be here, but in properties instead

2022-03-24 17:28 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/domain/ProjectRepository.java
> +import org.springframework.http.ResponseEntity;
it's totally forbidden. Domain should not use external framework like springframework

2022-03-24 17:29 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +import org.springframework.http.ResponseEntity;
we are in secondary, so there should not be import like this, which are related to primary (rest)

2022-03-24 17:35 UTC, pascalgrimaud commented on pom.xml
> +      <artifactId>commons-io</artifactId>
If it's just used for converting inputstream to byte array, we don't need this

2022-03-24 17:37 UTC, pascalgrimaud commented on src/main/resources/generator/dependencies/common/package.json
> +    "@prettier/plugin-xml": "2.0.1",
not the scope of this PR

2022-03-24 17:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepositoryTest.java
> +    assertNotNull(repository.zip(project));
use assertj instead to keep consistency with the other tests. Then, it would be better to test the filename of zip, for example

2022-03-24 17:39 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepositoryTest.java
> +    assertThat(repository.zip(project).getStatusCode() == HttpStatus.INTERNAL_SERVER_ERROR);
there should not be httpstatus in secondary, so this test needs to be rework

2022-03-24 17:39 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepositoryTest.java
> +      assertThat(repository.zip(project).getStatusCode() == HttpStatus.INTERNAL_SERVER_ERROR);
there should not be httpstatus in secondary, so this test needs to be rework

2022-03-25 08:17 UTC, matthieulapatate commented on pom.xml
> +      <artifactId>commons-io</artifactId>
Is there an existing method already doing it ?

2022-03-25 08:19 UTC, matthieulapatate commented on src/main/java/tech/jhipster/lite/generator/project/domain/ProjectRepository.java
> +import org.springframework.http.ResponseEntity;
How can i describe what's returned ? is the responseEntity already implemented in return apis ?

2022-03-25 08:39 UTC, pascalgrimaud commented on pom.xml
> +      <artifactId>commons-io</artifactId>
search byte array to inputstream or inputstream to byte array -> https://www.baeldung.com/convert-byte-array-to-input-stream

2022-03-25 08:41 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/domain/ProjectRepository.java
> +import org.springframework.http.ResponseEntity;
void or byte[]

2022-03-27 17:34 UTC, pascalgrimaud requested changes

2022-03-27 17:34 UTC, pascalgrimaud commented on pom.xml
> +    <commons-io.version>2.11.0</commons-io.version>
no need

2022-03-27 17:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +      log.error("This folder doesn't exist");
it's not true, there can be another problem when zipping. Simply change to something like: 'Error when zipping {}', with the folder name as parameter

2022-03-27 17:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +      throw (e);
better to throw GeneratorException

2022-03-27 17:35 UTC, pascalgrimaud commented
I suppose the work is finished but it's still in draft probably you forgot to change it.
Anyway I made some comments

2022-03-28 07:45 UTC, pascalgrimaud requested changes

2022-03-28 07:45 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +      throw new GeneratorException("Error when zipping " + project.getFolder());
```suggestion
      throw new GeneratorException("Error when zipping " + project.getFolder(), e);
```

2022-03-28 08:13 UTC, matthieulapatate commented
Is there any problem with codecov ? sonar analyse has 100% passed on local

2022-03-28 08:16 UTC, pascalgrimaud commented
@matthieulapatate : see the logs:

![image](https://user-images.githubusercontent.com/9156882/160355731-f88b2ee8-a145-48c8-8b5f-4165c9e2c483.png)

There was a problem when uploading analysis to codecov. I'm restarting the job

2022-03-28 08:33 UTC, pascalgrimaud approved these changes

2022-03-28 08:33 UTC, merged