Add pinia for vue 3
jhipster/jhipster-lite pull request #1188
Opened 2022-03-29 08:30 UTC by seraphinandrieux

- Fix #1117

2022-03-30 20:40 UTC, pascalgrimaud requested changes

2022-03-30 20:40 UTC, pascalgrimaud commented on package.json
> +    "pinia-plugin-persist": "^1.0.0",
always use fixed version

2022-03-30 20:40 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/Vue.java
> +    "import {createPinia} from \"pinia\";",
```suggestion
    "import {createPinia} from 'pinia';",
```

2022-03-30 20:40 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/Vue.java
> +    return List.of("Button.component.ts", "Button.html", "Button.vue", "index.ts");
need to be discussed, not sure about the use of these files. I know it is used as example, but in the end, the user will delete it for sure

2022-04-02 12:25 UTC, seraphinandrieux commented on src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/Vue.java
> +    return List.of("Button.component.ts", "Button.html", "Button.vue", "index.ts");
Ok no problemo, however if I delete these ones, I'm asking if I have also to delete CounterStore file.
Without the button this store is useless. 
What do you think ?

2022-04-02 12:32 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/Vue.java
> +    return List.of("Button.component.ts", "Button.html", "Button.vue", "index.ts");
Yes we can delete the button. Anyway, this store will be used very soon, to store the token so the example is not really usefull imo

2022-04-03 16:47 UTC, pascalgrimaud requested changes
few last comments and it would be good

2022-04-03 16:47 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/core/infrastructure/primary/rest/VueResource.java
> +  @GeneratorStep(id = "vue-pinia")
can you add and use new constant in GeneratorAction plz ?

2022-04-03 16:47 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/core/infrastructure/primary/rest/VueResource.java
> +  @PostMapping("/pinia")
it would be important to call this api in generator.sh, so it will be really test in CI

2022-04-03 19:12 UTC, pascalgrimaud approved these changes

2022-04-03 19:12 UTC, merged

2022-04-04 06:43 UTC, seraphinandrieux commented
$200 bounty claimed => https://opencollective.com/generator-jhipster/expenses/70882

2022-04-04 07:07 UTC, pascalgrimaud commented
@seraphinandrieux : approved