Add secondary for project download
jhipster/jhipster-lite pull request #1266
Opened 2022-04-07 07:07 UTC by matthieulapatate

- Related to #1132

2022-04-13 15:24 UTC, seraphinandrieux requested changes

2022-04-13 15:24 UTC, seraphinandrieux commented on .gitignore
> +/coverage/
Remove it

2022-04-13 15:27 UTC, seraphinandrieux commented on src/test/javascript/spec/springboot/primary/Generator.spec.ts
> +  it('should not not download when project path is not filled', async () => {
only one not

2022-04-13 20:13 UTC, pascalgrimaud commented
Just tried it, and the proposed file is undefined.zip
Can you use the basename.zip instead ?

2022-04-13 20:15 UTC, pascalgrimaud commented on src/main/webapp/app/springboot/primary/Generator.component.ts
> +          link.setAttribute('download', project.value.baseName + '.zip');
following my comment, in case of project.value.baseName is empty, use a default name instead of 'undefined'

2022-04-13 20:42 UTC, seraphinandrieux requested changes

2022-04-13 20:42 UTC, seraphinandrieux commented on src/main/webapp/app/springboot/primary/Generator.html
> +              <button
As we discussed, display the button only once project is not empty

2022-04-13 20:42 UTC, seraphinandrieux commented on src/test/javascript/spec/springboot/primary/Generator.spec.ts
> +    projectService.download.rejects({});
You could add a custom error in rejection, to check if logger uses it as you set in your method

2022-04-13 20:42 UTC, seraphinandrieux commented on src/test/javascript/spec/springboot/primary/Generator.spec.ts
> +  });
Once you will have implemented v-if statement, think to create test to check if it displayed or not in cypress tests

2022-04-14 07:03 UTC, matthieulapatate commented on src/main/webapp/app/springboot/primary/Generator.html
> +              <button
I think this file can be deleted, because what is displayed is in generator.vue file, that s where i implemented the v-if

2022-04-15 07:23 UTC, seraphinandrieux requested changes

2022-04-15 07:23 UTC, seraphinandrieux commented on test/.jhipster/history.json
> +{
remove

2022-04-15 12:29 UTC, pascalgrimaud requested changes

2022-04-15 12:57 UTC, pascalgrimaud requested changes

2022-04-15 12:57 UTC, pascalgrimaud commented on src/test/javascript/spec/springboot/primary/Generator.spec.ts
> +    // @ts-ignore
no other solution than add ts-ignore here?

2022-04-15 12:57 UTC, pascalgrimaud commented on src/test/javascript/spec/springboot/primary/Generator.spec.ts
> +    // @ts-ignore
no other solution than add ts-ignore here?

2022-04-16 08:31 UTC, pascalgrimaud commented on src/test/javascript/spec/springboot/primary/Generator.spec.ts
> +  });
hope @matthieulapatate can read this comment -> it can be take care in another PR, as this PR is opened since more than 1 week

2022-04-16 08:31 UTC, pascalgrimaud commented
I fix the last comments, then let's merge this PR

2022-04-16 08:47 UTC, pascalgrimaud approved these changes

2022-04-16 08:47 UTC, merged