Feat/issues/1096 kafka consumer
jhipster/jhipster-lite pull request #1283
Opened 2022-04-08 12:56 UTC by fdelbrayelle

fix #1096

2022-04-08 16:06 UTC, fdelbrayelle commented
Remaining work...

```
[WARNING] Rule violated for class tech.jhipster.kafkaapp.dummy.infrastructure.primary.kafka.consumer.AbstractConsumer: lines covered ratio is 0.85, but expected minimum is 1.00
[WARNING] Rule violated for class tech.jhipster.kafkaapp.dummy.infrastructure.primary.kafka.consumer.AbstractConsumer: branches covered ratio is 0.66, but expected minimum is 1.00
```

Could you start reviewing the code please @pascalgrimaud?

2022-04-20 06:12 UTC, pascalgrimaud requested changes

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/DummyConsumerIT.java.mustache
> +  private DummyProducer dummyProducer;
By using DummyProducer here, it means DummyConsumer can't be used without DummyProducer

2 solutions here:
- 1 single API to generate both: producer and consumer
- change the test here to not use DummyProducer

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/DummyConsumerIT.java.mustache
> +    assertEquals(true, actualResult);
Use assertj

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/DummyConsumerTest.java.mustache
> +    assertEquals(true, actualResult);
Use assertj

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/DummyConsumerTest.java.mustache
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Use assertj instead

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/DummyConsumerTest.java.mustache
> +    verify(consumer, timeout(3000)).subscribe(Collections.singleton("queue.jhipster.dummy"));
Extract 3000 to local constant

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/KafkaConfiguration.java.mustache
> +  public KafkaProducer<String, String> kafkaProducer(KafkaProperties kafkaProperties) {
It confirms both producer and consumer need to be generated at the same time

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/KafkaPropertiesTest.java.mustache
> +    assertEquals("localhost:9092", kafkaProperties.getConsumer().get(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG));
Use assertj instead

2022-04-20 06:12 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/KafkaPropertiesTest.java.mustache
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Prefer assertj instead

2022-04-20 06:12 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot/brokers/kafka/dummy-consumer"
Change api to merge producer and consumer

2022-04-23 12:34 UTC, fdelbrayelle commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot/brokers/kafka/dummy-consumer"
I disagree, you don't want in any case to have the producer AND consumer in the same microservice.

2022-04-23 12:42 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot/brokers/kafka/dummy-consumer"
I'd prefer separate api too, but in this case, you need to rework the test and the configuration class I think

2022-04-30 21:21 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +        "KafkaConfiguration.java",
Maybe add this in `addConfiguration` above?

2022-05-01 05:45 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +        "KafkaConfiguration.java",
Yes it's better

2022-05-01 14:11 UTC, pascalgrimaud approved these changes

2022-05-01 14:12 UTC, merged