support gradle init and wrapper
jhipster/jhipster-lite pull request #1292
Opened 2022-04-08 20:25 UTC by atomfrede

This PR add initial gradle support for init and wrapper. I decided to use kotlin dsl. 

The PR is still in draft mode as I just wanted to know if the structure is fine or if something totally wrong and should be changed. After your go @pascalgrimaud I will go on and add needles for dependencies and so on.

updates #408

2022-04-08 20:41 UTC, pascalgrimaud commented
Oh thanks a lot @atomfrede 
Just have a very very quick review and the structure seems good
I can review it tomorrow but I'd prefer adding needles, dependencies etc in separated PRs (using this PR as start point) if possible. It will be easier to review, if you're ok

2022-04-08 20:48 UTC, atomfrede commented
Sure even better. Take your time no need to hurry. Will need some testing if the kotlin dsl syntax is complete

2022-04-09 05:50 UTC, atomfrede commented
@pascalgrimaud The first part is done and everythings works fine. I did not check the sonar duplications yet, but as maven and gradle are quite similar I expected that. I would not try find and extract common parts to be honest.

2022-04-09 08:27 UTC, pascalgrimaud requested changes

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/domain/Gradle.java
> +}
```suggestion
import java.util.Map;

public class Gradle {

  private Gradle() {}

  public static Map<String, String> gradleWrapper() {
    // prettier-ignore
    return Map.of(
      "gradlew", ".",
      "gradlew.bat", ".",
      "gradle-wrapper.jar", "gradle/wrapper",
      "gradle-wrapper.properties", "gradle/wrapper"
    );
  }
}
```

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/domain/GradleDomainService.java
> +    projectRepository.add(project, sourceWrapper, "gradle-wrapper.properties", destinationWrapper);
```suggestion
    Gradle
      .gradleWrapper()
      .forEach((file, location) -> projectRepository.add(project, getPath(SOURCE, location), file, location));
    projectRepository.setExecutable(project, "", "gradlew");
    projectRepository.setExecutable(project, "", "gradlew.bat");
```

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/README.md
> +# Maven
```suggestion
# Gradle
```

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/application/GradleApplicationService.java
> +    gradleService.addJavaBuildGradleKts(project);
not covered by int test

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/infrastructure/primary/rest/GradleResource.java
> +  @GeneratorStep(id = GeneratorAction.MAVEN_JAVA)
need a new constant here

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/infrastructure/primary/rest/GradleResource.java
> +  @GeneratorStep(id = GeneratorAction.MAVEN_JAVA_POM_XML)
same, need a new constant here

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/infrastructure/primary/rest/GradleResource.java
> +  @GeneratorStep(id = GeneratorAction.MAVEN_WRAPPER)
new constant too

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/domain/GradleDomainService.java
> +  }
if not needed yet, you can remove I think

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/domain/GradleService.java
> +  Optional<String> getVersion(String name);
remove if it's not needed yet

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/infrastructure/primary/rest/GradleResource.java
> +  public void addPomXml(@RequestBody ProjectDTO projectDTO) {
rename method

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/infrastructure/primary/rest/GradleResource.java
> +  public void addMavenWrapper(@RequestBody ProjectDTO projectDTO) {
rename method

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/infrastructure/primary/rest/GradleResource.java
> +    gradleApplicationService.addBuildGradle(project);
not covered by test

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/resources/generator/buildtool/gradle/build.gradle.kts.mustache
> +plugins {
wonder if we should format with 2 spaces for indent, to be consistent with all the appliaction

2022-04-09 08:27 UTC, pascalgrimaud commented on src/main/resources/generator/buildtool/gradle/build.gradle.kts.mustache
> +  set("junit-jupiter.version", "5.8.2")
the indentation is good here :)

2022-04-09 08:27 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/buildtool/gradle/infrastructure/primary/rest/GradleResourceIT.java
> +  void shouldAddMavenWrapper() throws Exception {
rename test

2022-04-09 08:40 UTC, atomfrede commented
Thanks for the review! Will have a look later today.

2022-04-09 09:06 UTC, pascalgrimaud commented
For maven, I launch: ./mvnw clean verify
What is the similar command for gradle plz?

2022-04-09 09:42 UTC, atomfrede commented
./gradlew check should do it

2022-04-09 17:59 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/domain/GradleDomainService.java
> +  }
Still thinking how to get the version.

2022-04-09 18:00 UTC, atomfrede commented on src/main/resources/generator/buildtool/gradle/build.gradle.kts.mustache
> +plugins {
Will do, we should

2022-04-09 18:43 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/generator/buildtool/gradle/domain/GradleDomainService.java
> +  }
Remove for now as not needed (yet)

2022-04-09 19:47 UTC, pascalgrimaud approved these changes

2022-04-09 19:48 UTC, pascalgrimaud commented
Thanks and good job @atomfrede 
I'll take care of the CI, as it needs some customisation before adding Gradle there :)

2022-04-09 19:48 UTC, merged

2022-04-09 20:39 UTC, pascalgrimaud commented
Strange, I got this error:

```
22:38:07 in /tmp/jhlite/gradleapp on  main took 4s 
➜ ./gradlew check
> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [**/*Test.*](filter.includeTestsMatching)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
3 actionable tasks: 1 executed, 2 up-to-date

22:38:15 in /tmp/jhlite/gradleapp on  main took 3s 
➜ ll src/test/java/tech/jhipster/gradleapp/error/domain/*Test.*
-rw-rw-r-- 1 pgrimaud pgrimaud 4,4K avril  9 22:35 src/test/java/tech/jhipster/gradleapp/error/domain/AssertTest.java
-rw-rw-r-- 1 pgrimaud pgrimaud 1,3K avril  9 22:35 src/test/java/tech/jhipster/gradleapp/error/domain/MissingMandatoryValueExceptionTest.java
-rw-rw-r-- 1 pgrimaud pgrimaud 2,9K avril  9 22:35 src/test/java/tech/jhipster/gradleapp/error/domain/UnauthorizedValueExceptionTest.java

```

2022-04-09 20:56 UTC, atomfrede commented
Ah maybe I just did compile when testing it. But yes when there are no tests the tasks fails (at least I had that with another project already). Let me check tomorrow if it can be configured.

2022-04-09 20:58 UTC, pascalgrimaud commented
@atomfrede : in order, I use: init, gradle, java-base, so there are some tests (see my logs). I didn't find the solution yet, as I'm noob with Gradle :-D

2022-04-09 21:02 UTC, atomfrede commented
That's really strange. Let me check. Maybe something with the kotlin dsl ( first time using it)

2022-04-09 21:06 UTC, pascalgrimaud commented
I found this https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestFilter.html and using this, seems better:

![image](https://user-images.githubusercontent.com/9156882/162591649-d45601a6-743a-40c0-bd9a-3e0abad6778b.png)

![image](https://user-images.githubusercontent.com/9156882/162591664-2fc9b3a7-2d1f-4f5e-8c2d-6ea43c8cae14.png)

2022-04-10 04:29 UTC, atomfrede commented
Thanks @pascalgrimaud ! Indeed difference between groovy and kotlin dsl as the other exclusion works fine with the groovy dsl

2022-04-10 04:44 UTC, atomfrede commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/71921

2022-04-10 04:46 UTC, pascalgrimaud commented
@atomfrede : welcome to this project and thanks for your work here :)
Approved!