add github actions for gradle based builds
jhipster/jhipster-lite pull request #1342
Opened 2022-04-13 19:40 UTC by atomfrede

updates #1297

2022-04-14 07:41 UTC, pascalgrimaud requested changes

2022-04-14 07:41 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/ci/github/actions/application/GitHubActionsApplicationService.java
> +    gitHubActionsService.addGithubActions(project);
I think we can merge these 2 methods

2022-04-14 07:41 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/ci/github/actions/domain/GitHubActionsService.java
> +  void addGithubActions(Project project);
typo: addGithubActions -> addGitHubActions :-)

2022-04-14 07:41 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/ci/github/actions/infrastructure/primary/rest/GitHubActionsResource.java
> +  }
maybe merge both API, to use 1 single as the logic is in domainService

2022-04-14 08:08 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/generator/ci/github/actions/infrastructure/primary/rest/GitHubActionsResource.java
> +  }
Thought so too, was not sure. Will change it.

2022-04-16 07:06 UTC, pascalgrimaud approved these changes

2022-04-16 07:07 UTC, pascalgrimaud commented
thanks a lot @atomfrede !

2022-04-16 07:07 UTC, merged

2022-04-17 19:38 UTC, atomfrede commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/73020

2022-04-17 19:48 UTC, pascalgrimaud commented
@atomfrede : approved