Fix #691 - Add Mongock support
jhipster/jhipster-lite pull request #1424
Opened 2022-04-21 13:00 UTC by beatfreaker

Fix #691 - Add Mongock support

2022-04-22 06:03 UTC, beatfreaker commented
@pascalgrimaud can you please review this PR

2022-04-22 07:02 UTC, pascalgrimaud commented
@beatfreaker : yes, will do it when possible. I'm a little bit late, as I have several PRs to review before this one. Just be patient :)

2022-04-22 16:48 UTC, pascalgrimaud commented
@beatfreaker : can you resolve the conflict plz?

2022-04-22 17:05 UTC, pascalgrimaud requested changes

2022-04-22 17:05 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/domain/MongockDomainService.java
> +    String packageNamePath = project.getPackageNamePath().orElse(getPath("com/mycompany/myapp"));
use constants in DefaultConfig

2022-04-22 17:05 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/domain/MongockDomainService.java
> +    String mongockDBMigrationPath = "technical/infrastructure/secondary/mongock/dbmigration";
use TECHNICAL_INFRASTRUCTURE_SECONDARY

2022-04-22 17:05 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/mongock/InitialMigrationSetup.java.mustache
> +}
```suggestion
  public void rollback() {}
}
```

2022-04-22 17:05 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/mongock/InitialMigrationSetup.java.mustache
> +  }
```suggestion
  public InitialMigrationSetup(MongoTemplate template) {
    this.template = template;
  }
```

2022-04-22 17:05 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/application/MongockApplicationServiceIT.java
> +    Project project = ProjectDTO.toProject(projectDTO);
```suggestion
    ProjectDTO projectDTO = TestUtils.readFileToObject("json/chips.json", ProjectDTO.class).folder(tmpDirForTest());
    Project project = ProjectDTO.toProject(projectDTO);
```

2022-04-22 17:07 UTC, pascalgrimaud commented
Very good job here, @beatfreaker 
I still have 3 other comments:
- plz add a package-info.java, defined as a BusinessContext
- plz add a new README.md (similar to what is done in maven/README.md)
- call the API in the generate.sh file, at the same level than mongodbapp

2022-04-26 05:41 UTC, beatfreaker commented
Hello @pascalgrimaud 

currently the build is failing for `mongodbapp` execution, and I suspect it is because of following warning

```
Warning:  Rule violated for class tech.jhipster.fullapp.technical.infrastructure.secondary.mongock.dbmigration.InitialMigrationSetup: lines covered ratio is 0.00, but expected minimum is 1.00
Warning:  Rule violated for class tech.jhipster.fullapp.technical.infrastructure.secondary.mongock.MongockDatabaseConfiguration: lines covered ratio is 0.00, but expected minimum is 1.00
```

As these generated files does not have any logic so I don't know what should we write in unit tests, could you please help me with it ?

2022-04-26 05:43 UTC, pascalgrimaud commented
@beatfreaker : sure, what do you prefer? Suggestion in comment or commit directly to your branch ?

2022-04-26 05:50 UTC, beatfreaker commented
@pascalgrimaud I am okay with both,

If you have limited time then just add it here, I can put it in code and test it.

2022-04-26 09:29 UTC, pascalgrimaud requested changes

2022-04-26 11:10 UTC, beatfreaker commented
> @beatfreaker : here the simple unit test you can use:
> 
> ```java
> @UnitTest
> @ExtendWith(MockitoExtension.class)
> class InitialMigrationSetupTest {
> 
>   @InjectMocks
>   InitialMigrationSetup initialMigrationSetup;
> 
>   @Test
>   void shouldChangeSet() {
>     assertThatCode(() -> initialMigrationSetup.changeSet()).doesNotThrowAnyException();
>   }
> 
>   @Test
>   void shouldRollback() {
>     assertThatCode(() -> initialMigrationSetup.rollback()).doesNotThrowAnyException();
>   }
> }
> ```

This helps, thank you

2022-04-26 12:35 UTC, pascalgrimaud commented
Fine to remove it, in this initial migration file.
In the other migration files (for User for example), it will be there, so no worry about that

2022-04-27 05:42 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/README.md
> +- [Pascal Grimaud](https://github.com/pascalgrimaud)
Don't you want to take the lead on this part @beatfreaker ? :-)

2022-04-27 05:49 UTC, beatfreaker commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/README.md
> +- [Pascal Grimaud](https://github.com/pascalgrimaud)
I can, updating it :)

2022-04-27 05:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/mongock/README.md
> +- [Pascal Grimaud](https://github.com/pascalgrimaud)
Yes plz put your name :-)

2022-04-27 06:35 UTC, pascalgrimaud approved these changes

2022-04-27 06:35 UTC, merged

2022-04-27 06:36 UTC, pascalgrimaud commented
Thanks for your work here @beatfreaker :heart:

2022-04-30 19:11 UTC, beatfreaker commented
@pascalgrimaud Bounty claimed at https://opencollective.com/generator-jhipster/expenses/74748

2022-04-30 19:16 UTC, pascalgrimaud commented
@beatfreaker : approved. If possible, can you contribute to the front part too? Otherwise, the feature won't be available

2022-04-30 19:22 UTC, beatfreaker commented
@pascalgrimaud yeah sure I can make respective changes on frontend too, will create new ticket to handle it.