History generator
jhipster/jhipster-lite pull request #1449
Opened 2022-04-23 10:41 UTC by MSaguer

To close #1445 

Add new timestamp field in history file.
For back compatibilty's sake, null timestamp values are authorized as timestamp values.

2022-04-23 10:44 UTC, MSaguer commented
Miss the HistoryDTO update to end this

2022-04-23 14:24 UTC, Bolo89 requested changes

2022-04-23 14:24 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/common/domain/TimeUtils.java
> +  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
Maybe use a standard date time format ? the timezone does not appear here (ISO)

2022-04-23 14:24 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/common/domain/TimeUtils.java
> +  public static String getNowTimestamp(Clock clock, int plusSecond) {
Maybe i'm wrong but for me, timestamp is the time passed between 1970 and now. If I read the method name, I except a long value instead of a string

2022-04-23 14:24 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/history/infrastructure/primary/GeneratorHistoryInterceptor.java
> +    GeneratorHistoryValue generatorHistoryValue = new GeneratorHistoryValue(serviceId, TimeUtils.getNowTimestamp(clock));
clock.instant() is enough ? I think it's better to keep instant as parameter instead of string. Maybe tomorrow the history will be saved in database, and instant is standard

2022-04-28 06:27 UTC, pascalgrimaud commented
@MSaguer : the review was done by @Bolo89, can you take care of it plz ? And resolve conflict too plz

2022-04-29 09:03 UTC, MSaguer commented on src/main/java/tech/jhipster/lite/common/domain/TimeUtils.java
> +  public static String getNowTimestamp(Clock clock, int plusSecond) {
I've changed this to getDateString. Is that ok for you?

2022-04-29 09:07 UTC, MSaguer commented on src/main/java/tech/jhipster/lite/common/domain/TimeUtils.java
> +  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
That's the date time format used for the liquibase xml file naming. As it was used two times in 2 differents classes, I've just refactored existing code into one util class.
I don't think that behaviour shall be changed in this MR.

2022-04-29 09:12 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/common/domain/TimeUtils.java
> +  public static String getNowTimestamp(Clock clock, int plusSecond) {
Yes

2022-04-29 09:13 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/common/domain/TimeUtils.java
> +  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
OK this format is only used for file name

2022-04-29 09:14 UTC, MSaguer commented
@pascalgrimaud first modification batch.
Work in progress  : creation of GeneratorHistoryDTO to solve the ArchUnit test on domain dependency to Jackson annotation.

@Bolo89 I've change the timestamp type from String  to Instant. Is the new serialized format "yyyy-MM-dd HH:mm:ss" Ok for you?

2022-04-29 11:48 UTC, Bolo89 commented
@MSaguer, in the format  "yyyy-MM-dd HH:mm:ss", the timezone / offset is skipped. Possible to have this format ? `2022-02-22T10:11:12.000Z` ? (used when you convert instant to string)

```java
@JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ss.SSSZ", timezone = "UTC")
```

or for global configuration of the objectMapper in JSonUtils.java
```java
new ObjectMapper()
                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
```

2022-04-29 19:01 UTC, MSaguer commented
thanks @Bolo89. Adding ObjectMapper configuration in JsonUtils was what I was lokking for.

2022-04-29 19:04 UTC, MSaguer commented
There is a sonar "code smell" that I can't easily solve
![image](https://user-images.githubusercontent.com/42449441/166009511-492440dd-3c90-43e4-92e7-a52a5553eb46.png)

I think that the only solution is to add `@SuppressWarnings("java:S110")`

Do you agree?

2022-04-29 19:10 UTC, pascalgrimaud commented
Agree @MSaguer as it does not depend on our code

2022-05-01 16:21 UTC, pascalgrimaud commented
this part will probably have an impact with the front part, so I'll have a deep look + tests before merging this

2022-05-03 16:49 UTC, Bolo89 approved these changes

2022-05-05 06:13 UTC, pascalgrimaud commented
@MSaguer : can you solve conflict plz?

2022-05-06 08:52 UTC, merged