Add Spring Cloud Gateway
jhipster/jhipster-lite pull request #1502
Opened 2022-04-26 13:55 UTC by juliensadaoui

related at #1500

2022-04-28 15:21 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/gateway/infrastructure/primary/rest/GatewayResource.java
> +  @GeneratorStep(id = GeneratorAction.EUREKA_CLIENT)
The generatorstep id should be '' springCloudGateway '' and not eurekaclient ?

2022-05-12 13:15 UTC, pascalgrimaud requested changes

2022-05-12 13:15 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/springcloud/gateway/java/GatewayResource.java.mustache
> +public class GatewayResource {
No need public

2022-05-12 13:15 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/springcloud/gateway/java/RouteVM.java.mustache
> +    private String path;
Indentation missing prettier here

2022-05-12 13:15 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/springcloud/gateway/java/test/GatewayResourceIT.java.mustache
> +class GatewayResourceIT {
Need prettier to reorganize a little bit the imports

2022-05-13 03:07 UTC, pascalgrimaud approved these changes

2022-05-13 03:07 UTC, merged

2022-05-15 17:49 UTC, juliensadaoui commented
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/76937