Vue: add login context with simple form page
jhipster/jhipster-lite pull request #1591
Opened 2022-05-04 17:23 UTC by matthieuRioual

- related to #897

2022-05-05 06:10 UTC, pascalgrimaud requested changes

2022-05-05 06:10 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/core/domain/VueDomainService.java
> +  }
as discussed, this part should not be included in `client/vue/core`, it should be in a separated context like `client/vue/security/jwt`, so later we can have `client/vue/security/oauth2`

2022-05-05 06:10 UTC, pascalgrimaud commented
I'm converting this PR to draft, as it's not ready yet

2022-05-10 20:21 UTC, pascalgrimaud commented
Can you have a look plz @seraphinandrieux ?
I'll do the same when possible

2022-05-11 07:09 UTC, seraphinandrieux approved these changes

2022-05-11 07:09 UTC, seraphinandrieux commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwt.java
> +  public static boolean checkIfPinia(Project project) {
```suggestion
  public static boolean isPiniaImplemented(Project project) {
```

2022-05-11 07:09 UTC, seraphinandrieux commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwtDomainService.java
> +  public static final String DESTINATION_PRIMARY = "src/main/webapp/app/common/primary/";
I believe you have these const already set into a class. @pascalgrimaud I cannot remember which one ?

2022-05-11 07:09 UTC, seraphinandrieux commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwtDomainService.java
> +    if (!VueJwt.checkIfPinia(project)) throw new GeneratorException("Pinia has not been added");
If you use only once this method, you should problably update it into `isPiniaNotImplemented`

2022-05-11 07:09 UTC, seraphinandrieux commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwtDomainService.java
> +    Assert.notNull("project", project);
Besides extract the two assertions

2022-05-11 07:09 UTC, seraphinandrieux commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwtDomainService.java
> +    projectRepository.template(project, getPath(SOURCE, SOURCE_DOMAIN), "Login.ts", DESTINATION_DOMAIN);
Extract all files which have to be generated into Domain, and do a for each here to call template method

2022-05-11 07:09 UTC, seraphinandrieux commented on src/test/java/tech/jhipster/lite/generator/client/vue/security/jwt/infrastructure/primary/rest/VueJwtResourceIT.java
> +class VueJwtResourceIT {
I think it misses some tests

2022-05-11 20:01 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwtDomainService.java
> +  public static final String DESTINATION_PRIMARY = "src/main/webapp/app/common/primary/";
Yes, simply see Constants

2022-05-19 04:43 UTC, pascalgrimaud commented
@matthieuRioual : can it be closed in favor of https://github.com/jhipster/jhipster-lite/pull/1759 ?

2022-05-19 06:28 UTC, closed without merging