Add Pulsar generator
jhipster/jhipster-lite pull request #1745
Opened 2022-05-16 19:44 UTC by cbornet

2022-05-17 04:09 UTC, pascalgrimaud commented
Nice to see this contribution, thanks a lot @cbornet 
Don't hesitate to ping me if you need help

2022-05-23 09:15 UTC, cbornet commented
I fixed the CI issues. Ready for review.

2022-05-23 09:44 UTC, pascalgrimaud commented
Thanks a lot @cbornet : will review it soon :)

2022-05-24 16:43 UTC, pascalgrimaud requested changes

2022-05-24 16:43 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarDomainService.java
> +    final Dependency dependency = Dependency.builder().groupId("org.apache.pulsar").artifactId("pulsar-client").version("2.10.0").build();
the version should not be hard code here, add it to there: https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/dependencies/pom.xml#L35

So it will be upgraded automatically by dependabot

2022-05-24 16:43 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarDomainService.java
> +    springBootCommonService.addProperties(project, "pulsar.client.service-url", "pulsar://localhost:6650");
after that, could add a new line:

```
springBootCommonService.addPropertiesNewLine(project);
```

2022-05-24 16:43 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarDomainService.java
> +    springBootCommonService.addPropertiesTest(project, "pulsar.consumer.subscription-name", "test-subscription");
after that, could add a new line:

```
springBootCommonService.addPropertiesTestNewLine(project);
```

2022-05-24 16:43 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/pulsar/pulsar.yml.mustache
> +      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
wonder if this additional space " -Xms512" is intended?

2022-05-25 10:01 UTC, cbornet commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarDomainService.java
> +    final Dependency dependency = Dependency.builder().groupId("org.apache.pulsar").artifactId("pulsar-client").version("2.10.0").build();
done

2022-05-25 10:01 UTC, cbornet commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarDomainService.java
> +    springBootCommonService.addPropertiesTest(project, "pulsar.consumer.subscription-name", "test-subscription");
done

2022-05-25 10:01 UTC, cbornet commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/pulsar/domain/PulsarDomainService.java
> +    springBootCommonService.addProperties(project, "pulsar.client.service-url", "pulsar://localhost:6650");
done

2022-05-25 10:02 UTC, cbornet commented
@pascalgrimaud I've done the changes and fixed the docker-compose file

2022-05-25 11:30 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/pulsar/pulsar.yml.mustache
> +      - 8080:8080
it can conflict with the default port of spring boot app.
Is it used ? Can we use another port in this case ?

2022-05-30 12:21 UTC, cbornet commented on src/main/resources/generator/server/springboot/broker/pulsar/pulsar.yml.mustache
> +      - 8080:8080
Which port would be good ?

2022-05-30 18:08 UTC, pascalgrimaud approved these changes

2022-05-30 18:08 UTC, merged