Vue: authentication JWT
jhipster/jhipster-lite pull request #1759
Opened 2022-05-17 14:45 UTC by matthieuRioual

Add authentication progress to vue application through pinia storage.

A login page has been created as a guard route.

Once connected you can access application single page and check your identity or ever log out.

Before adding jwt to vue generated application, make sur you added pinia or it gonna throw an error.

You can test it on this branch with credentials "admin, admin"

- fix https://github.com/jhipster/jhipster-lite/issues/897

2022-05-18 09:45 UTC, pascalgrimaud commented
I edited your initial description to link to the original ticket

2022-05-18 10:17 UTC, pascalgrimaud requested changes

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwtDomainService.java
> +    if (VueJwt.isPiniaNotImplemented(project)) throw new GeneratorException("Pinia has not been added");
```suggestion
    if (VueJwt.isPiniaNotImplemented(project)) {
      throw new GeneratorException("Pinia has not been added");
    }
```

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/domain/VueJwtDomainService.java
> +  }
I don't understand as there is already VueLogo and JHipster-Lite-neon-green in the project. Why should VueJWT add these files ?

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/infrastructure/primary/rest/VueJwtResource.java
> +  @Operation(summary = "Add JWT to vue ap", description = "Add Jwt")
```suggestion
  @Operation(summary = "Add JWT to Vue application")
```

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/infrastructure/primary/rest/VueJwtResource.java
> +  @ApiResponse(responseCode = "500", description = "An error occurred while adding JWT on Vue")
```suggestion
  @ApiResponse(responseCode = "500", description = "An error occurred while adding JWT to Vue application")
```

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vue/security/jwt/infrastructure/primary/rest/VueJwtResource.java
> +  @GeneratorStep(id = GeneratorAction.VUE)
not correct, should be a new GeneratorAction

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/test/spec/jwt/primary/login/Login.spec.ts.mustache
> +  */
why this comment ?

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/test/spec/jwt/secondary/LoginDTO.spec.ts.mustache
> +import { LoginDTO, toLoginDTO } from '@/common/secondary/LoginDTO';
little bit strange to have the name LoginDTO
It's used more often for the backend, not the frontend

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/jwt/primary/app/App.html.mustache
> +</div>
don't understand this file, it's already generated by vue/core

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/jwt/primary/login/Login.html.mustache
> +<div id="login">
fix indent of this file, it should be with 2 spaces

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/jwt/primary/login/Login.vue.mustache
> +    align-items: center;
review indent

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/jwt/primary/welcome/Welcome.component.ts.mustache
> +
prettier: should remove this line

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/jwt/primary/welcome/Welcome.html.mustache
> +<div id="welcome">
same, don't understand this page, as there is already a home page, generated by vue/core

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/jwt/secondary/ConsoleLogger.ts.mustache
> +import { Logger } from '@/common/domain/Logger';
maybe it should be included by default in vue/core, instead of this PR ?

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/jwt/secondary/LoginDTO.ts.mustache
> +export interface LoginDTO {
as said previously, the name is a little bit strange

2022-05-18 10:17 UTC, pascalgrimaud commented on src/main/resources/generator/client/vue/webapp/app/router/router.ts.mustache
> +    {{#auth}}
I don't think we should do this, as the router already exist in the project, with specific routes from the user. By doing this, you'll erase all the route.

Instead, we should insert the new routes, in an existing file

2022-05-18 13:13 UTC, matthieulapatate commented on src/main/resources/generator/client/vue/test/spec/jwt/secondary/LoginDTO.spec.ts.mustache
> +import { LoginDTO, toLoginDTO } from '@/common/secondary/LoginDTO';
What about restLogin ? (proposed by Hypolite)

2022-05-18 13:17 UTC, matthieulapatate commented on src/main/resources/generator/client/vue/webapp/app/jwt/primary/app/App.html.mustache
> +</div>
Indeed, but but since this is this component mounted on the main.ts i changed the simple html by router view to route the application either to Welcome Component nor to Login Component

2022-05-31 15:19 UTC, pascalgrimaud commented
another comment: this feature is not tested in the CI, you need to update the generate.sh file

2022-06-18 23:59 UTC, closed without merging