Add MSSQL core
jhipster/jhipster-lite pull request #1770
Opened 2022-05-18 09:27 UTC by seraphinandrieux

- Fix #428

2022-05-27 08:36 UTC, pascalgrimaud requested changes

2022-05-27 08:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mssql/domain/MssqlService.java
> +  void addLoggerInConfiguration(Project project);
wonder if we need to expose all these methods, only init should be needed, I think

2022-05-27 08:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/docker/application/DockerApplicationServiceIT.java
> +    assertThat(imageNameWithVersion).contains("mysql:8.0.29");
as the version is hard coded here, I afraid it will fail when the version of mysql will be upgraded

2022-05-27 08:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/docker/application/DockerApplicationServiceIT.java
> +    assertThat(imageVersion).contains("8.0.29");
same comment about hard coded version

2022-05-27 08:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/MongodbAssert.java
> +    assertFileContent(project, "src/main/docker/mongodb.yml", "mongo:5.0.8");
same comment about hard coded version

2022-05-27 08:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/mssql/infrastructure/primary/rest/MssqlResourceIT.java
> +    Project project = ProjectDTO.toProject(projectDTO);
replace this part by another one, which is better: https://github.com/jhipster/jhipster-lite/blob/main/src/test/java/tech/jhipster/lite/generator/server/springboot/core/infrastructure/primary/rest/SpringBootResourceIT.java#L42-L43

2022-05-27 08:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/mysql/application/MySQLApplicationServiceIT.java
> +      List.of("spring.datasource.url=jdbc:tc:mysql:8.0.29:///jhipster", "spring.datasource.username=jhipster")
same comment about hard coded version

2022-05-27 08:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/mysql/application/MySQLApplicationServiceIT.java
> +    assertFileContent(project, "src/main/docker/mysql.yml", "mysql:8.0.29");
same comment about hard coded version

2022-05-27 08:36 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot/caches/ehcache/xml-configuration"
not related to MSSQL, no need liquibase for now, no need cache
we can add this later if needed

2022-05-27 08:57 UTC, seraphinandrieux commented on src/test/java/tech/jhipster/lite/generator/docker/application/DockerApplicationServiceIT.java
> +    assertThat(imageNameWithVersion).contains("mysql:8.0.29");
The dependabot is not here to do it for us ?

2022-05-27 13:02 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/docker/application/DockerApplicationServiceIT.java
> +    assertThat(imageNameWithVersion).contains("mysql:8.0.29");
I think contains("mysql") is enough, without the version, don't you think ?

2022-05-27 14:43 UTC, seraphinandrieux commented on src/test/java/tech/jhipster/lite/generator/docker/application/DockerApplicationServiceIT.java
> +    assertThat(imageVersion).contains("8.0.29");
I can't for this one remove it, the method tests which version is used

2022-05-27 14:44 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/docker/application/DockerApplicationServiceIT.java
> +    assertThat(imageVersion).contains("8.0.29");
Oh ok, then let's keep like this so, and improve it in another PR

2022-05-28 05:35 UTC, pascalgrimaud submitted a review, later dismissed

2022-05-28 05:54 UTC, pascalgrimaud commented
Something wrong in the CI, as it took a lot of time
I need to investigate

2022-06-15 12:47 UTC, pascalgrimaud requested changes

2022-06-15 12:47 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/core/IntegrationTest.java.mustache
> +// jhipster-needle-annotation-it
Same comment about needle, no need it here

2022-06-15 12:47 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/core/ReactiveSqlTestContainerExtension.java.mustache
> +public class ReactiveSqlTestContainerExtension implements BeforeAllCallback {
I'd rename this class, and remove Reactive as we are using jdbc and not rdbc here

2022-06-15 15:26 UTC, pascalgrimaud approved these changes

2022-06-15 15:26 UTC, merged

2022-06-15 15:30 UTC, seraphinandrieux commented
$300 bounty claimed: https://opencollective.com/generator-jhipster/expenses/82466