React jwt
jhipster/jhipster-lite pull request #1776
Opened 2022-05-18 15:03 UTC by flcarre

2022-05-18 15:06 UTC, flcarre commented
remaining

- [ ] add react jwt to generator
- [ ] modify app.tsx by adding <LoginForm /> composant
- [ ] add tests to generated
- [ ] add tests to generator

2022-06-16 16:35 UTC, fdelbrayelle commented on src/main/resources/generator/client/react/src/main/webapp/app/login/primary/LoginForm/index.tsx.mustache
> +    setUsername,
I mean in the generated project

2022-06-24 12:32 UTC, fdelbrayelle requested changes

2022-06-24 12:32 UTC, fdelbrayelle commented on src/main/resources/generator/client/react/src/main/webapp/app/common/primary/app/LoginApp.tsx.mustache
> +    <div className="App">
Why is there just a basic template here and no login form?

2022-06-24 12:32 UTC, fdelbrayelle commented on src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginForm/index.tsx.mustache
> +    setOpen(true);
Oneline ?

2022-06-24 12:32 UTC, fdelbrayelle commented on src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginForm/index.tsx.mustache
> +    setOpen(false);
Oneline ?

2022-06-24 12:32 UTC, fdelbrayelle commented on src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginForm/index.tsx.mustache
> +        Se connecter
No i18n ?

2022-06-24 12:32 UTC, fdelbrayelle commented on src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginModal/index.tsx.mustache
> +  login({ ...loginData, setUsername, setToken });
`npm run prettier:format` on generated project to indent better mustache files

2022-06-24 12:32 UTC, fdelbrayelle commented on src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginModal/index.tsx.mustache
> +  setError(false);
same : indentation :warning:

2022-06-24 12:34 UTC, flcarre commented on src/main/resources/generator/client/react/src/main/webapp/app/login/primary/loginForm/index.tsx.mustache
> +        Se connecter
I18n not already plug

2022-06-24 16:13 UTC, fdelbrayelle submitted a review, later dismissed

2022-06-30 05:15 UTC, pascalgrimaud commented
Can you solve the conflict plz? So it can be merged

2022-06-30 06:41 UTC, flcarre commented
> Can you solve the conflict plz? So it can be merged

Done

2022-06-30 06:45 UTC, merged