[WIP] Add java dependencies in module
jhipster/jhipster-lite pull request #1859
Opened 2022-05-26 19:04 UTC by DamnClin

Closes: https://github.com/jhipster/jhipster-lite/issues/1787

TODO:
- [ ] Maven infrastructure code

2022-05-27 16:18 UTC, DamnClin commented
Still some work left but this is moving :D

2022-05-28 07:52 UTC, pascalgrimaud requested changes

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/ArtifactId.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency;
I'd rename to javadependency

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/DependencyId.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency;
I'd rename to javadependency

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/GroupId.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency;
I'd rename to javadependency

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/JavaDependencies.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency;
I'd rename to javadependency

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/JavaDependenciesCurrentVersionsRepository.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency;
I'd rename to javadependency

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/JavaDependenciesVersions.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency;
I'd rename to javadependency

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/command/JavaDependencyCommandType.java
> +  SET_VERSION,
maybe rename to UPDATE ?

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/FileSystemJHipsterModuleFiles.java
> +        Files.writeString(filePath, file.content());
could we add a log debug or log info here? So it's nice to know what happens

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/FileSystemProjectJavaDependenciesRepository.java
> +  private static final String VERSION_SUFFIX = ".version";
could we use the constant from VersionSlug?

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/FileSystemProjectJavaDependenciesRepository.java
> +    Path pomPath = folder.filePath("pom.xml");
Use Constants POM_XML ?

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/InvalidPomException.java
> +    super("Your pom file is invalid, you have to define, at least, an artifact id fro your project");
```suggestion
    super("Your pom.xml file is invalid, you have to define, at least, an artifact id for your project");
```

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/MavenCommandHandler.java
> +        writer.write(JOOX.$(e).toString().replace("\r\n", "\n"));
maybe use constants from WordUtils ?

2022-05-28 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/MissingPomException.java
> +    super("Can't find pom in " + folder.folder());
```suggestion
    super("Can't find pom.xml in " + folder.folder());
```

2022-05-28 07:56 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/module/JHipsterModules.java
> +package tech.jhipster.lite.generator.module;
Unfortunately yes... This service is intended to be called by basically everyone and:

- This can't be a primary since they can only be called by secondary (which adds a useless overload).
- This can't be in domain since it's a spring bean
- This can't be in secondary since it don't really fits in there

I think we have to see that as a public API, that's why I ended up putting it here. I also though about a dedicated package but that sounds overkill

2022-05-28 07:59 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/MavenCommandHandler.java
> +        writer.write(JOOX.$(e).toString().replace("\r\n", "\n"));
I don't like using such general thinks between packages...

2022-05-28 08:01 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/command/JavaDependencyCommandType.java
> +  SET_VERSION,
That was the original but it's not a good idea since it's an upsert (creating the property if needed) so set sounds goods to me

2022-05-28 08:02 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/module/infrastructure/secondary/FileSystemJHipsterModuleFiles.java
> +        Files.writeString(filePath, file.content());
I need https://github.com/jhipster/jhipster-lite/pull/1867 for that :D

2022-05-28 08:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/JHipsterModules.java
> +package tech.jhipster.lite.generator.module;
thanks for explaining this

2022-05-28 08:57 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/command/AddJavaDependency.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency.command;
could you rename java_dependency too?

2022-05-28 09:00 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/module/domain/java_dependency/command/AddJavaDependency.java
> +package tech.jhipster.lite.generator.module.domain.java_dependency.command;
oopsy

2022-05-28 09:06 UTC, pascalgrimaud approved these changes

2022-05-28 09:07 UTC, pascalgrimaud commented
It's a big step in our engine !
thanks for your work @DamnClin !

2022-05-28 09:16 UTC, merged