Cucumber module
jhipster/jhipster-lite pull request #1875
Opened 2022-05-28 14:01 UTC by DamnClin

Module to add cucumber to a project

2022-05-28 14:02 UTC, DamnClin commented
@pascalgrimaud where do you think the project generation test should be added for this one?

2022-05-28 14:31 UTC, DamnClin commented
BTW this needs https://github.com/jhipster/jhipster-lite/pull/1874 :D

2022-05-28 14:54 UTC, pascalgrimaud commented
> @pascalgrimaud where do you think the project generation test should be added for this one?

Don't understand well the question. Shouldn't we keep the same structure of folder than in JH Lite ?

2022-05-28 15:34 UTC, DamnClin commented
> > @pascalgrimaud where do you think the project generation test should be added for this one?
> 
> Don't understand well the question. Shouldn't we keep the same structure of folder than in JH Lite ?

No, I mean I added it in `fullapp`, is this correct?

2022-05-28 15:35 UTC, pascalgrimaud commented
@DamnClin : oh yes, looks good to add this to fullapp

2022-05-29 04:47 UTC, pascalgrimaud approved these changes

2022-05-29 04:47 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber/infrastructure/primary/CucumberResource.java
> +  public void addJavaBase(@RequestBody ProjectDTO projectDTO) {
Wrong method name :-p

2022-05-29 04:47 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/ProjectsSteps.java
> +    // TODO
Still todo?

2022-05-29 08:10 UTC, pascalgrimaud requested changes

2022-05-29 08:10 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber/domain/CucumberModuleFactory.java
> +        .add(awaitilityDepencency())
it looks like it's adding 3 times the property:

![image](https://user-images.githubusercontent.com/9156882/170858656-82c43176-cd0a-4f2e-abc1-2e4105b25055.png)

2022-05-29 09:22 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber/infrastructure/primary/CucumberResource.java
> +  public void addJavaBase(@RequestBody ProjectDTO projectDTO) {
Copy pasta spotted :D

2022-05-29 09:23 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/generator/ProjectsSteps.java
> +    // TODO
No, changed my mind on this but forgot to remove...

2022-05-29 09:23 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber/domain/CucumberModuleFactory.java
> +        .add(awaitilityDepencency())
Oh, good catch, forgot about that case, will fix, thanks

2022-05-29 09:29 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber/domain/CucumberModuleFactory.java
> +        .add(awaitilityDepencency())
it's minor because prettier can do the job, but there are some additional useless spaces, which can be removed too. Can be done in a separated PR as improvement :)

2022-05-29 09:37 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/cucumber/domain/CucumberModuleFactory.java
> +        .add(awaitilityDepencency())
I think a dedicated for those useless spaces + useless line break in some cases after a removal can be a good idea since it may be more challenging than it looks and value is not that great (I gave it a 3mn try but failed...). The other points are fixed :D

2022-05-29 20:20 UTC, pascalgrimaud approved these changes

2022-05-29 20:20 UTC, merged