Feature/autofill projectdetails
jhipster/jhipster-lite pull request #1876
Opened 2022-05-28 14:26 UTC by swarajsaaj

Fix 1858

2022-06-03 06:06 UTC, pascalgrimaud requested changes

2022-06-03 06:06 UTC, pascalgrimaud commented on src/main/webapp/app/springboot/domain/ProjectService.ts
> +import { RestProject } from '../secondary/RestProject';
as we are in domain, we should not import a secondary

2022-06-03 06:06 UTC, pascalgrimaud commented on src/main/webapp/app/springboot/domain/ProjectService.ts
> +  getProjectDetails(folder: string): Promise<RestProject>;
maybe return a Promise<Project> instead ?

2022-06-03 10:43 UTC, swarajsaaj commented on src/main/webapp/app/springboot/domain/ProjectService.ts
> +  getProjectDetails(folder: string): Promise<RestProject>;
Do you mean `Promise<void>` instead of `Promise<RestProject>?`

2022-06-03 11:16 UTC, pascalgrimaud commented on src/main/webapp/app/springboot/domain/ProjectService.ts
> +  getProjectDetails(folder: string): Promise<RestProject>;
Yes, or Promise<Project>

2022-06-03 17:40 UTC, swarajsaaj commented on src/main/webapp/app/springboot/domain/ProjectService.ts
> +  getProjectDetails(folder: string): Promise<RestProject>;
Sure, as return type generic is not required for the feature, I have made it `Promise<void>` for generic required in promise

2022-06-03 17:41 UTC, swarajsaaj commented on src/main/webapp/app/springboot/domain/ProjectService.ts
> +import { RestProject } from '../secondary/RestProject';
Fixed in [727b697](https://github.com/jhipster/jhipster-lite/pull/1876/commits/727b6976e67a31641da8a03e8c794aa1831c755b)

2022-06-10 05:48 UTC, pascalgrimaud approved these changes

2022-06-10 05:48 UTC, merged

2022-06-10 18:28 UTC, swarajsaaj commented
bounty claimed at https://opencollective.com/generator-jhipster/expenses/81769

2022-06-10 18:29 UTC, pascalgrimaud commented
@swarajsaaj : approved :)