Rework OAuth2 module
jhipster/jhipster-lite pull request #2087
Opened 2022-06-14 18:23 UTC by DamnClin

Close https://github.com/jhipster/jhipster-lite/issues/1689

Still need todo the account module but I don't really know what's the need here, any business need appreciated on this part :)

2022-06-14 18:55 UTC, DamnClin commented
My current idea is to create an `Account` domain aggregate with: 

* Username
* Name
  * Firstname
  * Lastname
* Email
* Roles

With all those fields mandatory (with roles that can be empty) and provide tooling to read that from token and to expose an endpoint for the authenticated user.

What do you think?

2022-06-14 19:10 UTC, antarus commented
I think that's enough at first. we can always upgrade later

2022-06-14 19:10 UTC, pascalgrimaud commented
@DamnClin : yes it's exactly what should be done, a specific account context

2022-06-14 19:13 UTC, DamnClin commented
Ok, I should be able to do that tomorrow

2022-06-14 20:05 UTC, DanielFran requested changes

2022-06-14 20:05 UTC, DanielFran commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/domain/OAuth2ModuleFactory.java
> +      .add(SRPING_GROUP, artifactId("spring-boot-starter-oauth2-resource-server"))
```suggestion
      .add(SPRING_GROUP, artifactId("spring-boot-starter-security"))
      .add(SPRING_GROUP, artifactId("spring-boot-starter-oauth2-client"))
      .add(SPRING_GROUP, artifactId("spring-boot-starter-oauth2-resource-server"))
```

2022-06-15 11:21 UTC, pascalgrimaud approved these changes

2022-06-15 11:23 UTC, merged