Migrate Kafka domain service to new module system
jhipster/jhipster-lite pull request #2455
Opened 2022-07-08 15:35 UTC by fdelbrayelle

closes #2109

2022-07-10 14:33 UTC, DamnClin commented
Looks like this module is the lat user of src/main/java/tech/jhipster/lite/generator/readme so I think this package removal should be part of this PR

2022-07-11 08:23 UTC, DamnClin commented
/!\ breaking change incomming. In https://github.com/jhipster/jhipster-lite/pull/2500 the `dependency` method become `addDependency`. I can add some method for migration phase if you want

2022-07-11 13:07 UTC, fdelbrayelle commented
> Looks like this module is the lat user of src/main/java/tech/jhipster/lite/generator/readme so I think this package removal should be part of this PR

Yep I will remove it!

2022-07-11 13:09 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +      .and()
missing spaces

2022-07-11 13:09 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +            """
extract value to a dedicated method for readability

2022-07-11 13:09 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +            """
extract value to a dedicated method for readability

2022-07-11 13:11 UTC, fdelbrayelle commented
> /!\ breaking change incomming. In #2500 the `dependency` method become `addDependency`. I can add some method for migration phase if you want

Fixed here: https://github.com/jhipster/jhipster-lite/pull/2455/commits/c9da3d2055fe4df8b71e81b8654a5ef62736f531

2022-07-11 13:17 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +      .and()
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/619dcec72114e9fefcef227cf4fdb538bf2d2e71

2022-07-11 13:17 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +            """
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/619dcec72114e9fefcef227cf4fdb538bf2d2e71

2022-07-11 13:17 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +            """
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/619dcec72114e9fefcef227cf4fdb538bf2d2e71

2022-07-12 16:32 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +  public static final String STRING_SERIALIZER = "org.apache.kafka.common.serialization.StringSerializer";
Why public

2022-07-12 16:32 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/infrastructure/primary/rest/KafkaResourceConfiguration.java
> +public class KafkaResourceConfiguration {
Package private

2022-07-12 18:44 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +  public static final String STRING_DESERIALIZER = "org.apache.kafka.common.serialization.StringDeserializer";
Auto public with idea, I didn't check it. Will fix it!

2022-07-12 18:50 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +  public static final String STRING_DESERIALIZER = "org.apache.kafka.common.serialization.StringDeserializer";
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/8b953a481d7fa92eb50b9eb9dc51439bc360ea6b

2022-07-12 18:50 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/infrastructure/primary/rest/KafkaResourceConfiguration.java
> +public class KafkaResourceConfiguration {
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/8b953a481d7fa92eb50b9eb9dc51439bc360ea6b

2022-07-13 05:54 UTC, pascalgrimaud requested changes

2022-07-13 05:54 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +    return builder.build();
you can inline

2022-07-13 05:54 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +    return builder.build();
you can inline

2022-07-13 05:54 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +    return builder.build();
you can inline

2022-07-13 05:54 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactoryTest.java
> +    var dummyConsumerPath = "dummy/infrastructure/primary/kafka/consumer";
don't like too much the var here :D

2022-07-13 05:54 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactoryTest.java
> +      .and();
you could improve this part by doing something like:

```java
   .createFiles(
        MAIN_JAVA + "/" + properties.basePackage().path() + "/" + dummyProducerPath + "/DummyProducer.java",
        MAIN_JAVA + "/" + properties.basePackage().path() + "/" + dummyConsumerPath + "/AbstractConsumer.java",
        MAIN_JAVA + "/" + properties.basePackage().path() + "/" + dummyConsumerPath + "/DummyConsumer.java"
        )
      .createFiles(
        TEST_JAVA + "/" + properties.basePackage().path() + "/" + dummyProducerPath + "/DummyProducerTest.java",
        TEST_JAVA + "/" + properties.basePackage().path() + "/" + dummyProducerPath + "/DummyProducerIT.java",
        TEST_JAVA + "/" + properties.basePackage().path() + "/" + dummyConsumerPath + "/DummyConsumerTest.java",
        TEST_JAVA + "/" + properties.basePackage().path() + "/" + dummyConsumerPath + "/DummyConsumerIT.java"
      )
```

Then, you could extract to private method for building mainJava and testJava to have be more readable here

2022-07-13 07:53 UTC, fdelbrayelle commented on src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactoryTest.java
> +    var dummyConsumerPath = "dummy/infrastructure/primary/kafka/consumer";
Yep but it's an authorized keyword for better readability IMO here :)

2022-07-13 07:55 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +    return builder.build();
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/abebdac9053fe4ae09a24dc1a783c960e235e918

2022-07-13 07:55 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +    return builder.build();
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/abebdac9053fe4ae09a24dc1a783c960e235e918

2022-07-13 07:55 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactory.java
> +    return builder.build();
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/abebdac9053fe4ae09a24dc1a783c960e235e918

2022-07-13 07:56 UTC, fdelbrayelle commented on src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaModuleFactoryTest.java
> +      .and();
Fixed: https://github.com/jhipster/jhipster-lite/pull/2455/commits/abebdac9053fe4ae09a24dc1a783c960e235e918

2022-07-13 10:03 UTC, pascalgrimaud approved these changes

2022-07-13 10:03 UTC, merged