Frontend maven module
jhipster/jhipster-lite pull request #2491
Opened 2022-07-10 19:12 UTC by DamnClin

Close https://github.com/jhipster/jhipster-lite/issues/2473

2022-07-10 19:12 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
> +  private static final String NODE_VERSION = "v16.15.0";
hardcoded for now because I think the version update don't work on that

2022-07-10 19:12 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
> +  private static final String NPM_VERSION = "8.5.0";
hardcoded for now because I think the version update don't work on that

2022-07-11 06:21 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
> +  private static final String NODE_VERSION = "v16.15.0";
We could already use 16.16.0

2022-07-11 06:22 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactory.java
> +  private static final String NODE_VERSION = "v16.15.0";
I think what we really need is that https://github.com/jhipster/jhipster-lite/issues/2499

2022-07-11 06:23 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactoryTest.java
> +      .containing("    <node.version>v16.15.0</node.version>")
Do we need to update the test, each time we upgrade the node version?
Instead, I'd suggest to use the constant here

2022-07-11 06:23 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactoryTest.java
> +      .containing("    <npm.version>8.5.0</npm.version>")
Same comment for npm here, maybe use the constant

2022-07-11 06:24 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/generator/server/javatool/frontendmaven/domain/FrontendMavenModuleFactoryTest.java
> +      .containing("    <npm.version>8.5.0</npm.version>")
This a mistake in the test, I'll remove the version (just keep the key)

2022-07-11 06:24 UTC, pascalgrimaud requested changes
Few comments

2022-07-11 06:29 UTC, pascalgrimaud approved these changes

2022-07-11 06:55 UTC, merged