Dummy feature module
jhipster/jhipster-lite pull request #2546
Opened 2022-07-13 15:32 UTC by DamnClin

Close https://github.com/jhipster/jhipster-lite/issues/2444
Close https://github.com/jhipster/jhipster-lite/issues/2541

2022-07-13 16:42 UTC, DamnClin commented
In fact this also needs https://github.com/jhipster/jhipster-lite/issues/2351

So I'll integrate: 
* https://github.com/jhipster/jhipster-lite/issues/1800
* https://github.com/jhipster/jhipster-lite/issues/2001

But that means it is after https://github.com/jhipster/jhipster-lite/issues/2467 (so sad)

2022-07-14 08:44 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/domain/DummyFeatureModuleFactory.java
> +          .template("JsonHelper.java")
Remove

2022-07-15 07:05 UTC, DamnClin commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot/features/dummy"
Also add in OAuth2 app

2022-07-17 14:29 UTC, pascalgrimaud commented
Moving the bounty to the ticket

2022-07-19 14:46 UTC, DamnClin commented
cc @pascalgrimaud for me it's ok, status check is stuck because...reasons but I think this is all good

2022-07-19 14:48 UTC, pascalgrimaud commented
just be patient :)

2022-07-19 21:40 UTC, pascalgrimaud commented
I'll test this feature tomorrow

2022-07-20 05:19 UTC, pascalgrimaud requested changes

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/dummy.md
> +A brave beer retailler is handling his 3 shops with papers and pencils and he is starting to have some trouble scaling up. He asked us to a build a simple system where he'll be able to:
retailer instead?

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/dummy.md
> +Our brave team of 1 dev didn't build that on his own, in fact he was with the retailler (tasting the product) while doing the first version. As the goal was to show what can be done easily the persis
retailer?

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/dummy.md
> +Even this very simple product already helped the retailler (a lot)! So he came back to our team (with some beers!) to add a feature to manage orders. The team started something to allow orders taking
retailer?

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/dummy.md
> +We got answer from the retailler later on but our team is currently recovering from a very serious headache. Can you end what they started on order considering that:
retailer?

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/test/HttpSteps.java.mustache
> +
Remove this extra line

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/test/beers-catalog.feature
> +  Scenario: Add beer to catalog
Should add beer...

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/test/dummy/infrastructure/primary/beer/RestBeerTest.java.mustache
> +        {\
Not sure about my comment: is `\` needed here?

2022-07-20 05:19 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/test/dummy/infrastructure/primary/beer/RestBeerToCreateTest.java.mustache
> +class RestBeerToCreateTest {
Missing UnitTest

2022-07-20 06:04 UTC, DamnClin commented on src/main/resources/generator/server/springboot/mvc/dummy/test/dummy/infrastructure/primary/beer/RestBeerTest.java.mustache
> +        {\
yep, without them we have line break and test fails

2022-07-20 06:41 UTC, pascalgrimaud approved these changes

2022-07-20 07:16 UTC, merged

2022-07-20 07:25 UTC, DamnClin commented
Claimed https://opencollective.com/generator-jhipster/expenses/87078

2022-07-20 07:30 UTC, pascalgrimaud commented
@DamnClin : approved