React jwt module
jhipster/jhipster-lite pull request #2594
Opened 2022-07-14 20:08 UTC by DamnClin

Close https://github.com/jhipster/jhipster-lite/issues/2531

The current version don't work on not styled react, hopefully this will fix that

2022-07-14 20:17 UTC, DamnClin commented
Needs https://github.com/jhipster/jhipster-lite/pull/2587 for line break fix on windows

2022-07-15 18:12 UTC, DamnClin commented
Even if we decide to disable JWT I think this should be merged (and disabled latter on)

2022-07-17 14:14 UTC, pascalgrimaud requested changes

2022-07-17 14:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/domain/GeneratorAction.java
> +  public static final String GITHUB_ACTIONS = "github-actions";
No need this, as github actions has been migrated

2022-07-17 16:32 UTC, pascalgrimaud commented
can you resolve the conflict plz @DamnClin ?

2022-07-17 17:38 UTC, pascalgrimaud approved these changes

2022-07-17 17:38 UTC, merged