Add sonar documentation
jhipster/jhipster-lite pull request #2639
Opened 2022-07-17 15:40 UTC by antarus

close https://github.com/jhipster/jhipster-lite/issues/2543

2022-07-17 15:43 UTC, pascalgrimaud requested changes

2022-07-17 15:43 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/domain/SonarModulesFactory.java
> +      .documentation(documentationTitle("sonar"), SOURCE.template("sonar.md"))
you could add this file to unit test, to be sure it's generated

2022-07-17 15:44 UTC, antarus commented on src/main/java/tech/jhipster/lite/generator/server/sonar/domain/SonarModulesFactory.java
> +      .documentation(documentationTitle("sonar"), SOURCE.template("sonar.md"))
yes

2022-07-17 15:52 UTC, pascalgrimaud approved these changes

2022-07-17 15:52 UTC, antarus commented
@pascalgrimaud test add

2022-07-17 16:14 UTC, DamnClin commented
I think we should add short readmesection for the docker image (I made a test in the mongo DB module)

2022-07-17 16:30 UTC, antarus commented
ok I'll look it up

2022-07-17 16:39 UTC, antarus commented
@DamnClin 
Isn't it a little redundant to have the documentation and after the docker-compose to launch?

maybe add a specific needle to the docker to start?

2022-07-17 16:40 UTC, DamnClin commented
I don't know, most of the time I have many docker to start (and I make a makefile but that's not the subject...), I'dd like to have all the command in the frontpage

2022-07-17 16:43 UTC, antarus commented
I agree with you, I regularly make a script to start everything but if you want to put all the useful commands at launch, they would be better under `npm install` in the readme, wouldn't they?

2022-07-17 16:44 UTC, DamnClin commented
Totally, good idea

2022-07-17 16:52 UTC, antarus commented
which name would be the most appropriate for this needle ? i can do a MR

2022-07-17 16:56 UTC, DamnClin commented
<!-- jhipster-needle-run-commands --> sounds good. I think we should also add a shortcut in JHipsterModule where you give the command and it's doing the other part (formatting, replacement, etc)

2022-07-17 17:35 UTC, merged

2022-07-18 07:09 UTC, pascalgrimaud commented
> I don't know, most of the time I have many docker to start (and I make a makefile but that's not the subject...), I'dd like to have all the command in the frontpage

For your information, in generator-jhipster: there are some npm commands to start all docker-compose services. See https://github.com/jhipster/jhipster-sample-app/blob/main/package.json#L32-L38

Some users said me they don't like this, as it looks strange to have these kinds of commands inside `package.json`
So here some suggestions, in JHipster Lite:
- a module which add to `package.json` these kind of commands, using docker-compose
- a module which will init a makefile and add the different commands

If you think it's a good idea, we can open a ticket for that