Multiple git repository depending on environment
jhipster/jhipster-lite pull request #2700
Opened 2022-07-19 19:11 UTC by DamnClin

Close https://github.com/jhipster/jhipster-lite/issues/2549

2022-07-19 21:38 UTC, pascalgrimaud requested changes

2022-07-19 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/init/infrastructure/secondary/GitChecker.java
> +@Generated(reason = "Higly dependant of execution environment")
Typo: Highly

2022-07-19 21:39 UTC, pascalgrimaud commented
About disabled tests, don't you think we can let them? For users who launch unit tests on this project, they probably cloned it, using git, so for sure, they have git :-D

2022-07-20 06:00 UTC, DamnClin commented
> About disabled tests, don't you think we can let them? For users who launch unit tests on this project, they probably cloned it, using git, so for sure, they have git :-D

Didn't know if you have it on all CI machines...

2022-07-20 06:40 UTC, pascalgrimaud approved these changes

2022-07-20 06:51 UTC, merged