Add style from tikui
jhipster/jhipster-lite pull request #3042
Opened 2022-08-12 12:55 UTC by Gnuk

2022-08-12 12:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=3042) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=3042) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=3042) it.</sub>

2022-08-29 11:34 UTC, pascalgrimaud requested changes

2022-08-29 11:34 UTC, pascalgrimaud commented on package.json
> +    "@tikui/core": "^2.1.0",
always use fixed version plz

2022-08-29 11:34 UTC, pascalgrimaud commented on package.json
> +    "tikuidoc-tikui": "^4.0.0",
same, use fixed version

2022-08-29 11:34 UTC, pascalgrimaud commented on pom.xml
> +    <node.version>v16.16.0</node.version>
the last version is 16.17.0, maybe the rebase will solve it

2022-08-29 11:34 UTC, pascalgrimaud commented on .github/actions/setup/action.yml
> +        node-version: 16.16.0
last version should be 16.17.0

2022-08-29 12:23 UTC, pascalgrimaud approved these changes

2022-08-29 12:24 UTC, hdurix commented
I've got an error when I'm trying to build the app, for instance with `./mvnw`:

```
[INFO] Building on /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style directory.
[INFO] [0] node:internal/modules/cjs/loader:959
[INFO] [0]   throw err;
[INFO] [0]   ^
[INFO] [0] 
[INFO] [0] Error: Cannot find module '/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/node/bin/node_modules/npm/bin/npm-cli.js'
[INFO] [0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
[INFO] [0]     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
[INFO] [0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[INFO] [0]     at node:internal/main/run_main_module:17:47 {
[INFO] [0]   code: 'MODULE_NOT_FOUND',
[INFO] [0]   requireStack: []
[INFO] [0] }
[INFO] [0] node:internal/modules/cjs/loader:959
[INFO] [0]   throw err;
[INFO] [0]   ^
[INFO] [0] 
[INFO] [0] Error: Cannot find module '/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/node/bin/node_modules/npm/bin/npx-cli.js'
[INFO] [0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
[INFO] [0]     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
[INFO] [0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[INFO] [0]     at node:internal/main/run_main_module:17:47 {
[INFO] [0]   code: 'MODULE_NOT_FOUND',
[INFO] [0]   requireStack: []
[INFO] [0] }
[INFO] [0] npx sass "/home/hippolyte/workspace/jhipster/jhipster-lite/src/main/style":"/home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style" -s compressed --source-map --embed-sources exited with code 1
[INFO] [1] /home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/tikuidoc-tikui/src/documentation/style.scss => /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style/documentation/style.css using SCSS
[INFO] [1] /home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/prismjs/prism.js => /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style/lib/prismjs/prism.js

...

[INFO] [1] /home/hippolyte/workspace/jhipster/jhipster-lite/src/main/style/template/template.pug => /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style/template/template.html using Pug
[INFO] [1] node "/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/@tikui/core/dist/assets-build.js" && node "/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/@tikui/core/dist/pug-build.js" exited with code 0
[INFO] Build failed, first error code found: 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

any idea why?

2022-08-29 12:25 UTC, pascalgrimaud commented
@hdurix : need to clean node/ folder as suggested by @Gnuk , but I don't understand why

2022-08-29 12:26 UTC, Gnuk commented
> I've got an error when I'm trying to build the app, for instance with `./mvnw`:
> 
> ```
> [INFO] Building on /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style directory.
> [INFO] [0] node:internal/modules/cjs/loader:959
> [INFO] [0]   throw err;
> [INFO] [0]   ^
> [INFO] [0] 
> [INFO] [0] Error: Cannot find module '/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/node/bin/node_modules/npm/bin/npm-cli.js'
> [INFO] [0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
> [INFO] [0]     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
> [INFO] [0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> [INFO] [0]     at node:internal/main/run_main_module:17:47 {
> [INFO] [0]   code: 'MODULE_NOT_FOUND',
> [INFO] [0]   requireStack: []
> [INFO] [0] }
> [INFO] [0] node:internal/modules/cjs/loader:959
> [INFO] [0]   throw err;
> [INFO] [0]   ^
> [INFO] [0] 
> [INFO] [0] Error: Cannot find module '/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/node/bin/node_modules/npm/bin/npx-cli.js'
> [INFO] [0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
> [INFO] [0]     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
> [INFO] [0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> [INFO] [0]     at node:internal/main/run_main_module:17:47 {
> [INFO] [0]   code: 'MODULE_NOT_FOUND',
> [INFO] [0]   requireStack: []
> [INFO] [0] }
> [INFO] [0] npx sass "/home/hippolyte/workspace/jhipster/jhipster-lite/src/main/style":"/home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style" -s compressed --source-map --embed-sources exited with code 1
> [INFO] [1] /home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/tikuidoc-tikui/src/documentation/style.scss => /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style/documentation/style.css using SCSS
> [INFO] [1] /home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/prismjs/prism.js => /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style/lib/prismjs/prism.js
> 
> ...
> 
> [INFO] [1] /home/hippolyte/workspace/jhipster/jhipster-lite/src/main/style/template/template.pug => /home/hippolyte/workspace/jhipster/jhipster-lite/target/classes/public/style/template/template.html using Pug
> [INFO] [1] node "/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/@tikui/core/dist/assets-build.js" && node "/home/hippolyte/workspace/jhipster/jhipster-lite/node_modules/@tikui/core/dist/pug-build.js" exited with code 0
> [INFO] Build failed, first error code found: 1
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> ```
> 
> any idea why?

Yes, `node` directory seems not be removed with `clean`, maybe remove it manually then launch `./mvnw`

2022-08-29 12:32 UTC, hdurix commented
better now, thanks. This may be the case for every contributors once we merge this one.

2022-08-29 12:34 UTC, merged

2022-08-29 12:51 UTC, Gnuk commented
> better now, thanks. This may be the case for every contributors once we merge this one.

Yes, may we need to link this PR to the contributors during this phase.

2022-09-02 15:32 UTC, pascalgrimaud commented
Adding a bounty on this nice PR.
Plz claim it @Gnuk

2022-09-02 15:50 UTC, Gnuk commented
Claimed https://opencollective.com/generator-jhipster/expenses/92758

2022-09-02 15:51 UTC, pascalgrimaud commented
@Gnuk : approved