Fix windows breaking paths
jhipster/jhipster-lite pull request #317
Opened 2021-12-11 18:21 UTC by swarajsaaj

Getting the generator run in windows:-
1. Using "/" as file separator for windows to avoid conflicts with
mustache.
2. Avoid Posix file executable for non-posix systems

Note:- If using "\\" (File.separator on windows) its not possible to generate the project at all, so replacing it with more universal "/" 
Exception in mustache when using "\" as file separator from
```

java.lang.IllegalArgumentException: Illegal character in path at index 9: generator\init\README.md.mustache
	at java.base/java.net.URI.create(URI.java:906) ~[na:na]
	at com.github.mustachejava.resolver.ClasspathResolver.getReader(ClasspathResolver.java:37) ~[compiler-0.9.10.jar:na]
	at com.github.mustachejava.resolver.DefaultResolver.getReader(DefaultResolver.java:48) ~[compiler-0.9.10.jar:na]
	at com.github.mustachejava.DefaultMustacheFactory.getReader(DefaultMustacheFactory.java:118) ~[compiler-0.9.10.jar:na]
	at com.github.mustachejava.MustacheParser.compile(MustacheParser.java:33) ~[compiler-0.9.10.jar:na]
```

2021-12-11 20:52 UTC, pascalgrimaud commented
Thanks a lot @swarajsaaj 
I didn't find the solution to test with Windows, so your help is welcome here

2021-12-11 20:57 UTC, jdubois commented
As some of this code is very close to NubesGen.com you probably have the same errors I had there on Windows. It’s fixed in NubesGen, we should share code on this.

2021-12-12 16:00 UTC, pascalgrimaud requested changes

2021-12-12 18:01 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +  private final boolean isPosix = FileSystems.getDefault().supportedFileAttributeViews().contains("posix");
Hi @pascalgrimaud ,
Thanks for the review, I have moved the check to  `FileUtils`, and for the test case I have attempted writing a non-windows test case with mocked static method, let me know if it can be improved? :)

2021-12-12 18:11 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +  private final boolean isPosix = FileSystems.getDefault().supportedFileAttributeViews().contains("posix");
Yes the solution is to use mocked static :-)

2021-12-12 18:59 UTC, pascalgrimaud requested changes

2021-12-12 18:59 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +    System.out.println(getPath(project.getFolder()));
just remove this system out and we should be good :)

2021-12-12 19:02 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/project/infrastructure/secondary/ProjectLocalRepository.java
> +    System.out.println(getPath(project.getFolder()));
Oops.
Removed it

2021-12-12 19:05 UTC, pascalgrimaud approved these changes

2021-12-12 19:15 UTC, merged

2021-12-12 19:15 UTC, pascalgrimaud commented
Thanks for your contributions @swarajsaaj 
And congrats for keeping the coverage ;)

2021-12-12 19:20 UTC, swarajsaaj commented
> Thanks for your contributions @swarajsaaj And congrats for keeping the coverage ;)

Thanks for all the help @pascalgrimaud 👍