Add MySQL
jhipster/jhipster-lite pull request #320
Opened 2021-12-13 20:16 UTC by swarajsaaj

Add support for MySQL database

Fix #231

I have replicated the postgresql style here without extracting common functionalities to avoid making a complicated if-else ladder in future.

2021-12-14 05:43 UTC, pascalgrimaud commented
Wow, thanks @swarajsaaj !
I'll review it soon

2021-12-14 12:30 UTC, pascalgrimaud requested changes

2021-12-14 12:30 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +    result.put("spring.datasource.driver-class-name", "com.mysql.jdbc.Driver");
I don't think we need this

2021-12-14 12:30 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +    result.put("spring.jpa.properties.hibernate.dialect", "org.hibernate.dialect.MySQL8Dialect");
same, I don't think we need this. What I can suggest, is to generate a JHipster project with MySQL and check all properties in application-prod.yml

2021-12-14 12:30 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQL.java
> +
just an idea, maybe we can add: DOCKER_MYSQL_VERSION = "mysql:8.0.27"

2021-12-14 12:30 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +    result.put("spring.datasource.url", "jdbc:tc:mysql:8.0.27:///" + baseName);
we could use MySQL.getDockerMysqlVersion(), following my comment above

2021-12-14 12:30 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/mysql/mysql.yml.mustache
> +    image: mysql:8.0.27
we could use {{dockerMysqlVersion}}, injected by DOCKER_MYSQL_VERSION value

2021-12-14 12:30 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +    project.addDefaultConfig(BASE_NAME);
we could add something like:

project.addConfig("dockerMysqlVersion", MySQL.getDockerMysqlVersion());

2021-12-14 12:30 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQL.java
> +  }
with new method getDockerMysqlVersion()

2021-12-14 12:30 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/mysql/application/MySQLApplicationServiceIT.java
> +      List.of("spring.datasource.url=jdbc:tc:mysql:8.0.27:///chips", "spring.datasource.username=chips")
use MySQL.getDockerMysqlVersion()

2021-12-14 14:46 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQL.java
> +
yes sure, I think constant name could be DOCKER_IMAGE_NAME instead?

2021-12-14 15:12 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +    result.put("spring.jpa.properties.hibernate.dialect", "org.hibernate.dialect.MySQL8Dialect");
agreed, these properties are not needed. Removed

2021-12-14 15:12 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +    result.put("spring.datasource.driver-class-name", "com.mysql.jdbc.Driver");
agreed, these properties are not needed. Removed

2021-12-14 17:41 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQL.java
> +
yes it's ok :)

2021-12-14 17:43 UTC, pascalgrimaud commented
By reviewing this PR, I need to improve the code in PostgreSQL too :)

2021-12-14 17:43 UTC, pascalgrimaud approved these changes

2021-12-14 17:50 UTC, merged

2021-12-14 17:50 UTC, pascalgrimaud commented
Don't forget to claim your bounty @swarajsaaj 
Well deserved

2021-12-18 16:23 UTC, swarajsaaj commented
I claim the bounty :) https://opencollective.com/generator-jhipster/expenses/58753

2021-12-18 16:26 UTC, pascalgrimaud commented
@swarajsaaj : approved!