Feature/add logback
jhipster/jhipster-lite pull request #329
Opened 2021-12-16 19:18 UTC by swarajsaaj

This PR adds the shared-context for Logging configuration (with needle approach)

Added by default in Spring core

Logger configurations added for:-
- Spring MVC (Tomcat + Undertow)
- MySQL
- PostgreSQL
- Liquibase

Fix #209

2021-12-16 20:16 UTC, pascalgrimaud commented
Thanks @swarajsaaj ! huge work.

My advices for next PRs:
- try to work by context, instead of several contexts at the same time
- it will ease your work, and this architecture allows to work like this
- it's better to have smaller PR, instead of big PR like we can have in generator-jhipster

For this use case, it could be done in several PRs:
- add logback in Spring Boot (1st PR)
- add logging context in another PR
- call logging in PostgreSQL (another PR)
- call logging in MySQL (another PR)
- etc...

2021-12-16 20:58 UTC, pascalgrimaud requested changes

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java
> +  public static final String NEEDLE_LOGBACK_LOGGER = "<!-- jhipster-needle-logback-add-logger -->";
I would use the same one than in generator-jhipster: `jhipster-needle-logback-add-log`

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java
> +  public static final String LOGGING_TEST_CONFIGURATION = "logback-test.xml";
could it be renamed to logback.xml ? Like in generator-jhipster ? I think it's possible

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +import ch.qos.logback.classic.Level;
should be removed, as we are in Domain, so we should not use external lib -> use our own enum LoggingLevel or Level, in logging context

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLService.java
> +import ch.qos.logback.classic.Level;
not used, so should be removed

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/postgresql/domain/PostgresqlDomainService.java
> +import ch.qos.logback.classic.Level;
same comment, should be removed and replace by our own custom Level in logging context

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseDomainService.java
> +import ch.qos.logback.classic.Level;
same comment, should be removed and replace by our own custom Level in logging context

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logging/domain/SpringBootLoggingDomainService.java
> +import ch.qos.logback.classic.Level;
maybe instead of using this, just create an enum in this context: LoggingLevel or simply Level (which is different from the one in logback)

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logging/domain/SpringBootLoggingService.java
> +import ch.qos.logback.classic.Level;
same comment, should be removed and replace by our own custom Level in logging context

2021-12-16 20:58 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/HexagonalArchTest.java
> +    "ch.qos.logback.."
following my previous comment, should be removed, as it is too specific here

Then, I'll remove slf4j and common.lang3 in another PR :)

The domain should only use java, nothing else

2021-12-16 20:58 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/core/application/SpringBootApplicationServiceIT.java
> +    assertFileExist(project, getPath(MAIN_RESOURCES, "logback-spring.xml"));
should add this in `shouldInit` test too

2021-12-16 20:58 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/core/application/SpringBootApplicationServiceIT.java
> +    assertFileExist(project, getPath(TEST_RESOURCES, "logback-test.xml"));
should add this in `shouldInit` test too

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logging/application/SpringBootLoggingApplicationService.java
> +import ch.qos.logback.classic.Level;
same comment, should be removed and replace by our own custom Level in logging context

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcDomainService.java
> +import ch.qos.logback.classic.Level;
same comment, should be removed and replace by our own custom Level in logging context

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/core/logback-spring.xml.mustache
> +      </root>
wonder if we can format this part to use 2 spaces for indentation?

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/core/logback-test.xml.mustache
> +      </root>
wonder if we can format this part to use 2 spaces for indentation?

2021-12-16 20:58 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/core/logback-test.xml.mustache
> +  <logger name="com.tngtech.archunit.core.importer" level="ERROR"/>
should not be added here

2021-12-17 02:36 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java
> +  public static final String NEEDLE_LOGBACK_LOGGER = "<!-- jhipster-needle-logback-add-logger -->";
Is this to keep it similar to generator-jhipster for future compatibility?

2021-12-17 02:37 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java
> +  public static final String LOGGING_TEST_CONFIGURATION = "logback-test.xml";
Yes its possible, Ideally logback-test.xml takes precedence over logback.xml in tests but both would work
Is this to keep it similar to generator-jhipster for future compatibility?

2021-12-17 06:04 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java
> +  public static final String NEEDLE_LOGBACK_LOGGER = "<!-- jhipster-needle-logback-add-logger -->";
Yes, at least we can try. Imagine a feature in JHipster Lite which can be used in existing project, generated with generator-jhipster :-)

2021-12-17 06:04 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java
> +  public static final String LOGGING_TEST_CONFIGURATION = "logback-test.xml";
Yes exactly

2021-12-17 15:03 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBoot.java
> +  public static final String NEEDLE_LOGBACK_LOGGER = "<!-- jhipster-needle-logback-add-logger -->";
Done.

2021-12-17 15:05 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mysql/domain/MySQLDomainService.java
> +import ch.qos.logback.classic.Level;
Changed to a custom enum

2021-12-17 15:05 UTC, swarajsaaj commented on src/main/resources/generator/server/springboot/core/logback-spring.xml.mustache
> +      </root>
Fixed in the commented portion

2021-12-17 15:06 UTC, swarajsaaj commented on src/main/resources/generator/server/springboot/core/logback-test.xml.mustache
> +  <logger name="com.tngtech.archunit.core.importer" level="ERROR"/>
removed.

2021-12-17 15:28 UTC, pascalgrimaud requested changes

2021-12-17 15:28 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/core/logback.xml.mustache
> +  <logger name="org.testcontainers" level="WARN"/>
you forgot to remove this by default

2021-12-17 16:08 UTC, swarajsaaj commented on src/main/resources/generator/server/springboot/core/logback.xml.mustache
> +  <logger name="org.testcontainers" level="WARN"/>
Ah!. I missed these ones.. moved them to database contexts

2021-12-17 18:29 UTC, pascalgrimaud approved these changes

2021-12-17 18:29 UTC, pascalgrimaud commented
You're awesome @swarajsaaj !

2021-12-17 18:29 UTC, merged

2021-12-18 16:25 UTC, swarajsaaj commented
I claim the bounty at https://opencollective.com/generator-jhipster/expenses/58755 :)

2021-12-18 16:27 UTC, pascalgrimaud commented
@swarajsaaj : approved!