Actuator: Add Actuator
jhipster/jhipster-lite pull request #345
Opened 2021-12-18 20:28 UTC by swarajsaaj

Add actuator and relevant properties

Did not add metrics/Prometheus (I think it should be part of dedicated PR), maybe allow multiple exports (datadog, Prometheus etc.) .

Fix #198

2021-12-18 21:00 UTC, pascalgrimaud commented
Thanks! I'll review it tomorrow

2021-12-19 07:00 UTC, pascalgrimaud requested changes

2021-12-19 07:01 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/infrastructure/primary/rest/SpringBootMvcResource.java
> +  @ApiResponses({ @ApiResponse(responseCode = "500", description = "An error occurred while adding Spring Boot Actuator") })
I applied some changes about this in main branch (related to Sonar analysis), that's the reason :)

2021-12-19 07:36 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/infrastructure/primary/rest/SpringBootMvcResource.java
> +  @ApiResponses({ @ApiResponse(responseCode = "500", description = "An error occurred while adding Spring Boot Actuator") })
Thanks @pascalgrimaud , I have committed the change.

2021-12-19 07:36 UTC, pascalgrimaud approved these changes

2021-12-19 07:39 UTC, merged