Redefining ArchUnit tests
jhipster/jhipster-lite pull request #3552
Opened 2022-09-14 16:50 UTC by onepunchmagne

Relates [#2921](https://github.com/jhipster/jhipster-lite/issues/2921)

* Shared kernels cannot depend on bounded contexts
* Bounded context can calls each others only using secondary to primary Java adapters communications
* Domain cannot use anything but its self-domain, Java vanilla features or some common utils libraries
* Application cannot call infrastructure
* Primary cannot directly call secondary
* Secondary cannot call any application service

2022-09-14 16:54 UTC, pascalgrimaud commented
Does it fix #2921 @onepunchmagne ?

2022-09-14 16:55 UTC, onepunchmagne commented
Work left:
* a bug fixed in ArchUnit 1.0.0-rc1 seems to be still an issue for check primary Java adapters are called only by secondaries to fix #2921
* @DamnClin @pascalgrimaud I have a problem understanding why `module` is a shared kernel and `project` a bounded context -> we have an architecture issue on `FileSystemJHipsterModulesRepository` calling `JavaProjects`

2022-09-14 16:59 UTC, DamnClin commented
> I have a problem understanding why module is a shared kernel and project a bounded context

Not sure to understand the question so I can only answer by saying that module is a shared kernel and project is a business context (I don't think we have a bounded context annotation as this would be really wrong and missleading !)

> we have an architecture issue on FileSystemJHipsterModulesRepository calling JavaProjects

This is not a bug, JavaProject is a primary adapter, it's totally normal

2022-09-14 19:43 UTC, onepunchmagne commented
> I don't think we have a bounded context annotation as this would be really wrong and missleading !

Here is the thing that should be discussed, the annotation is called `@BusinessContext` but the tests say otherwise, here is the behavior implemented in the existing tests: `"Shared kernels should not have dependencies to bounded contexts"`  
Moreover in the `hexagonal-architecture.md` we explain in the same paragraph:  

> So, first things first: **an application is made of multiple "hexagons"**, one for each [Bounded Context](https://martinfowler.com/bliki/BoundedContext.html). (Yes, sometimes you can have only one but this is an exception). We usually have each Bounded Context as root packages in the application.
> - `my_business_context`: root package for the context (naming depends on your technology naming conventions)  

I think @pascalgrimaud and @hdurix aggried that JHLite generates `bounded contexts` from DDD, but this is very confusing in JHLite code itself. As a user of JHLite our project team also understood that `@BusinessContext` annotation was from "bounded context" (without understanding why it was not named exactly after the DDD strategic patterns). Also the other annotation coming in pair is the `@SharedKernel` so it made perfectly sense for JHLite **users** (not contributors). But for contributors point of view, it is indeed misleading, I can't understand our `package-info.java` descriptors.

If I may, I would suggest we rename to `@BoundedContext` explicitely to stick to a well-documented notion that would wear a conviction along with `@SharedKernel`. But that we remove/redefine the existing `package-info.java` that seems to randomly wear the annotations. (ticket is here https://github.com/jhipster/jhipster-lite/issues/3540)

2022-09-15 15:26 UTC, DamnClin commented
Ok, if I'm the only one finding that misleading let's rename it

2022-09-23 07:20 UTC, DamnClin requested changes

2022-09-23 07:20 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/project/package-info.java
> +@tech.jhipster.lite.SharedKernel
Project is not a shared kernel, I don't understand this change

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +  private static final Collection<String> businessContexts = getPackageAnnotatedBy(BusinessContext.class);
getPackageAnnotatedBy -> packagesWithAnnotation ?

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +  private static final Collection<String> businessContextsPackages = toPackages(businessContexts);
toPackages -> buildPackagesPatterns?

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +  private static final Collection<String> vanillaPackages = Arrays.asList("java..", "");
Arrays.asList -> List.of (not allowing null values)

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +  private static final Collection<String> commonToolsAndUtilsPackages = Arrays.asList(
Arrays.asList -> List.of

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +          .because("Contexts can only depend on classes in the same context or in common")
or in common -> or in shared kernels?

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +    void shouldBeAnOnionArchitecture() {
Hum no, this is an hexagonal architecture test, not an onion architecture test

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +          .because("Each bounded context should implement an onion architecture")
Totally disagree with that. We should make a dedicated module if we want to enforce onion architecture

2022-09-23 07:20 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +        .resideInAPackage(".domain..")
I don't get it, here we are allowing domain to depend on any domain no? No more check for domain dependencies to other domains?

2022-09-23 11:54 UTC, DamnClin commented
This can give some god hints: https://github.com/whiskeysierra/archunit-hexagonal/blob/trunk/src/main/kotlin/io/github/whiskeysierra/archunit/hexagonal/HexagonalArchitecture.kt

2022-09-23 12:22 UTC, onepunchmagne commented
> This can give some god hints: https://github.com/whiskeysierra/archunit-hexagonal/blob/trunk/src/main/kotlin/io/github/whiskeysierra/archunit/hexagonal/HexagonalArchitecture.kt

Thanks for the correction you're right, I used the hint trying to define some basics rules, I get that it's hard to define "the" hexagonal architecture test but it should probably serve as a good base for people to update according to their definition.

2022-09-23 12:25 UTC, onepunchmagne commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +        .resideInAPackage(".domain..")
Yes but there were a lot of overlaying tests so I tried defining different separate responsibility tests such as:  
* `BoundedContexts.shouldNotDependOnOtherBoundedContextDomains` which will verify our hexagons co-existence and boundaries
* `Domain.shouldNotDependOnOutside` which does not even know it co-exists with other hexagons, it simply check its dependencies to "outside" of a domain package

2022-09-23 12:31 UTC, onepunchmagne commented on src/main/java/tech/jhipster/lite/project/package-info.java
> +@tech.jhipster.lite.SharedKernel
If possible I'd like to take also this job but in issue https://github.com/jhipster/jhipster-lite/issues/3540  
because sticking to the architecture tests, we have a failure because `project` is called directly by `module` which is tagged as a shared kernel.

To be honest I have absolutely no clue currently of which package is a shared kernel and which is a "business" context, but there is something to do in this separate issue I think to realign the dependencies.

2022-09-23 13:53 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/project/package-info.java
> +@tech.jhipster.lite.SharedKernel
This is a mistake :D project is a business context and module is a SharedKernel, what is the link?

2022-09-23 16:21 UTC, onepunchmagne commented on src/main/java/tech/jhipster/lite/project/package-info.java
> +@tech.jhipster.lite.SharedKernel
Ok, so the whole thing about `SharedKernels.shouldNotDependOnBoundedContexts` is wrong I suppose, I delete it. A shared kernel can actually call bounded contexts following the same rule as passing through its secondary adapter to call the bounded context primary adapter, is that right?

Thus the `shouldBeAnHexagonalArchitecture` test should also be applied to shared kernel in the exact same way. Please check new change where I applied this logic

2022-09-27 08:43 UTC, DamnClin submitted a review, later dismissed

2022-09-27 08:43 UTC, DamnClin commented on src/main/resources/generator/server/javatool/arch/HexagonalArchTest.java.mustache
> +import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
Can you change your imports to import * starting at first static import?

2022-09-27 18:35 UTC, merged

2022-12-18 17:31 UTC, onepunchmagne commented
Claimed https://opencollective.com/generator-jhipster/expenses/114216

2022-12-18 18:00 UTC, DanielFran commented
@onepunchmagne approved