Maven: Add configuration plugin/pluginManagement
jhipster/jhipster-lite pull request #361
Opened 2021-12-20 19:25 UTC by swarajsaaj

Pre-requisite for #284

2021-12-20 20:55 UTC, pascalgrimaud requested changes

2021-12-20 20:55 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +  public static final String PLUGIN_MANAGEMENT_BEGIN = "<pluginManagement>";
maybe missing PLUGIN_MANAGEMENT_END ?

2021-12-20 20:55 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +    String expected = "<plugin>" + System.lineSeparator() +
maybe use text block ?

2021-12-20 20:55 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +      <executions>
maybe try to respect indent with 2 spaces?

2021-12-20 20:56 UTC, pascalgrimaud commented
another missing: you need to add the method in buildToolDomainService too

2021-12-21 05:08 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +  public static final String PLUGIN_MANAGEMENT_BEGIN = "<pluginManagement>";
Was initially not needed, as kept the regex between `<pluginManagement>` and `!-- jhipster-needle-maven-add-plugin-management -->`, but refactored in new commit it to end with `</pluginManagement>`

2021-12-21 05:09 UTC, swarajsaaj commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +    String expected = "<plugin>" + System.lineSeparator() +
Done. Still we need to add a `replaceAll("\n", System.lineSeparator())` to keep it OS friendly as Line endings in text blocks are always \n

2021-12-21 05:14 UTC, swarajsaaj commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +      <executions>
Did you suggest to indent the text block?

2021-12-21 05:19 UTC, swarajsaaj commented
> another missing: you need to add the method in buildToolDomainService too

Thanks for pointing it out, added it.

2021-12-21 06:42 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +        result.append(plugin.getAdditionalElements().get().indent(4 * indentation).replaceAll("\n", System.lineSeparator()))
What happened if the initial text already contains \r\n? Will it become \r\r\n?

2021-12-21 06:48 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +            </plugin>""".replaceAll("\n", System.lineSeparator());
Same comment about existing \r\n which could become \r\r\n

2021-12-21 07:02 UTC, pascalgrimaud requested changes

2021-12-21 07:02 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +                  </webResources>
```suggestion
              <configuration>
                <warSourceIncludes>WEB-INF/**,META-INF/**</warSourceIncludes>
                <failOnMissingWebXml>false</failOnMissingWebXml>
                <warSourceDirectory>target/classes/static/</warSourceDirectory>
                <webResources>
                  <resource>
                    <directory>src/main/webapp</directory>
                    <includes>
                      <include>WEB-INF/**</include>
                    </includes>
                  </resource>
                </webResources>
              </configuration>
```

2021-12-21 07:02 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +              <phase>package</phase>
```suggestion
            <id>default-war</id>
            <goals>
              <goal>war</goal>
            </goals>
            <phase>package</phase>
```

2021-12-21 07:02 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java
> +            </webResources>"""
```suggestion
          <warSourceIncludes>WEB-INF/**,META-INF/**</warSourceIncludes>
          <failOnMissingWebXml>false</failOnMissingWebXml>
          <warSourceDirectory>target/classes/static/</warSourceDirectory>
          <webResources>
            <resource>
              <directory>src/main/webapp</directory>
              <includes>
                <include>WEB-INF/**</include>
              </includes>
            </resource>
          </webResources>
        </configuration>"""
```

2021-12-21 07:04 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +        result.append(plugin.getAdditionalElements().get().indent(4 * indentation).replaceAll("\n", System.lineSeparator()))
So if I understand well, text block with windows always use \n as Line separator ?

2021-12-21 07:13 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +        result.append(plugin.getAdditionalElements().get().indent(4 * indentation).replaceAll("\n", System.lineSeparator()))
Not just in windows, as per https://docs.oracle.com/en/java/javase/15/text-blocks/index.html#normalization-of-line-terminators , any line endings will become \n in a text block

2021-12-21 07:34 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +        result.append(plugin.getAdditionalElements().get().indent(4 * indentation).replaceAll("\n", System.lineSeparator()))
This would help to generate the code as per user's system line endings (in case jhipster-lite is generating on user's local)

2021-12-21 07:41 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +        result.append(plugin.getAdditionalElements().get().indent(4 * indentation).replaceAll("\n", System.lineSeparator()))
ok thanks for explaination :)
Just to know, which OS do you use ?

I'm using Linux Ubuntu so it's hard for me to test Windows

2021-12-21 07:42 UTC, pascalgrimaud approved these changes

2021-12-21 07:42 UTC, merged

2021-12-21 07:45 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +        result.append(plugin.getAdditionalElements().get().indent(4 * indentation).replaceAll("\n", System.lineSeparator()))
I am using Windows 10 as of now :)

2021-12-21 07:51 UTC, swarajsaaj commented
Thanks for the review and merge :)

2021-12-21 07:52 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/Maven.java
> +        result.append(plugin.getAdditionalElements().get().indent(4 * indentation).replaceAll("\n", System.lineSeparator()))
perfect! so I'm totally trusting you for Windows part!

2021-12-21 08:11 UTC, pascalgrimaud commented
Big thanks to you, for helping this project!