Aop logging
jhipster/jhipster-lite pull request #379
Opened 2021-12-21 16:26 UTC by MSaguer

To close #274 

Aop logging activation is based on spring.aop/logging property

2021-12-21 16:29 UTC, MSaguer commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspect.java.mustache
> +        " || within({{packageName}}..*.repository..*)"
Are these pointcuts definition OK with the design. Not sure for the repository line.

2021-12-21 16:34 UTC, MSaguer commented on src/test/java/tech/jhipster/lite/generator/server/springboot/aop/logging/application/AopLoggingApplicationServiceIT.java
> +    Project project = tmpProject();
Not sure about this test because its has the same content than the following add tests. Seems to be partially redondant.

2021-12-21 16:59 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspect.java.mustache
> +        " || within({{packageName}}..*.repository..*)"
Hmmmm, I think the package to validate are:
- packageName.*.primary.*
- packageName.*.application.*
- packageName.*.infrastructure.*

2021-12-21 17:02 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/aop/logging/application/AopLoggingApplicationServiceIT.java
> +    Project project = tmpProject();
yes agree, I have the same feeling, while working in TDD:
- adding tests in XxxApplicationServiceIT
- coding in XxxApplicationService
- adding same tests in XxxResourceIT
- coding in XxxResource

Later, applicationService will contain security check, so it's important to keep for now.

2021-12-21 17:11 UTC, pascalgrimaud requested changes

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/aop/logging/domain/AopLogging.java
> +public class AopLogging {
no need, maybe we can remove it ?

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/aop/logging/domain/AopLoggingDomainService.java
> +  private static final String LOGGING_PROPERTY_FIELDS = "spring.aop.logging";
I'd prefer using `application.aop.logging` instead

application.* is specific to each project.
spring.* should be official configuration from spring lib

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/aop/logging/infrastructure/primary/rest/AopLoggingResource.java
> +  @ApiResponses({ @ApiResponse(responseCode = "500", description = "An error occurred while adding Springbot APO logging") })
```suggestion
  @ApiResponse(responseCode = "500", description = "An error occurred while adding Springbot APO logging")
```

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/aop/logging/infrastructure/primary/rest/AopLoggingResource.java
> +import io.swagger.v3.oas.annotations.responses.ApiResponses;
remove this (following the other comment, in this class)

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspect.java.mustache
> +import org.aspectj.lang.JoinPoint;
```suggestion
import java.util.Arrays;
import org.aspectj.lang.JoinPoint;
```

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspect.java.mustache
> +    @Value("${spring.aop.logging:false}")
```suggestion
    @Value("${application.aop.logging:false}")
```

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspect.java.mustache
> +    public LoggingAspect() {
it would be cool if this class can be indent with 2 spaces intead?

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectConfiguration.java.mustache
> +    @ConditionalOnProperty("spring.aop.logging")
```suggestion
    @ConditionalOnProperty("application.aop.logging")
```

2021-12-21 17:11 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectConfiguration.java.mustache
> +    public LoggingAspect loggingAspect() {
indent the class with 2 spaces, if possible?

2021-12-21 17:12 UTC, pascalgrimaud commented
@MSaguer : thanks for this contribution :)
Can you rebase against main branch plz? You're a little bit late :)
`This branch is 2 commits ahead, 51 commits behind jhipster:main.`

2021-12-21 17:28 UTC, pascalgrimaud commented
Before testing, I needed to add this, in `application-fast.properties`:

```
logging.level.tech.jhipster.beer=DEBUG
```

It means, it should be added by default -> I'll do another PR for this

Then, I started the application with `fast` profile and it works well:

```
2021-12-21 18:26:36.127 DEBUG 113111 --- [nio-8080-exec-1] t.j.b.a.i.p.rest.AuthenticationResource  : Enter: authorize() with argument[s] = [LoginDTO{username='admin', rememberMe=false}]
2021-12-21 18:26:36.565 DEBUG 113111 --- [nio-8080-exec-1] t.j.b.a.i.p.rest.AuthenticationResource  : Exit: authorize() with result = <200 OK OK,tech.jhipster.beer.account.infrastructure.primary.rest.AuthenticationResource$JWTToken@43d396f0,[Authorization:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNjQwMTkzOTk2fQ.dc7K4V4wPcpy0GVB4uGqYSzSu3EHxWffww6agf7icYFZQQB3r5GBklF_o71a9pnTO9tGhH6C2D1aULmFWmV28A"]>
```

2021-12-21 20:05 UTC, MSaguer commented
Remarks taken into account but not tested yet. I'l do it tomorrow.
Now it's time to use the PC to display a film to the family 😄

2021-12-21 21:04 UTC, pascalgrimaud commented
@MSaguer : yes, take care of yourself and families. It's more important than Open Source projects, as it can wait :) Nothing is urgent, as we do it during our freetime ;)

Again, thanks so much for helping this project

2021-12-22 11:57 UTC, MSaguer commented
Question about the logging.level.tech.jhipster.beer property initialization. I think it could be set with default value as following
- defaut : info
- fast : debug
- test : info
Do you agree?

2021-12-22 12:07 UTC, pascalgrimaud commented
Yes agree @MSaguer

2021-12-22 13:23 UTC, pascalgrimaud commented
@MSaguer : forgot to ask this. Can you add the API to these tests plz ? https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L22-L46

2021-12-22 13:28 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/aop/logging/domain/AopLoggingDomainService.java
> +    springBootPropertiesService.addProperties(project, loggingProperty, "INFO");
2 solutions:
- do you think we should add this in AOP logging
- or should this property be by default in the initial generation of application.properties ?

I'd vote for the 2nd choice, so the user will have the default property and he/she can change it.
But maybe he/she doesn't want the AOP logging.

What do you think?

2021-12-22 13:31 UTC, pascalgrimaud commented
Just tested it, and the build will fail with JaCoCo:

```
[WARNING] Rule violated for class tech.jhipster.beer.technical.infrastructure.secondary.aop.logging.LoggingAspect: lines covered ratio is 0.57, but expected minimum is 1.00
[WARNING] Rule violated for class tech.jhipster.beer.technical.infrastructure.secondary.aop.logging.LoggingAspect: branches covered ratio is 0.40, but expected minimum is 1.00
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:21 min
[INFO] Finished at: 2021-12-22T14:27:23+01:00
[INFO] ------------------------------------------------------------------------
```

It's normal as there is no tests for LoggingAspect.
it looks not so easy to add. If you need help, ask me, and I'll try to help here.

2021-12-22 13:48 UTC, MSaguer commented on src/main/java/tech/jhipster/lite/generator/server/springboot/aop/logging/domain/AopLoggingDomainService.java
> +    springBootPropertiesService.addProperties(project, loggingProperty, "INFO");
Ok for the second option that makes sens.
I transform the application properties files into mustache files generated by the springBootApplicationService

2021-12-24 14:52 UTC, pascalgrimaud commented
Just for your information, there are some conflicts. I wanted to solve with phone but it doesn't work well :-D

Take your time to solve it plz, nothing urgent.

2021-12-25 16:41 UTC, MSaguer commented
It was a good idea to stop trying to fix conflicts with your phone. There were more than one file to fix :)

2021-12-25 16:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +public class LoggingAspectTest {
No need public

2021-12-25 16:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +    @Mock
Indent all this class with 2 spaces

2021-12-25 16:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +    public void setup() {
Remove public

2021-12-25 16:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +    public void shouldGetLogger() {
Remove public

2021-12-25 16:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +    public void shouldLogAfterWithLoggingTrueAndExceptionCause() {
Remove public on all tests plz :-)

2021-12-25 16:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +
Remove this additional line.

2021-12-25 20:36 UTC, MSaguer commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +    @Mock
That's almost what I did : generate the real project, check that code is OK, copy paste the code into the mustache file. I've forgot to run the pettier command. And it's not the first time :(
Maybe we could add a "prettier --check" command on generated project in the github action to raise these errors earlier.

2021-12-25 20:56 UTC, MSaguer commented on src/main/resources/generator/server/springboot/aop/logging/LoggingAspectTest.java.mustache
> +    public void shouldLogAfterWithLoggingTrueAndExceptionCause() {
Adding public on classes and methods is an habit I've taken since a so long time. Maybe a bad one when it's about tests.
Do you think it could be a usefull to had a Arch test in generated project to check if public has been set in test classes and methods?

2021-12-25 21:14 UTC, pascalgrimaud approved these changes

2021-12-25 21:14 UTC, pascalgrimaud commented
Really great work @MSaguer !!

2021-12-25 21:15 UTC, merged