Prettier xml
jhipster/jhipster-lite pull request #380
Opened 2021-12-21 17:33 UTC by MSaguer

To close #103 

Prettier-xml added and called automatically during commit with default values

2021-12-21 21:15 UTC, pascalgrimaud commented
I don't understand how this plugin should work.
I changed the indentation in `pom.xml` :

![image](https://user-images.githubusercontent.com/9156882/146998539-4df3bdae-03bc-40fe-afde-d7c24ac4ef22.png)

But everything is well formated:

![image](https://user-images.githubusercontent.com/9156882/146998616-07995b08-c017-4ebc-b663-138543887d12.png)

2021-12-22 06:27 UTC, MSaguer commented
That also surprised me that this indentation feature doesn't work out of
the box.
I must have missed something. I'll give it another try in the week.

Le mar. 21 déc. 2021 à 22:15, Pascal Grimaud ***@***.***> a
écrit :

> I don't understand how this plugin should work.
> I changed the indentation in pom.xml :
>
> [image: image]
> <https://user-images.githubusercontent.com/9156882/146998539-4df3bdae-03bc-40fe-afde-d7c24ac4ef22.png>
>
> But everything is well formated:
>
> [image: image]
> <https://user-images.githubusercontent.com/9156882/146998616-07995b08-c017-4ebc-b663-138543887d12.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jhipster/jhipster-lite/pull/380#issuecomment-999098873>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKD3UIP7FBRNKWK35C72CYLUSDU6VANCNFSM5KQWOA3Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2021-12-22 08:44 UTC, pascalgrimaud commented
@MSaguer : I found the issue. We need to add this property in `.prettierrc` file

```diff
diff --git a/.prettierrc b/.prettierrc
index 34b8d15..7c210c3 100644
--- a/.prettierrc
+++ b/.prettierrc
@@ -11,6 +11,9 @@ arrowParens: avoid
 # jsx and tsx rules:
 bracketSameLine: false
 
+# xml
+xmlWhitespaceSensitivity: ignore
+
 # java rules:
 overrides:
   - files: "*.java"
```

2021-12-22 08:46 UTC, pascalgrimaud requested changes

2021-12-22 08:46 UTC, pascalgrimaud commented on package.json
> +    "@prettier/plugin-xml": "^1.1.0",
I'd prefer to use fixed version, as we have tons of issue in generator-jhipster when using `^`

```suggestion
    "@prettier/plugin-xml": "1.1.0",
```

2021-12-22 08:46 UTC, pascalgrimaud commented on package.json
> +    "prettier": "^2.5.1",
```suggestion
    "prettier": "2.5.1",
```

2021-12-22 11:13 UTC, pascalgrimaud approved these changes

2021-12-22 11:13 UTC, merged