Add sonar
jhipster/jhipster-lite pull request #381
Opened 2021-12-21 19:16 UTC by swarajsaaj

2021-12-21 21:15 UTC, pascalgrimaud commented
I'll review it tomorrow @swarajsaaj :)
Too tired for today

2021-12-22 09:28 UTC, pascalgrimaud requested changes

2021-12-22 09:28 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/infrastructure/primary/SonarResource.java
> +@Tag(name = "Server")
```suggestion
@Tag(name = "Sonar")
```

2021-12-22 09:28 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/domain/Sonar.java
> +  public static final String SONARQUBE_DOCKER_VERSION = "9.2.4-community";
maybe doing the same than in MySQL, by including the image name too?

```suggestion
  public static final String SONARQUBE_DOCKER_IMAGE = "sonarqube:9.2.4-community";
```

2021-12-22 09:28 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/domain/SonarDomainService.java
> +    project.addConfig("dockerImageName", Sonar.getSonarqubeDockerVersion());
I would apply this change. The main reason is to avoid conflict with possible same "config" in Project, when later, we'll compose all services to generate full application (like in generator-jhipster)

```suggestion
    project.addConfig("sonarqubeDockerImage", Sonar.getSonarqubeDockerImage());
```

2021-12-22 09:28 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/domain/Sonar.java
> +    return SONARQUBE_DOCKER_VERSION;
```suggestion
  public static String getSonarqubeDockerImage() {
    return SONARQUBE_DOCKER_IMAGE;
```

2021-12-22 09:28 UTC, pascalgrimaud commented on src/main/resources/generator/server/sonar/sonar.yml.mustache
> +    image: sonarqube:{{dockerImageName}}
```suggestion
    image: sonarqube:{{sonarqubeDockerImage}}
```

2021-12-22 09:28 UTC, pascalgrimaud commented on src/main/resources/generator/server/sonar/sonar-project.properties.mustache
> +#sonar.javascript.lcov.reportPaths=target/test-results/lcov.info
it was my fault :D we could remove this

2021-12-22 09:28 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/sonar/domain/SonarTest.java
> +public class SonarTest {
```suggestion
class SonarTest {
```

2021-12-22 09:28 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/sonar/infrastructure/primary/rest/SonarResourceIT.java
> +    Project project = ProjectDTO.toProject(projectDTO);
```suggestion
    ProjectDTO projectDTO = TestUtils.readFileToObject("json/chips.json", ProjectDTO.class).folder(FileUtils.tmpDirForTest());
    Project project = ProjectDTO.toProject(projectDTO);
```

2021-12-22 09:28 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/sonar/infrastructure/primary/rest/SonarResourceIT.java
> +  void shouldInit() throws Exception {
maybe rename to shouldAddSonar, to match with the method in SonarResource ?

2021-12-22 09:34 UTC, pascalgrimaud requested changes

2021-12-22 09:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/domain/SonarDomainService.java
> +import tech.jhipster.lite.generator.server.springboot.database.mysql.domain.MySQL;
can be removed

2021-12-22 09:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/infrastructure/config/SonarBeanConfiguration.java
> +import tech.jhipster.lite.generator.server.javatool.jacoco.domain.JacocoService;
can be removed

2021-12-22 09:34 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/sonar/infrastructure/config/SonarBeanConfigurationIT.java
> +import tech.jhipster.lite.generator.server.springboot.database.mysql.domain.MySQLDomainService;
remove this

2021-12-22 09:34 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/sonar/infrastructure/primary/rest/SonarResourceIT.java
> +import tech.jhipster.lite.error.domain.GeneratorException;
not used

2021-12-22 09:34 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/sonar/infrastructure/primary/rest/SonarResourceIT.java
> +import tech.jhipster.lite.generator.server.springboot.core.application.SpringBootApplicationService;
remove this

2021-12-22 12:31 UTC, pascalgrimaud requested changes

2021-12-22 12:31 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/sonar/domain/SonarDomainService.java
> +          </configuration>
wrong indent here, missing 2 spaces I think

2021-12-22 13:24 UTC, pascalgrimaud commented
@swarajsaaj  : forgot to ask this. Can you add the API to these tests too plz ? https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L22-L46

2021-12-22 15:11 UTC, pascalgrimaud requested changes

2021-12-22 15:11 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/sonar
```suggestion
  callApi "/api/servers/sonar"
```

2021-12-22 15:17 UTC, swarajsaaj commented on tests-ci/generate.sh
> +  callApi "/api/servers/sonar
Ah. Thanks :)

2021-12-22 15:24 UTC, pascalgrimaud commented
Is it ready to be merged?

2021-12-22 15:24 UTC, pascalgrimaud approved these changes

2021-12-22 15:34 UTC, swarajsaaj commented
> Is it ready to be merged?

Yes please

2021-12-22 16:53 UTC, merged

2021-12-22 17:02 UTC, pascalgrimaud commented
Could you fix this new code smells in a next PR too plz?
https://sonarcloud.io/project/issues?id=jhipster_jhipster-lite&open=AX3jEfawla2Sa0kGvzBB&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL

Otherwise, I'll do it the next time I power on my computer :-)

2022-01-08 17:05 UTC, swarajsaaj commented
bounty claimed at https://opencollective.com/generator-jhipster/expenses/60637

2022-01-08 18:02 UTC, pascalgrimaud commented
@swarajsaaj : approved