Feature/okta configuration
jhipster/jhipster-lite pull request #3812
Opened 2022-10-04 14:09 UTC by juliensadaoui

fix #3634

2022-10-04 14:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/domain/SpringDocOktaModuleFactory.java
> +  private static String clientId(JHipsterModuleProperties properties) {
This can directly result in a property value

2022-10-04 14:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/domain/SpringDocOktaModuleFactory.java
> +  private String authorizationUrl(JHipsterModuleProperties properties) {
This can directly result in a property value

2022-10-04 14:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertiesDefinition.java
> +    public JHipsterModulePropertiesDefinitionBuilder addClientId() {
Not sure to add that here, it's really specific to okta so maybe stick to calling add(...), dunno

2022-10-04 14:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertiesDefinition.java
> +    public JHipsterModulePropertiesDefinitionBuilder addOktaDomain() {
Not sure to add that here, it's really specific to okta so maybe stick to calling add(...), dunno

2022-10-04 14:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinition.java
> +      .order(100)
Using different order value can avoid strange behaviors on the frontend with field swaping orders

2022-10-04 14:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulePropertyDefinition.java
> +    return mandatoryStringProperty("oktaDomain").description("Okta domain").example("dev-123456.okta.com").order(100).build();
Using different order value can avoid strange behaviors on the frontend with field swaping orders

2022-10-04 17:20 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/domain/SpringDocOktaModuleFactory.java
> +  private static String clientId(JHipsterModuleProperties properties) {
I mean returning `PropertyValue` instead of `String` :)

2022-10-04 17:20 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/domain/SpringDocOktaModuleFactory.java
> +  private String authorizationUrl(JHipsterModuleProperties properties) {
I mean returning `PropertyValue` instead of `String` :)

2022-10-06 07:16 UTC, DamnClin reviewed
So sad we can't add those apps in the generate.sh to have a CI on them... Nevertheless very good additions. Thanks a lot.

How was your contributing experience? Any improvement on JHLite modules APIs you have in mind?

2022-10-06 07:16 UTC, DamnClin commented on src/main/resources/generator/server/springboot/mvc/security/oauth2/auth0/documentation/auth0.md.mustache
> +```javascript
Line break before that I think

2022-10-06 07:16 UTC, DamnClin commented on src/main/resources/generator/server/springboot/mvc/security/oauth2/auth0/documentation/auth0.md.mustache
> +In your application, modify src/main/resources/config/application-auth0.yml to use your Auth0 settings. Hint: replace {yourAuth0Domain} with your org’s name (e.g., dev-123456.us.auth0.com).
modify -> update

2022-10-06 07:16 UTC, DamnClin commented on src/main/resources/generator/server/springboot/mvc/security/oauth2/auth0/documentation/auth0.md.mustache
> +Modify `auth0.sh` to use your Auth0 settings.
Modify -> Update

2022-10-06 07:16 UTC, DamnClin commented on src/main/resources/generator/server/springboot/mvc/security/oauth2/okta/documentation/okta.md.mustache
> +Modify `src/main/resources/config/application-okta.yml` to use your Okta settings. Hint: replace {yourOktaDomain} with your org’s name (e.g., dev-123456.okta.com).
Modify -> Update

2022-10-06 08:06 UTC, juliensadaoui commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocauth0/domain/SpringDocAuth0ModuleFactory.java
> +    return propertyValue(
It's for this reason that i don't use a StringBuilder. When i use Intellij, it suggests this notice for me. notice: 'StringBuilder sb' can be replaced with 'String'

2022-10-06 08:30 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocauth0/domain/SpringDocAuth0ModuleFactory.java
> +    return propertyValue(
Yep, this is doing the exact same thing (one of the few compile time optimization in java) but, sometimes, the fluent API of StringBuilder gives a better readability

2022-10-06 09:14 UTC, juliensadaoui commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocokta/infrastructure/primary/SpringDocOktaModuleConfiguration.java
> +          .addModuleDependency("springdoc-oauth2")
you're right !

2022-10-07 05:31 UTC, DamnClin approved these changes

2022-10-07 07:14 UTC, pascalgrimaud requested changes

2022-10-07 07:14 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/security/oauth2/okta/documentation/okta.md.mustache
> +SPRING_PROFILES_ACTIVE=otka ./mvnw
```suggestion
SPRING_PROFILES_ACTIVE=okta ./mvnw
```

2022-10-07 07:14 UTC, pascalgrimaud commented on src/test/features/oauth2.feature
> +    And I apply "spring-boot-oauth2-auth" module with parameters to last project
```suggestion
    And I apply "spring-boot-oauth2-auth0" module with parameters to last project
```

2022-10-07 07:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdocauth0/infrastructure/primary/SpringDocAuth0ModuleConfiguration.java
> +        JHipsterModuleOrganization.builder().addFeatureDependency("springdoc").addModuleDependency("spring-boot-oauth2-auth").build()
```suggestion
        JHipsterModuleOrganization.builder().addFeatureDependency("springdoc").addModuleDependency("spring-boot-oauth2-auth0").build()
```

2022-10-07 07:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/auth0/infrastructure/primary/OAuth2Auth0ModuleConfiguration.java
> +      .slug("spring-boot-oauth2-auth")
```suggestion
      .slug("spring-boot-oauth2-auth0")
```

2022-10-07 07:16 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/security/oauth2/okta/documentation/okta.md.mustache
> +
you could add this command too:

```
./mvnw -Dspring-boot.run.profiles=okta
```

2022-10-07 08:13 UTC, pascalgrimaud approved these changes

2022-10-07 08:13 UTC, merged

2022-10-07 08:22 UTC, juliensadaoui commented
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/100331

2022-10-07 08:41 UTC, pascalgrimaud commented
@juliensadaoui : approved