move module endpoints (get + post /apply-patch)
jhipster/jhipster-lite pull request #3931
Opened 2022-10-12 13:43 UTC by AnneJacquet

closes #3276

2022-10-12 14:58 UTC, DamnClin requested changes

2022-10-12 14:58 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  public void applyPatch(@RequestBody @Validated RestJHipsterModuleProperties restProperties, @PathVariable("slug") String slug) {
I remember now that I had to do the dynamic stuff to handle legacy URLs. An attention point: I think the swagger documentation for this is not OK now. I think we should keep the dynamic documentation and not document this endpoint

2022-10-12 14:58 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  public RestJHipsterModulePropertiesDefinition propertiesDefinition(@PathVariable("slug") String slug) {
Same as previous endpoint

2022-10-13 14:15 UTC, AnneJacquet commented on src/test/java/tech/jhipster/lite/module/infrastructure/secondary/TestJHipsterModules.java
> +        new JHipsterModulesResources(List.of(defaultModuleResourceBuilder().slug("test-module").factory(properties -> module).build()))
Had to change the test as only the slug and the properties and needed to apply module. And the module is fetch with its slug from the list. So the list is no longer static in the test but only contains 1 module each time : the one we're trying to apply.

2022-10-13 14:47 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  public JHipsterModuleResource get(JHipsterModuleSlug slug) {
This logic can't be in the resource. This is a business responsibility, must be in the domain

2022-10-13 14:47 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  public void applyPatch(@RequestBody @Validated RestJHipsterModuleProperties restProperties, @PathVariable("slug") String slug) {
Yep, we just need to be sure that this endpoint is ignored in swagger

2022-10-13 14:47 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/infrastructure/primary/ModulesSteps.java
> +import static org.assertj.core.api.Assertions.assertThat;
Update your static imports policy to have * starting at 1

2022-10-13 16:13 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  public JHipsterModuleResource get(JHipsterModuleSlug slug) {
Oh my bad! I'll take a closer look at that tomorrow, sorry

2022-10-13 16:38 UTC, AnneJacquet commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  public JHipsterModuleResource get(JHipsterModuleSlug slug) {
Ok great, no problem, thought I was missing something !

2022-10-14 11:29 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  public JHipsterModuleResource get(JHipsterModuleSlug slug) {
Ok, great!

I'll go with: 

```java
  public JHipsterModuleResource get(JHipsterModuleSlug slug) {
    assertKnownSlug(slug);
    
    return resources.get(slug);
  }

  private void assertKnownSlug(JHipsterModuleSlug slug) {
    Assert.notNull("slug", slug);
    
    if (!resources.containsKey(slug)) {
      throw new UnknownSlugException(slug);
    }
  }
```

2022-10-14 11:29 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  @Tag(name = "Modules")
annotation order: shortest ones comes first

2022-10-14 11:29 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  @Tag(name = "Modules")
annotation order: shortest ones comes first

2022-10-14 11:29 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  @Tag(name = "Modules")
annotation order: shortest ones comes first

2022-10-14 11:29 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  public void applyPatch(@RequestBody @Validated RestJHipsterModuleProperties restProperties, @PathVariable("slug") String slug) {
This is shown in swagger and it's really important that it don't show since there are better documentation for each modules

2022-10-14 15:23 UTC, AnneJacquet commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  public void applyPatch(@RequestBody @Validated RestJHipsterModuleProperties restProperties, @PathVariable("slug") String slug) {
I looked too quickly, I thought removing the @Tag from the controller worked 🤦‍♀️ Done !

2022-10-14 15:29 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  @Hidden
This one should not be hidden I think since there is nothing specific by module

2022-10-14 15:37 UTC, AnneJacquet commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  @Hidden
I don't know if we're talking about the same thing but there are 2 endpoints per module on the swagger ui
![image](https://user-images.githubusercontent.com/18069443/195886047-96e50433-2d95-4aa0-8238-ac1129e6177b.png)

2022-10-14 15:40 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java
> +  @Hidden
Oh true, I though that was the apply all endpoint... I should stop doing reviews on my phone...

2022-10-14 15:44 UTC, DamnClin approved these changes

2022-10-14 15:57 UTC, merged

2022-10-14 15:57 UTC, DamnClin commented
Thanks for your work here @AnneJacquet , don't forget to claim for the $300 for this :)

2022-10-17 06:12 UTC, AnneJacquet commented
Claimed https://opencollective.com/generator-jhipster/expenses/102135 :)

2022-10-17 06:29 UTC, pascalgrimaud commented
@AnneJacquet : approved, thanks for your work :-)