add neo4j support
jhipster/jhipster-lite pull request #3950
Opened 2022-10-13 15:15 UTC by atomfrede

This adds the neo4j spring boot starter and if desired neo4j-migrations to an application (I hope I didn't forget any important tests on jh-lite).

I plan to add some dummy module for this, will be a dedicated PR

EDIT: Going to check why the cucumber test is failing. It works doing it manuallyvia the ui.

2022-10-13 15:26 UTC, DanielFran requested changes

2022-10-13 15:26 UTC, DanielFran commented on src/main/resources/generator/server/springboot/database/neo4j/spring.factories.mustache
> +org.springframework.context.ApplicationListener={{packageName}}.TestNeo4jManager
Should be used META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports instead of META-INF/spring.factories

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration

2022-10-13 15:26 UTC, DanielFran commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactoryTest.java
> +      .hasFile("src/test/resources/META-INF/spring.factories")
Should be used META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports instead of META-INF/spring.factories

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration

2022-10-13 15:34 UTC, DamnClin reviewed
Some minor comments but overall that looks really good.

This seems to be your first big modules contribution (the gitlab ci one was way smaller). Ho was the dev experience? Any feedback on the module API?

2022-10-13 15:34 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactory.java
> +import static tech.jhipster.lite.module.domain.JHipsterModule.artifactId;
You should update your static import policy to add * starting a 1

2022-10-13 15:34 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactory.java
> +        .files()
Indentation is strange here I think. We usually do: 

```
.javaDependencies()
  .stuff(...)
  .and()
.files()
  .stuff()
```

Reason beeing we don't really care about the `.and()` but want to clearly see the new elements

2022-10-13 15:34 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactory.java
> +  private String startupCommand() {
Can be inlined I think

2022-10-13 15:34 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/infrastructure/primary/Neo4jModuleConfiguration.java
> +      .slug("neo4j")
This is probably deprecated, can you switch to the definition using [JHLiteModuleSlug.java](https://github.com/jhipster/jhipster-lite/pull/3950/files#diff-b332b2ad7ed756b4b0b7530411e8cd6b5d7a3900f8112539be0a592ed8869d01) ?

2022-10-13 15:34 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/neo4jmigrations/domain/Neo4jMigrationsModuleFactory.java
> +import static tech.jhipster.lite.module.domain.JHipsterModule.artifactId;
Same for static imports

2022-10-13 15:34 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/neo4jmigrations/domain/Neo4jMigrationsModuleFactory.java
> +    return moduleBuilder(properties)
I prefer this formatting

2022-10-13 15:34 UTC, DamnClin commented on src/main/resources/generator/server/springboot/database/neo4j/TestNeo4jManager.java.mustache
> +public class TestNeo4jManager implements ApplicationListener<ApplicationEnvironmentPreparedEvent> {
This really needs to be public?

2022-10-13 15:34 UTC, DamnClin commented on src/test/features/neo4j.feature
> +    When I apply modules to default project
Array indentation is off

2022-10-13 15:35 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactory.java
> +import static tech.jhipster.lite.module.domain.JHipsterModule.artifactId;
Ah yes, did this on another machine.

2022-10-13 15:35 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactory.java
> +        .files()
Was not sure, but makes sense with `.and` further indented.

2022-10-13 16:05 UTC, atomfrede commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactoryTest.java
> +      .hasFile("src/test/resources/META-INF/spring.factories")
Are you sure? It is not an autoconfiguration.

2022-10-13 16:09 UTC, atomfrede commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactoryTest.java
> +      .hasFile("src/test/resources/META-INF/spring.factories")
At least the documentation still mentions spring.facotries https://docs.spring.io/spring-boot/docs/2.7.4/reference/htmlsingle/#features.spring-application.application-events-and-listeners

2022-10-13 16:33 UTC, atomfrede commented
> Some minor comments but overall that looks really good.
> 
> This seems to be your first big modules contribution (the gitlab ci one was way smaller). Ho was the dev experience? Any feedback on the module API?

After I figured out where all relevant properties (e.g. dependency versions, docker file versions etc.) are located and where to add them it was very nice to use.

2022-10-13 16:40 UTC, DanielFran commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/neo4j/domain/Neo4jModuleFactoryTest.java
> +      .hasFile("src/test/resources/META-INF/spring.factories")
Did not even validate what the purpose of this file was; sorry, just remember that spring deprecated it for the autoconfiguration files

2022-10-14 08:36 UTC, DamnClin commented
@atomfrede 

> After I figured out where all relevant properties (e.g. dependency versions, docker file versions etc.) are located and where to add them it was very nice to use.

I wasn't sure how to give good hints on that. The exceptions message gives the path but that's probably not enough, adding that to the module contribution documentation would have help (or you didn't use this doc at all)?

Perhaps we should work on javadoc for the module API, may be helpful, dunno, advice appreciated

2022-10-14 08:59 UTC, atomfrede commented
:D I didn't look at it of course. We should make it more visible in the readme maybe. The main problem in the end was the cucumber test and two locations for e.g. the dockerfile names. So testing it locally and via unit tests everything worked fine, running it via cucumber failed and the error messages pointed to the dockerfile which contained the neo4j image 😄 

The module creation looks fine already but an overview where certain (common) files are located would be helpful, in particular for new contributors

2022-10-14 14:36 UTC, pascalgrimaud commented
great work @atomfrede 
I'll have a look and play with it soon

2022-10-14 14:41 UTC, atomfrede commented
@pascalgrimaud No need to hurry

2022-10-15 07:31 UTC, pascalgrimaud requested changes
some minor changes and we should be good to go

2022-10-15 07:31 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/neo4j/TestNeo4jManager.java.mustache
> +        .withoutAuthentication();
```suggestion
    neo4jContainer = new Neo4jContainer(DockerImageName.parse("{{neo4jDockerImage}}")).withoutAuthentication();
```

2022-10-15 07:31 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/neo4j/TestNeo4jManager.java.mustache
> +        .addShutdownHook(new Thread(stopContainer()));
```suggestion
    Runtime.getRuntime().addShutdownHook(new Thread(stopContainer()));
```

2022-10-15 07:31 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/neo4j/neo4j.yml.mustache
> +      - "127.0.0.1:7687:7687"
```suggestion
      - '127.0.0.1:7474:7474'
      - '127.0.0.1:7687:7687'
```

2022-10-15 07:31 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/neo4j/neo4j.yml.mustache
> +  mongodb:
```suggestion
  neo4j:
```

2022-10-15 07:31 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/neo4j/TestNeo4jManager.java.mustache
> +import org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent;
```suggestion
import org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent;
```

2022-10-17 11:54 UTC, pascalgrimaud approved these changes

2022-10-17 11:54 UTC, merged

2022-10-18 14:41 UTC, atomfrede commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/102433 ❤️ @pascalgrimaud for putting a bounty on it

2022-10-18 14:57 UTC, pascalgrimaud commented
@atomfrede : approved, totally deserved. Thanks for your work