enum module
jhipster/jhipster-lite pull request #4046
Opened 2022-10-19 20:45 UTC by cemdrman

2022-10-19 20:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=4046) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=4046) before we can accept your contribution.<br/><hr/>**cem dırman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=4046) it.</sub>

2022-10-20 05:04 UTC, pascalgrimaud requested changes

2022-10-20 05:04 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/JHLiteModuleSlug.java
Rename to JAVA_ENUMS and order it plz

2022-10-20 05:04 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/enums/primary/EnumModuleConfiguration.java
> +      .apiDoc("Java", "Add Enum module")
```suggestion
      .apiDoc("Java", "Add Enums module")
```

2022-10-20 05:04 UTC, pascalgrimaud commented on src/main/resources/generator/enums/EnumsTest.java.mustache
> +import tech.jhipster.lite.UnitTest;
Should be templated, with packageName

2022-10-20 05:07 UTC, pascalgrimaud commented
Thanks and congrats for your 1st contribution @cemdrman 

Can you sign the CLA plz?
In the 1st comment, can you add: fix https://github.com/jhipster/jhipster-lite/issues/3826 so it will be closed automatically

2022-10-20 05:23 UTC, DamnClin commented on src/main/resources/generator/enums/Enums.java.mustache
> +import tech.jhipster.lite.error.domain.Assert;
Needs to be templated

2022-10-20 19:42 UTC, cemdrman commented
> 
@pascalgrimaud how can I add fix number to my commit? i don't get it sorry.

2022-10-20 20:53 UTC, pascalgrimaud commented
I edited the comment for you, to put: `fix #3826`

2022-10-21 09:17 UTC, pascalgrimaud commented
Maybe you need to change the email in your commit too, otherwise, you won't be able to sign the CLA ?

2022-10-21 10:54 UTC, cemdrman commented
> Maybe you need to change the email in your commit too, otherwise, you won't be able to sign the CLA ?

actually, i already changed my last commits' name and email but still i can't sign.

2022-10-21 12:49 UTC, pascalgrimaud commented
It's because of the the first commit, with another email:

![image](https://user-images.githubusercontent.com/9156882/197199432-d5d5e2d7-6b1c-40d8-abdc-dab8e12a008c.png)

You can squash your 2 commits into 1 single, then edit again the email, sign the CLA and I hope it should be good :-D

2022-10-21 15:39 UTC, cemdrman commented
> It's because of the the first commit, with another email:
> 
> ![image](https://user-images.githubusercontent.com/9156882/197199432-d5d5e2d7-6b1c-40d8-abdc-dab8e12a008c.png)
> 
> You can squash your 2 commits into 1 single, then edit again the email, sign the CLA and I hope it should be good :-D

finally I dit it :laughing

2022-10-23 12:09 UTC, DamnClin commented on src/main/resources/generator/enums/UnmappableEnumException.java.mustache
> +import {{packageName}}.error.domain.GeneratorException;
There is no GeneratorException in the generated apps since GeneratorException is for the Generator

2022-10-23 12:09 UTC, DamnClin commented on src/main/resources/generator/enums/EnumsTest.java.mustache
> +import {{packageName}}.generator.enums.Enums;
I don't understand this, why not putting the test in the same package as the class?

2022-10-23 12:10 UTC, DamnClin commented on src/test/features/enums.feature
> +      | Enums.java |
Missing line at end of file

2022-10-23 12:10 UTC, DamnClin commented on src/main/resources/generator/enums/UnmappableEnumException.java.mustache
> +}
Missing line at end of file

2022-10-31 21:17 UTC, cemdrman commented on src/test/features/enums.feature
> +      | Enums.java |
why this is matter? I'm just asking because I don't understand and also there are files like this.

2022-10-31 21:19 UTC, DamnClin commented on src/test/features/enums.feature
> +      | Enums.java |
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2022-10-31 21:35 UTC, cemdrman commented on src/main/resources/generator/enums/UnmappableEnumException.java.mustache
> +import {{packageName}}.error.domain.GeneratorException;
to be honest, I created these mustache files with just copy-paste. I copied .java file and then pasted to .mustache file.
so I don't know why I'm need to create these files and what im need to do?

2022-11-01 06:12 UTC, DamnClin commented on src/main/resources/generator/enums/UnmappableEnumException.java.mustache
> +import {{packageName}}.error.domain.GeneratorException;
The template files are the one used when applying the module. You need to have something that will compile in the generated app :⁠-⁠)

2022-11-01 06:21 UTC, pascalgrimaud commented on src/main/resources/generator/enums/UnmappableEnumException.java.mustache
> +import {{packageName}}.error.domain.GeneratorException;
We could remove the extends GeneratorException

2022-11-11 16:35 UTC, pascalgrimaud commented
@cemdrman : do you need help to finish this PR ?

2022-11-14 21:13 UTC, cemdrman commented
> @cemdrman : do you need help to finish this PR ?

yes, I need help, cause I did not understand what I need to do. and I'm sorry for late

2022-11-16 05:26 UTC, pascalgrimaud commented
Ok I'll help you to finish your work here
Don't be sorry for trying to contribute to Open Source projects :-)

2022-12-09 13:11 UTC, DamnClin requested changes

2022-12-09 13:11 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/enums/primary/EnumModuleConfiguration.java
> +      .standalone()
This is not standalone, it depends on java-base

2022-12-09 13:11 UTC, DamnClin commented on src/main/resources/generator/enums/UnmappableEnumException.java.mustache
> +class UnmappableEnumException {
This un a `RuntimeException`

2022-12-11 13:00 UTC, DamnClin commented
Hello @cemdrman I'll need this module for the internationalized errors module (coming after Spring Boot 3 migration) do you plan on finishing it or I do it?

2022-12-14 16:25 UTC, DamnClin commented
@cemdrman sorry but I needed this module so I built it in https://github.com/jhipster/jhipster-lite/pull/4745. You have nothing to be ashamed of! It was totally my fault to think that this can be a good first issue when it is not!

Please give JHLite contributions another try, I'll be very happy to help if I can!

2022-12-14 17:49 UTC, pascalgrimaud commented
Closing in favor of https://github.com/jhipster/jhipster-lite/pull/4745

Sorry my fault too, I didn't have time to commit directly to this PR to finish it

2022-12-14 17:49 UTC, closed without merging