add Optional typescript module
jhipster/jhipster-lite pull request #4058
Opened 2022-10-20 14:18 UTC by thomaslmbrt

Close #4057

2022-10-20 14:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=4058) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=4058) before we can accept your contribution.<br/><hr/>**Thomas Lambert** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=4058) it.</sub>

2022-10-20 16:13 UTC, pascalgrimaud requested changes

2022-10-20 16:13 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/typescript/optional/domain/OptionalTypescriptModuleFactory.java
> +      .add(from("typescript/webapp/common/domain/optional/").file("Optional.ts"), to("src/webapp/common/domain/Optional.ts"))
```suggestion
      .add(from("typescript/webapp/common/domain/optional/").file("Optional.ts"), to("src/webapp/app/common/domain/Optional.ts"))
```

2022-10-20 16:13 UTC, pascalgrimaud commented on src/test/features/optional-typescript.feature
> +    Then I should have files in "/src/webapp/common/domain/"
```suggestion
    Then I should have files in "/src/webapp/app/common/domain/"
```

2022-10-20 16:13 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/typescript/domain/optional/OptionalTypescriptModuleFactoryTest.java
> +public class OptionalTypescriptModuleFactoryTest {
```suggestion
class OptionalTypescriptModuleFactoryTest {
```

2022-10-20 16:13 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/typescript/domain/optional/OptionalTypescriptModuleFactoryTest.java
> +      .hasFile("src/webapp/common/domain/Optional.ts")
```suggestion
      .hasFile("src/webapp/app/common/domain/Optional.ts")
```

2022-10-20 16:13 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/typescript/optional/primary/OptionalTypescriptModuleConfiguration.java
> +public class OptionalTypescriptModuleConfiguration {
```suggestion
class OptionalTypescriptModuleConfiguration {
```

2022-10-21 08:59 UTC, DamnClin commented on src/main/resources/generator/typescript/webapp/common/domain/optional/Optional.ts
> +  abstract map<Output>(mapper: (value: Value) => Output): Optional<Output>;
I think `or(() => Optional<Value>)` should be added

2022-10-21 09:14 UTC, pascalgrimaud commented
Another comment:

![image](https://user-images.githubusercontent.com/9156882/197160090-49be71e5-37be-41de-9898-2ff8459e2ae2.png)

Can you put a different `package-info.java` inside each folder plz (instead at the root of typescript folder): 
- core
- optional

2022-10-26 07:46 UTC, pascalgrimaud commented on src/main/resources/generator/typescript/webapp/common/domain/optional/Optional.ts
> +  abstract map<Output>(mapper: (value: Value) => Output): Optional<Output>;
this part can be improved in another PR, and for JHLite + Generated part too
Let's merge this for now

2022-10-26 07:46 UTC, merged

2022-10-26 07:47 UTC, pascalgrimaud commented on src/main/resources/generator/typescript/webapp/common/domain/optional/Optional.ts
> +  abstract map<Output>(mapper: (value: Value) => Output): Optional<Output>;
oh forget my comment, it was already added ! :)

2022-10-26 07:48 UTC, pascalgrimaud commented
Thanks a lot for your contribution @thomaslmbrt !