Add chip atom
jhipster/jhipster-lite pull request #4089
Opened 2022-10-24 15:24 UTC by nassimerrahoui

This is PR add an ui component called Chip to modelize one module in the landscape. This is related to migrate CSS to Tikui.
For the moment, it is only an atom in Tikui but the integration is not done because it depends on other PR's. I'm working with @Gnuk 

- Preparation for [Migrate landscape css to tikui](https://github.com/jhipster/jhipster-lite/issues/3970)
- Related to [Put landscape in light](https://github.com/jhipster/jhipster-lite/pull/4088)
- Related to [UX/UI: improve the CSS](https://github.com/jhipster/jhipster-lite/issues/2894)

<img width="1417" alt="Capture d’écran 2022-10-24 à 17 22 54" src="https://user-images.githubusercontent.com/23552990/197563869-493003e6-d1e3-4766-9244-98a2fd82e1f7.png">

2022-10-27 07:40 UTC, nassimerrahoui commented
@Gnuk I think it's ready for a first review

2022-10-31 08:36 UTC, Gnuk commented
I think you need to add an example of the applied chip inside the pattern library

2022-10-31 08:51 UTC, nassimerrahoui commented
> I think you need to add an example of the applied chip inside the pattern library

Done 👍

2022-10-31 08:57 UTC, nassimerrahoui commented
@Gnuk I also updated the screenshots

2022-10-31 09:04 UTC, Gnuk requested changes

2022-10-31 09:04 UTC, Gnuk commented
> @Gnuk I also updated the screenshots

Sorry, I just forgot to apply the review, T-T

2022-10-31 09:19 UTC, nassimerrahoui commented on src/main/style/token/_colors.scss
> +@keyframes valid-highlight-animation {
Done 👍

2022-10-31 09:20 UTC, nassimerrahoui commented on src/main/webapp/app/module/primary/landscape/Landscape.vue
> +  background: #fff;
Found :)

2022-10-31 09:23 UTC, nassimerrahoui commented
> > @Gnuk I also updated the screenshots
> 
> Sorry, I just forgot to apply the review, T-T

@Gnuk it's ok 👌

2022-10-31 09:36 UTC, pascalgrimaud commented
Adding a bounty on this
Thanks for the work @nassimerrahoui !

2022-10-31 09:51 UTC, Gnuk approved these changes

2022-10-31 09:52 UTC, nassimerrahoui commented
> Adding a bounty on this Thanks for the work @nassimerrahoui !

@pascalgrimaud @Gnuk Nice, thank you :D

2022-11-01 07:29 UTC, Gnuk approved these changes

2022-11-01 07:42 UTC, merged

2022-11-01 14:22 UTC, pascalgrimaud commented
@nassimerrahoui : approved