add Spring Boot Logstash Logback appender
jhipster/jhipster-lite pull request #415
Opened 2021-12-27 17:18 UTC by pblanchardie

#276 

- [x] Logstash configuration
- [x] Generator code tests
- [ ] Generated code tests
- [ ] LoggerContextListener: allowed hot reloading of logstash configuration.
In a classic (non-web) application it produces a ConcurrentModificationException on exit (LOGBACK-1299, https://github.com/spring-projects/spring-boot/issues/17439) unless DelayingShutdownHook is removed.
It only makes sense if properties are reloadable, and not sure it's useful.

Refactoring of existing parts?
- [ ] Move logging (`SpringBootLogging*`) to logging.logger (shared kernel)
- [ ] Move logstash to logging.logstash
- [ ] Move aop.logging to logging.aop

2021-12-28 11:17 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logstash/domain/LogstashDomainService.java
> +    buildToolService.addDependency(project, jsonDependency);
@pascalgrimaud this explicit dependency to jackson-databind is not mandatory, as logstash-logback-encoder depends on jackson-databind too. Will be removed.

2021-12-28 14:51 UTC, pascalgrimaud commented
@pblanchardie : is it ready for review?

2021-12-28 15:57 UTC, pblanchardie commented
Yes it needs some review, and answers to naming questions above:

> - [ ] Make it explicit that this is a TCP only configuration
eg. rename route to include "tcp"
> - [ ] Rename config prefix from `logstash` to `application.logstash.tcp`?
> - [ ] Move logging (`SpringBootLogging*`) to logging.logger (shared kernel)
> - [ ] Move logstash to logging.logstash
> - [ ] Move aop.logging to logging.aop

2021-12-28 16:04 UTC, pascalgrimaud commented
> * [ ]  Make it explicit that this is a TCP only configuration

Yes, agree. It can be in API url

> * [ ]  Rename config prefix from `logstash` to `application.logstash.tcp`?

See https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/resources/config/application-prod.yml#L110-L112

The current config is jhipster.logging.logstash
Now, with jhipster lite, it should be application.logging.logstash.tcp

> * [ ]  Move logging (`SpringBootLogging*`) to logging.logger (shared kernel)

Agree, but can it be done in another PR, if it's simpler?

> * [ ]  Move logstash to logging.logstash

Yes

> * [ ]  Move aop.logging to logging.aop

Yes too

2021-12-28 17:35 UTC, pascalgrimaud requested changes

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logstash/domain/Logstash.java
> +  public static final String LOGSTASH_LOGBACK_ENCODER_VERSION = "7.0.1";
I'd prefer to add a specific method, instead of using directly the constant.

The reason is, later, the method will look into a shared pom.xml to extract the correct version.

See https://github.com/jhipster/jhipster-lite/issues/278

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logstash/domain/LogstashDomainService.java
> +    result.put("logstash.enabled", true);
As discussed, maybe using application.logstash instead

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/src/LogstashConfiguration.java.mustache
> +@ConditionalOnProperty(name = "logstash.enabled", havingValue = "true")
Change the property

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/src/LogstashProperties.java.mustache
> +@ConfigurationProperties(prefix = "logstash")
Update: application.logstash

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashConfigurationIT.java.mustache
> +      assertThrows(NoSuchBeanDefinitionException.class, () -> applicationContext.getBean("logstashLifeCycle"));
I'd prefer assertThatThrownBy

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashConfigurationTest.java.mustache
> +    LogstashConfiguration c = new LogstashConfiguration("jhipster-lite", null, new LogstashProperties());
Maybe rename c to configuration ?

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashLifeCycleTest.java.mustache
> +    LogstashLifeCycle l = new LogstashLifeCycle(null, properties);
Rename l to something like lifeCycle

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashLifeCycleTest.java.mustache
> +    LogstashLifeCycle l = new LogstashLifeCycle(null, properties, new ObjectMapper());
Same, rename l variable

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashLifeCycleTest.java.mustache
> +    LogstashLifeCycle l = new LogstashLifeCycle(null, new LogstashProperties(), new ObjectMapper());
Rename l variable

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashLifeCycleTest.java.mustache
> +    LogstashLifeCycle l = new LogstashLifeCycle(null, properties, new ObjectMapper());
Rename l variable

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashLifeCycleTest.java.mustache
> +    LogstashLifeCycle l = new LogstashLifeCycle(fields, new LogstashProperties());
Rename l variable

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashLifeCycleTest.java.mustache
> +    LogstashLifeCycle l = new LogstashLifeCycle(map, new LogstashProperties(), new ObjectMapper());
Rename l variable

2021-12-28 17:35 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/logging/logstash/test/LogstashLifeCycleTest.java.mustache
> +    assertThrows(IllegalStateException.class, l::serializedFields);
I'd prefer assertThatThrownBy

2021-12-28 20:49 UTC, pblanchardie commented
I'd like to squash commits before merging if you don't mind then add fix # in the message to close the issue

2021-12-28 21:03 UTC, pascalgrimaud commented
You can squash all commits if you want.
The 'fix #xxx' is needed only in the 1st comment of this pull request, no need to be in commit message :-)

2021-12-28 21:06 UTC, pblanchardie commented
> You can squash all commits if you want. The 'fix #xxx' is needed only in the 1st comment of this pull request, no need to be in commit message :-)

yep, juste figured out you were talking about the comment of PR, I was only using that in commit messages.

2021-12-28 21:09 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logstash/domain/Logstash.java
> +  public static final String LOGSTASH_LOGBACK_ENCODER_VERSION = "7.0.1";
forgot about that sry, fixing

2021-12-28 21:14 UTC, pblanchardie commented
I prefer to proceed with moving existing parts in another PR as you suggested

2021-12-30 08:40 UTC, pascalgrimaud requested changes

2021-12-30 08:40 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logstash/tcp/domain/Logstash.java
> +      .version(LOGSTASH_LOGBACK_ENCODER_VERSION)
remove the version from dependency

2021-12-30 08:40 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logstash/tcp/domain/LogstashDomainService.java
> +
missing method to add property in pom.xml.

Instead of having:

```xml
    <dependency>
      <groupId>net.logstash.logback</groupId>
      <artifactId>logstash-logback-encoder</artifactId>
      <version>7.0.1</version>
    </dependency>
```

It's better to have:

```xml
      <logstash.version>7.0.1</logstash.version>
```

```xml
    <dependency>
      <groupId>net.logstash.logback</groupId>
      <artifactId>logstash-logback-encoder</artifactId>
    </dependency>
```

2021-12-30 08:40 UTC, pascalgrimaud commented
Last comments and I think it will be ready to be merged :)

2021-12-30 09:20 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/logstash/tcp/domain/LogstashDomainService.java
> +
Sure!

2021-12-30 18:00 UTC, pascalgrimaud approved these changes

2021-12-30 18:00 UTC, merged

2022-01-01 19:19 UTC, pascalgrimaud commented
In a generated project, now we got this (Sonar Security Hotspots):

![image](https://user-images.githubusercontent.com/9156882/147858421-965c6c2f-4c1a-4c3e-86ec-c551d314d987.png)

Do you know how we can fix it?
Or should we add an ignore here?

2022-01-01 19:39 UTC, pblanchardie commented
> Do you know how we can fix it? Or should we add an ignore here?

If we want to keep custom fields (app_name & app_port), we have to programmatically inject the logger and ignore this hotspot, or find a way to do that with XML configuration (in logback-spring.xml), but I'm not sure it's feasible.

If we don't care about custom fields, we can simply rely on XML configuration and remove Java stuff, there won't be any hotspot.

Yes, it's simpler to add an ignore here.