add graal vm native image support for jhipster lite
jhipster/jhipster-lite pull request #4314
Opened 2022-11-08 16:55 UTC by atomfrede

Running following works fine now:

```
$ ./mvnw native:compile -Pnative -DskipTests
$ ./target/jhlite
```

I needed to add native hints for some of our rest classes to be correctly serialized via jackson in the native image.
The most important parts are in the common module which configures jgit and dom4j to work within the native image.

2022-11-08 17:09 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/common/infrastructure/secondary/NativeHints.java
> +      .registerType(TypeReference.of("org.dom4j.util.ProxyDocumentFactory"), MemberCategory.values())
We could use the classes directly here in fact.

2022-11-08 17:21 UTC, atomfrede commented
Will need to run local sonar from my linux machine later today

2022-11-09 10:07 UTC, atomfrede commented
@DamnClin Just to get your initial feedback regarding the hexagonal architecture. I put some of the native hint configuration into common (3rd party classes). Other configs which use e.g. some code from our modules into the respective modules. Do you consider this fine or should we structure it differently?

Regarding test coverage, what would you say how to test these native hint configurations? I think doing a unit test mocking some stuff seems quite useless (except fulfilling the coverage requirements).

2022-11-09 16:21 UTC, DamnClin commented on pom.xml
> +    <version>3.0.0-RC1</version>
versions should be kept in properties

2022-11-09 16:21 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/common/infrastructure/secondary/NativeHints.java
> +import org.dom4j.*;
Only static imports should be *

2022-11-09 16:21 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/primary/OpenApiModulesConfiguration.java
> +import org.springframework.context.annotation.*;
Only static imports should be *

2022-11-09 16:22 UTC, DamnClin commented
> Regarding test coverage, what would you say how to test these native hint configurations? I think doing a unit test mocking some stuff seems quite useless (except fulfilling the coverage requirements).

You can annotate them `@Generated`. The tests are run in the native image during build?

2022-11-09 16:35 UTC, atomfrede commented
> > Regarding test coverage, what would you say how to test these native hint configurations? I think doing a unit test mocking some stuff seems quite useless (except fulfilling the coverage requirements).
> 
> You can annotate them `@Generated`. The tests are run in the native image during build?

Right now the tests are not run in a native image/native mode.

2022-11-09 16:45 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/common/infrastructure/secondary/NativeHints.java
> +package tech.jhipster.lite.common.infrastructure.secondary;
🤦 I did that for the rest stuff and totally missed the git package. So in common only the dom4j stuff remains (if I can't find a clear place where it belongs to, maybe the maven module or so)

2022-11-09 16:46 UTC, atomfrede commented on src/main/java/tech/jhipster/lite/common/infrastructure/secondary/NativeHints.java
> +public class NativeHints implements RuntimeHintsRegistrar {
We could create a package private configuration and use it there, right now it is used in the application, but package private would be better

2022-11-09 16:47 UTC, DamnClin commented
> Right now the tests are not run in a native image/native mode.

I think it's really important to run the tests in the native image :)

2022-11-09 16:57 UTC, atomfrede commented
> > Right now the tests are not run in a native image/native mode.
> 
> I think it's really important to run the tests in the native image :)

Yes. I think we can do this in a second step as it will have a significant impact on ci build times for example

2022-11-09 20:27 UTC, atomfrede commented on pom.xml
> +    <version>3.0.0-RC1</version>
Can't use versions in parent definition

2022-11-09 20:35 UTC, atomfrede commented
I tried the native test execution. It seems cucumber is not yet compatible to native testing. So we would need to run cucumber from a normal jdk pointing to a running native image or container.

2022-11-09 20:41 UTC, atomfrede commented on pom.xml
> +    <version>3.0.0-RC1</version>
My solution, use the boot version from parent pom instead dedicated spring-boot.version property

2022-11-09 22:05 UTC, pascalgrimaud commented
Wow! Nice work here @atomfrede 
Let me think how we can test it without slowing down the full pipeline

2022-11-10 06:56 UTC, pascalgrimaud commented on pom.xml
> +    <version>3.0.0-RC1</version>
For explaination, it's related to this ticket https://github.com/jhipster/jhipster-lite/issues/579

2022-11-10 07:22 UTC, atomfrede commented on pom.xml
> +    <version>3.0.0-RC1</version>
Didn't know that issue. Changed it to use the parent to have the native build configurations "out of box"

2022-11-10 07:37 UTC, pascalgrimaud commented on pom.xml
> +    <version>3.0.0-RC1</version>
Yes, let's use parent like spring initializr

2022-11-11 08:05 UTC, atomfrede commented on pom.xml
> +    <version>3.0.0-RC1</version>
```suggestion
    <version>3.0.0-RC2</version>
```

2022-11-11 09:37 UTC, pascalgrimaud commented
Sorry, I upgraded the main branch, so you have some conflict here :p

2022-11-11 09:48 UTC, atomfrede commented
No problem.

2022-11-11 15:25 UTC, pascalgrimaud commented
I tried to follow the README to build a Docker image and it doesn't work:

```
./mvnw spring-boot:build-image -Pnative -DskipTests
```

```
[INFO] --- spring-boot-maven-plugin:3.0.0-RC2:build-image (default-cli) @ jhlite ---
[INFO] Building image 'docker.io/library/jhlite:0.22.1-SNAPSHOT'
[INFO] 
[INFO]  > Pulling builder image 'docker.io/paketobuildpacks/builder:tiny' 100%
[INFO]  > Pulled builder image 'paketobuildpacks/builder@sha256:84a20510c7c991e168019cf2d2e47fda07e44de40084fc3bd7edb740aeb35e31'
[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:tiny-cnb' 100%
[INFO]  > Pulled run image 'paketobuildpacks/run@sha256:cedde05847df71cf85b035edaece87436f73c72d934914cccaffc469d57d544b'
[INFO]  > Pulling buildpack image 'gcr.io/paketo-buildpacks/bellsoft-liberica:9.9.0-ea' 100%
[INFO]  > Pulled buildpack image 'gcr.io/paketo-buildpacks/bellsoft-liberica@sha256:32e69e3fcc17725ed8a7bddd9d2881a0f1019354a0e653521dac55898c0e8c36'
[INFO]  > Pulling buildpack image 'gcr.io/paketo-buildpacks/java-native-image:latest' 0%
[INFO]  > Pulling buildpack image 'gcr.io/paketo-buildpacks/java-native-image:latest' 23%
[INFO]  > Pulling buildpack image 'gcr.io/paketo-buildpacks/java-native-image:latest' 32%
[INFO]  > Pulling buildpack image 'gcr.io/paketo-buildpacks/java-native-image:latest' 39%
[INFO]  > Pulling buildpack image 'gcr.io/paketo-buildpacks/java-native-image:latest' 40%
[INFO]  > Pulling buildpack image 'gcr.io/paketo-buildpacks/java-native-image:latest' 100%
[INFO]  > Pulled buildpack image 'gcr.io/paketo-buildpacks/java-native-image@sha256:6347a2a1fb05c4fa0767e702246e0d04ff5cc8fd0d80fb445ebd6f7cbe395537'
[INFO]  > Executing lifecycle version v0.15.1
[INFO]  > Using build cache volume 'pack-cache-cbca7a44d7ec.build'
[INFO] 
[INFO]  > Running creator
[INFO]     [creator]     ===> ANALYZING
[INFO]     [creator]     Previous image with name "docker.io/library/jhlite:0.22.1-SNAPSHOT" not found
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     6 of 14 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 9.9.0-ea
[INFO]     [creator]     paketo-buildpacks/ca-certificates   3.4.0
[INFO]     [creator]     paketo-buildpacks/syft              1.22.1
[INFO]     [creator]     paketo-buildpacks/executable-jar    6.5.0
[INFO]     [creator]     paketo-buildpacks/spring-boot       5.20.0
[INFO]     [creator]     paketo-buildpacks/native-image      5.6.0
[INFO]     [creator]     ===> RESTORING
[INFO]     [creator]     ===> BUILDING
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for BellSoft Liberica 9.9.0-ea
[INFO]     [creator]       https://github.com/paketo-buildpacks/bellsoft-liberica
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_JVM_JLINK_ARGS           --no-man-pages --no-header-files --strip-debug --compress=1  configure custom link arguments (--output must be omitted)
[INFO]     [creator]         $BP_JVM_JLINK_ENABLED        false                                                        enables running jlink tool to generate custom JRE
[INFO]     [creator]         $BP_JVM_TYPE                 JRE                                                          the JVM type - JDK or JRE
[INFO]     [creator]         $BP_JVM_VERSION              11                                                           the Java version
[INFO]     [creator]       Launch Configuration:
[INFO]     [creator]         $BPL_DEBUG_ENABLED           false                                                        enables Java remote debugging support
[INFO]     [creator]         $BPL_DEBUG_PORT              8000                                                         configure the remote debugging port
[INFO]     [creator]         $BPL_DEBUG_SUSPEND           false                                                        configure whether to suspend execution until a debugger has attached
[INFO]     [creator]         $BPL_HEAP_DUMP_PATH                                                                       write heap dumps on error to this path
[INFO]     [creator]         $BPL_JAVA_NMT_ENABLED        true                                                         enables Java Native Memory Tracking (NMT)
[INFO]     [creator]         $BPL_JAVA_NMT_LEVEL          summary                                                      configure level of NMT, summary or detail
[INFO]     [creator]         $BPL_JFR_ARGS                                                                             configure custom Java Flight Recording (JFR) arguments
[INFO]     [creator]         $BPL_JFR_ENABLED             false                                                        enables Java Flight Recording (JFR)
[INFO]     [creator]         $BPL_JMX_ENABLED             false                                                        enables Java Management Extensions (JMX)
[INFO]     [creator]         $BPL_JMX_PORT                5000                                                         configure the JMX port
[INFO]     [creator]         $BPL_JVM_HEAD_ROOM           0                                                            the headroom in memory calculation
[INFO]     [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes                                               the number of loaded classes in memory calculation
[INFO]     [creator]         $BPL_JVM_THREAD_COUNT        250                                                          the number of threads in memory calculation
[INFO]     [creator]         $JAVA_TOOL_OPTIONS                                                                        the JVM launch flags
[INFO]     [creator]         Using Java version 17 extracted from MANIFEST.MF
[INFO]     [creator]       BellSoft Liberica NIK 17.0.5: Contributing to layer
[INFO]     [creator]         Downloading from https://download.bell-sw.com/vm/22.3.0/bellsoft-liberica-vm-core-openjdk17.0.5+8-22.3.0+1-ea-linux-amd64.tar.gz
[INFO]     [creator]         Verifying checksum
[INFO]     [creator]         Expanding to /layers/paketo-buildpacks_bellsoft-liberica/native-image-svm
[INFO]     [creator]         Adding 127 container CA certificates to JVM truststore
[INFO]     [creator]         Writing env.build/JAVA_HOME.override
[INFO]     [creator]         Writing env.build/JDK_HOME.override
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for CA Certificates 3.4.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/ca-certificates
[INFO]     [creator]       Launch Helper: Contributing to layer
[INFO]     [creator]         Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for Syft 1.22.1
[INFO]     [creator]       https://github.com/paketo-buildpacks/syft
[INFO]     [creator]         Downloading from https://github.com/anchore/syft/releases/download/v0.60.3/syft_0.60.3_linux_amd64.tar.gz
[INFO]     [creator]         Verifying checksum
[INFO]     [creator]         Writing env.build/SYFT_CHECK_FOR_APP_UPDATE.default
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for Executable JAR 6.5.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/executable-jar
[INFO]     [creator]       Class Path: Contributing to layer
[INFO]     [creator]         Writing env.build/CLASSPATH.delim
[INFO]     [creator]         Writing env.build/CLASSPATH.prepend
[INFO]     [creator]     
[INFO]     [creator]     Paketo Buildpack for Spring Boot 5.20.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/spring-boot
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_SPRING_CLOUD_BINDINGS_DISABLED   false  whether to contribute Spring Boot cloud bindings support
[INFO]     [creator]       Launch Configuration:
[INFO]     [creator]         $BPL_SPRING_CLOUD_BINDINGS_DISABLED  false  whether to auto-configure Spring Boot environment properties fro [...]

2022-11-11 15:31 UTC, atomfrede commented
Let me check. I always tested the native executable created with `./mvnw native:compile -Pnative -DskipTests`. But I am pretty sure I also build the image at least once.

2022-11-11 16:18 UTC, atomfrede commented
Same for me. I checked the minimal app from spring initializer and it worked. Will do some investigations.

2022-11-12 06:56 UTC, atomfrede commented
I think I have found the issue. Need to do some more testing and building the image later.

2022-11-12 17:20 UTC, atomfrede commented
@pascalgrimaud Can you try again? It took some time as the build took too long on the macs and on my linux workstation the frontend build didn't work. I tried both the native image and the native executable, both work fine.

2022-11-12 23:06 UTC, pascalgrimaud commented
Thanks @atomfrede : I'll try it tomorrow and if it's ok, we're ready for this awesome release

2022-11-13 08:05 UTC, pascalgrimaud requested changes

2022-11-13 08:05 UTC, pascalgrimaud commented on README.md
> +docker run --rm docker.io/library/jhlite:<VERSION>
```suggestion
docker run -p 7471:7471 --rm docker.io/library/jhlite:<VERSION>
```

2022-11-13 11:50 UTC, pascalgrimaud approved these changes

2022-11-13 12:08 UTC, merged

2022-11-13 16:10 UTC, atomfrede commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/107436

2022-11-13 16:24 UTC, pascalgrimaud commented
@atomfrede : approved