Spring Boot: Spring Cloud Consul
jhipster/jhipster-lite pull request #435
Opened 2021-12-30 02:38 UTC by pblanchardie

fixes #281 

- [x] Consul bootstrap, config and discovery base
- [ ] BuildTool: generate a Maven dependencyManagement section (needed for Spring Cloud)
- [ ] Add Spring Cloud Common for dependency management?
- [ ] Add more Consul properties
- [ ] Do not force config in fast profile
- [ ] Split consul-config and consul-discovery so they can be used separately or is it a non-sense?

2021-12-30 05:45 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/infrastructure/primary/rest/ConsulResource.java
> +@RequestMapping("/api/servers/spring-boot/cloud/consul")
We can keep `cloud` for public clouds (azure,gcp,aws) and use spring-cloud here `/api/servers/spring-boot/spring-cloud/consul`?

2021-12-30 08:31 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/infrastructure/primary/rest/ConsulResource.java
> +@RequestMapping("/api/servers/spring-boot/cloud/consul")
Done.

2021-12-31 21:43 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/ConsulDomainService.java
> +    result.put("spring.cloud.consul.discovery.tags[1]", "context-path=\\$\\{server.servlet.context-path:\\}");
taken from JHipster generator but not tested

2022-01-01 19:13 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String NEEDLE_BOOTSTRAP_TEST_PROPERTIES = "# jhipster-needle-bootstrap-test-properties";
As these are generic (also needed for eureka and config-server), these can be used from `SpringBootPropertiesApplicationService` (moved this in #457)

2022-01-01 19:25 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String NEEDLE_BOOTSTRAP_TEST_PROPERTIES = "# jhipster-needle-bootstrap-test-properties";
not sure about needle for bootstrap. Look at https://github.com/jhipster/jhipster-sample-app-microservice/blob/main/src/main/resources/config/bootstrap.yml

There is no needle here and I don't think we need its

2022-01-01 19:34 UTC, pascalgrimaud requested changes

2022-01-01 19:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String BOOTSTRAP_FAST_PROPERTIES = "bootstrap-fast.properties";
no need fast profile here

2022-01-01 19:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/ConsulDomainService.java
> +import static tech.jhipster.lite.generator.server.springboot.core.domain.SpringBootDomainService.CONFIG_FOLDER;
strange: this import should not be possible with HegaxonalArchTest as springboot.core is a BusinessContext

Then, maybe I would suggest to move CONFIG_FOLDER to Constants ?

2022-01-01 19:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/ConsulDomainService.java
> +    projectRepository.template(project, getPath(SOURCE, "src"), "bootstrap-fast.properties", getPath(MAIN_RESOURCES, CONFIG_FOLDER));
no need

2022-01-01 19:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/ConsulDomainService.java
> +    addProperty(
no need this as comment above. We should use bootstrap.properties.mustache and generate it like this

2022-01-01 20:24 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String BOOTSTRAP_FAST_PROPERTIES = "bootstrap-fast.properties";
I found it very convenient to be able to disable Consul during development.
Can you elaborate?

2022-01-01 20:26 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/ConsulDomainService.java
> +import static tech.jhipster.lite.generator.server.springboot.core.domain.SpringBootDomainService.CONFIG_FOLDER;
yes, didn't notice, I thought I was importing SpringBootCommonDomainService which is a shared kernel.
up to you if we move that to Constants or SpringBootCommonDomainService or other.

2022-01-01 20:31 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String NEEDLE_BOOTSTRAP_TEST_PROPERTIES = "# jhipster-needle-bootstrap-test-properties";
ho yes we should get rid of these needles, it will be simpler if everything is in the mustache template as I don't think we'll add anything in bootstrap properties in other contexts.

2022-01-01 20:32 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/ConsulDomainService.java
> +    addProperty(
absolutely

2022-01-01 22:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String BOOTSTRAP_FAST_PROPERTIES = "bootstrap-fast.properties";
If during development, you don't use consul, you won't see other microservices. So when you start your microservice1, you won't be able to communicate with microservice2

So you always need consul when you start you app.

Don't hesitate to tell me if I'm not clear enough

2022-01-01 22:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/ConsulDomainService.java
> +import static tech.jhipster.lite.generator.server.springboot.core.domain.SpringBootDomainService.CONFIG_FOLDER;
Constant like other MAIN and RESOURCES etc would be enough

2022-01-02 09:35 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String BOOTSTRAP_FAST_PROPERTIES = "bootstrap-fast.properties";
The problem is especially with config, not discovery.

During local development, it can be convenient to allow starting the app without Consul Config, and that was allowed by the `failFast` property that you'll probably prefer and which was in generator-jhipster.
https://cloud.spring.io/spring-cloud-consul/reference/html/#spring-cloud-consul-failfast

The difference is that Consul will still be enabled during local dev, but if it's not available for configuration, you'll still be able to start your app. If it's available, it will be used. I understand that it's a better choice.

2022-01-02 09:37 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String BOOTSTRAP_FAST_PROPERTIES = "bootstrap-fast.properties";
Oh I see. Then let's give it a try, and I'll test it on my real projects :)

2022-01-02 10:32 UTC, pblanchardie commented on src/main/java/tech/jhipster/lite/generator/server/springboot/consul/domain/Consul.java
> +  public static final String BOOTSTRAP_FAST_PROPERTIES = "bootstrap-fast.properties";
done, only for config.

2022-01-02 22:02 UTC, pascalgrimaud commented
so it looks ready, I'll review it tomorrow @pblanchardie

2022-01-03 12:30 UTC, pascalgrimaud commented
Just gave a quick try:

![image](https://user-images.githubusercontent.com/9156882/147930677-b3f9077a-7811-4e52-8455-bbe7d139e7c4.png)

2022-01-03 12:38 UTC, pascalgrimaud commented
One issue I saw, is the indentation, which should be fixed in another PR than this one:

![image](https://user-images.githubusercontent.com/9156882/147931366-f4adbd00-ae15-432c-b502-37cdbe34df2f.png)

2022-01-03 12:45 UTC, pascalgrimaud commented
Missing this folder `src/main/docker/central-server-config/` with a `application.properties` file

This file can contain: 

```
configserver.name=Docker Consul Service
configserver.status=Connected to Consul Server running in Docker
``

Then, these information can be displayed when starting the app maybe ?

```java
        String configServerStatus = env.getProperty("configserver.status");
        if (configServerStatus == null) {
            configServerStatus = "Not found or not setup for this application";
        }
        log.info(
            "\n----------------------------------------------------------\n\t" +
            "Config Server: \t{}\n----------------------------------------------------------",
            configServerStatus
        );
```

2022-01-03 13:03 UTC, pblanchardie commented
> One issue I saw, is the indentation, which should be fixed in another PR than this one:

Yes, seen this indentation problem. 

> Missing this folder src/main/docker/central-server-config/ with a application.properties file

Soit's just to be sure that config works?
Is `configserver.name` used somewhere?

2022-01-03 13:11 UTC, pascalgrimaud commented
For indentation, the fix could be similar to https://github.com/jhipster/jhipster-lite/pull/412/files -> but I'm not sure

`configserver.name` is only used to be sure that the application pull the config from Consul.
See https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/docker/config/consul-config/application.yml.ejs#L19-L21

2022-01-04 03:46 UTC, pblanchardie commented
> For indentation, the fix could be similar to https://github.com/jhipster/jhipster-lite/pull/412/files -> but I'm not sure

see #478

2022-01-04 20:32 UTC, pascalgrimaud approved these changes

2022-01-04 20:32 UTC, merged