Project banner module
jhipster/jhipster-lite pull request #4560
Opened 2022-12-02 16:44 UTC by MrMattam

- fix #3049

First version of banner generated from project name (truncated to 17chars if too long).

It could eventually be improved:

* by taking content from a dedicated module parameter.

* by building the banner from another acsii generator : for example using this [API](https://devops.datenkollektiv.de/banner.txt/index.html) or this [maven plugin](https://github.com/acanda/spring-banner-plugin) or any standard library (if found).

![image](https://user-images.githubusercontent.com/9273290/205342017-18a9e952-0453-416d-98d2-786f10eefc9e.png)

2022-12-02 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=4560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=4560) before we can accept your contribution.<br/><hr/>**Matthieu BONNOT** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=4560) it.</sub>

2022-12-02 17:00 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/banner/domain/AsciiArtGenerator.java
> +  private static BufferedImage buildImageFor(String text) {
I'm surprised that nothing here needs to be closed (haven't check, just found that strange)

2022-12-02 17:00 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/banner/domain/AsciiArtGenerator.java
> +  private static final String NO_COLORED_PIXEL = " ";
Is it a `BLANK_PIXEL` ?

2022-12-02 17:00 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/generator/server/springboot/banner/infrastructure/primary/BannerModuleConfiguration.java
> +      .organization(JHipsterModuleOrganization.builder().addDependency(SPRING_BOOT).build())
There's a shortcut spring boot dependency for that

2022-12-05 08:22 UTC, pascalgrimaud requested changes

2022-12-05 08:22 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/JHLiteModuleSlug.java
> -  BANNER_JHIPSTER_V7_VUE("banner-jhipster-v7-vue"),
I don't think these banners should be deleted, as it's easy to use and to have in existing project

2022-12-30 07:59 UTC, hdurix commented on src/main/java/tech/jhipster/lite/generator/JHLiteModuleSlug.java
> -  BANNER_JHIPSTER_V7_VUE("banner-jhipster-v7-vue"),
They can't be used right now (at least by default) as they are hidden in properties.

Do we need all of them? They take a lot of places on landscape view and I am not sure anyone will ever use JHipster v2 banner in their project :)

Should we keep only one like V7 named `JHipster` and the custom one? What do you think?

2022-12-30 08:01 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/JHLiteModuleSlug.java
> -  BANNER_JHIPSTER_V7_VUE("banner-jhipster-v7-vue"),
It can be hidden using spring properties, or simply deleted too
And yes you're right, just need to keep 1 as example

2024-03-15 09:49 UTC, pascalgrimaud commented
opened for too long, let's close this and discuss if needed

2024-03-15 09:49 UTC, closed without merging