Add config server
jhipster/jhipster-lite pull request #457
Opened 2022-01-01 17:25 UTC by swarajsaaj

2022-01-02 22:15 UTC, pascalgrimaud commented
@swarajsaaj : is it ready for review?

2022-01-03 02:24 UTC, swarajsaaj commented
@pascalgrimaud : yes it's ready for review.

2022-01-03 19:10 UTC, pascalgrimaud requested changes

2022-01-03 21:29 UTC, pascalgrimaud commented
Manually tested and it works well :)

![image](https://user-images.githubusercontent.com/9156882/147982335-1b7eeba3-ab3a-4c1b-aa7c-87640f4f4ed9.png)

2022-01-03 21:57 UTC, pascalgrimaud requested changes

2022-01-03 21:57 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/common/domain/Base64Utils.java
> +    return getBase64Secret(value, 50);
need to increase this value, otherwise, you can't log to JHipster Registry. I don't know which value should be used. I tried to 100 and it works.

```
jhipster-registry_1  | 2022-01-03 21:42:28.400 ERROR 1 --- [  XNIO-1 task-2] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
jhipster-registry_1  | 
jhipster-registry_1  | io.jsonwebtoken.security.WeakKeyException: The signing key's size is 400 bits which is not secure enough for the HS512 algorithm.  The JWT JWA Specification (RFC 7518, Section 3.2) states that keys used with HS512 MUST have a size >= 512 bits (the key size must be greater than or equal to the hash output size).  Consider using the io.jsonwebtoken.security.Keys class's 'secretKeyFor(SignatureAlgorithm.HS512)' method to create a key guaranteed to be secure enough for HS512.  See https://tools.ietf.org/html/rfc7518#section-3.2 for more information.
jhipster-registry_1  | 	at io.jsonwebtoken.SignatureAlgorithm.assertValid(SignatureAlgorithm.java:387)
jhipster-registry_1  | 	at io.jsonwebtoken.SignatureAlgorithm.assertValidSigningKey(SignatureAlgorithm.java:315)
jhipster-registry_1  | 	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:122)
jhipster-registry_1  | 	at tech.jhipster.registry.security.jwt.TokenProvider.createToken(TokenProvider.java:72)
jhipster-registry_1  | 	at tech.jhipster.registry.web.rest.UserJWTController.authorize(UserJWTController.java:42)
jhipster-registry_1  | 	at tech.jhipster.registry.web.rest.UserJWTController$$FastClassBySpringCGLIB$$dbfa9546.invoke(<generated>)
jhipster-registry_1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

2022-01-03 21:57 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/configclient/domain/SpringCloudConfig.java
> +  private static final String JHIPSTER_REGISTRY_PASSWORD = "admin";
Security issue with Sonar here:

![image](https://user-images.githubusercontent.com/9156882/147983764-54cfd715-df8d-459c-bc04-cea488f8d0c4.png)

2022-01-03 21:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/springcloud/configclient/src/bootstrap-fast.properties.mustache
> +spring.cloud.config.profile=dev
no need profile here, as dev/prod have been removed

2022-01-03 21:57 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/springcloud/configclient/src/bootstrap.properties.mustache
> +spring.cloud.config.profile=prod
no need profile here, as dev/prod have been removed

2022-01-03 21:57 UTC, pascalgrimaud commented on src/test/resources/generator/server/springboot/springcloud/bootstrap.src.fast.properties
> +#====================================================================
do you need this file ? as no need needle anymore

2022-01-03 21:57 UTC, pascalgrimaud commented on src/test/resources/generator/server/springboot/springcloud/bootstrap.src.properties
> +#====================================================================
do you need this file ? as no need needle anymore

2022-01-03 21:57 UTC, pascalgrimaud commented on src/test/resources/generator/server/springboot/springcloud/bootstrap.test.properties
> +#====================================================================
do you need this file ? as no need needle anymore

2022-01-03 21:57 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot/banner/jhipster-v7"
to reduce the test in CI, no need

2022-01-03 21:57 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/sonar"
to reduce the test in CI, no need

2022-01-03 21:58 UTC, pascalgrimaud commented
some code smells too:

![image](https://user-images.githubusercontent.com/9156882/147984910-c804359a-10a5-4af4-b902-ae163c868f0d.png)


![image](https://user-images.githubusercontent.com/9156882/147984886-36816d30-72ea-42ab-9934-e2f0d2750b89.png)

2022-01-04 12:58 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/package-info.java
> +package tech.jhipster.lite.generator.server.springboot.springcloud.consul;
I added three package for eureka, consul and config-client in `springboot/sprinbcloud` package for setitng up the structure. I can remove consul as its being done in another PR

2022-01-04 13:05 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/package-info.java
> +package tech.jhipster.lite.generator.server.springboot.springcloud.consul;
Oh I see. So I'm fine. Hope it won't conflict with the other PR :)

2022-01-04 13:22 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/common/domain/Base64Utils.java
> +    return getBase64Secret(value, 50);
Ah, requires minimum of 512 bits, so it should be 64, will update, thanks for noticing.

2022-01-04 15:25 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/configclient/domain/SpringCloudConfig.java
> +  private static final String JHIPSTER_REGISTRY_PASSWORD = "admin";
Well it has to be kept in Sourcecode for simplicity, will move to template like in `generator-jhipster`

2022-01-04 16:01 UTC, pascalgrimaud commented
Thanks @swarajsaaj : I'll have a 2nd look :)

2022-01-04 18:21 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/consul/package-info.java
> +package tech.jhipster.lite.generator.server.springboot.springcloud.consul;
I removed the consul package just to avoid any conflicts :)

2022-01-04 20:39 UTC, pascalgrimaud commented
I'm resolving the merge conflict with GitHub, so I'm reviewing it now

2022-01-04 20:50 UTC, pascalgrimaud approved these changes

2022-01-04 20:57 UTC, merged

2022-01-08 17:04 UTC, swarajsaaj commented
bounty claimed at https://opencollective.com/generator-jhipster/expenses/60636

2022-01-08 18:01 UTC, pascalgrimaud commented
@swarajsaaj : approved