Add springboot user
jhipster/jhipster-lite pull request #496
Opened 2022-01-06 22:09 UTC by MSaguer

To close #426 

[/] First working instance after user generation
[ ] Refactor of generated : temporary generated package
[ ] Refactor of generation code : package modification ? Separate the generation in many end points
[ ] Add tests in generator
[ ] Add tests in generated project

2022-01-08 10:17 UTC, MSaguer commented
Hi @pascalgrimaud 
Here is a first shot of generated files in tech.jhipster.beer.technical.infrastructure.secondary.user package
![image](https://user-images.githubusercontent.com/42449441/148640290-ed65099a-a61c-408f-bf6b-86e5e778d008.png)

Is it the right target package or do it need to be moved?

Same question on generation files. I've created source files in new tech.jhipster.lite.generator.server.springboot.user package.

Last question on required end points. For the moment, I have only one end point /api/servers/spring-boot/user/init that creates both user and authority files. I could split it in /api/servers/spring-boot/user/init and /api/servers/spring-boot/user/authority but they are not fully independant. The second one would require the first one to work.

Nota : I've seen that an Arch test is failling. I'll fix it when the target package will be defined.

2022-01-08 11:34 UTC, pascalgrimaud commented
The target should be to have a specific user context, so a dedicated folder `user`, so it could be:

![image](https://user-images.githubusercontent.com/9156882/148642547-c39c9dee-6245-4bdb-8d47-09591abb823e.png)

Another solution would be to add secondary/postgresql, in case of you have different database in your architecture:

![image](https://user-images.githubusercontent.com/9156882/148642581-edbb94d9-7f8b-4920-b99b-3a555d80651e.png)

2022-01-08 11:34 UTC, pascalgrimaud commented
For this PR, you can ignore primary, application and domain, as it will be done in another PR

2022-01-08 13:56 UTC, MSaguer commented
The second option seems good for me.

when reading [User.java.ejs](https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/domain/User.java.ejs), I can see that user class is the same for all slq database (using databaseTypeSql variable).
What do you think to replace postgresql package by sqldatabase or something like that?

2022-01-08 14:45 UTC, pascalgrimaud commented
So maybe just 'sql' ?

2022-01-08 16:28 UTC, MSaguer commented
Forget my last remark. It takes me a long time to fully understand what you said. I agree now it could be usefull to be able to generate user entities for many different databases.
So I change my end point into "/api/servers/spring-boot/user/postgresql" that calls the following services 

```
    springBootUserApplicationService.addSqlJavaUsers(project, sqlDatabaseName);
    springBootUserApplicationService.addSqlJavaAuthority(project, sqlDatabaseName);
    springBootUserApplicationService.addSqlJavaAuditEntity(project, sqlDatabaseName);
    springBootUserApplicationService.addSqlLiquibaseConfiguration(project, sqlDatabaseName);
```

Should be simplier to add more service for different databases.

2022-01-08 22:14 UTC, pascalgrimaud commented
Mhhh let me think, but I don't think liquibase should be part of this PR.
Imagine the user don't use liquibase but flyway, or nothing. So we should not include the liquibase part, in this PR.

IMO, creating user.xml and authority.xml can be done in another PR and should be in liquibase context, not in this one.

What do you think?

Later, at the end of this workflow, we could publish a spring event, and a database migration context can consume this event, and create liquibase diff or flyway diff, according to the project config. It's just an idea so I'm not sure about this

2022-01-09 15:58 UTC, MSaguer commented
user.xml and autority.xml are bounded to both user and liquibase services. That's why I planned to have a separated end point to let user decides or not if this should be generated.
I don't mind hosting this generation in liquibase or in user package.

I understand that liquibase:diff cmd could be the future target stragegy for changelog generation? If so, Is it still usefull to keep the xml generation I created ? 
Do you want me to move this to the liquibase package and to propose it in an other PR?

2022-01-09 16:26 UTC, pascalgrimaud commented
No, I don't think liquibase:diff will be used by JHipster Lite to generate changelog. It depends too much on external services (database, base code etc), so it's not a good idea. The end-user will use it if he/she wants.

About this PR.
You can keep user.xml and authority.xml in this pull request, no need to do it in another PR if it's simpler for you.

I wanted to point it because of this change:
![image](https://user-images.githubusercontent.com/9156882/148691061-6ea1692d-0b25-4752-8df0-c08997e87771.png)

Liquibase should stay as BusinessContext, it's not a shared kernel.
It means:
- user.xml / authority.xml should be in liquibase context
- methods which add these 2 files should be in liquibase context too
- user context should not call liquibase

Don't hesitate if I'm not clear enough. My english is really good.
Or send private message on Twitter ;)

2022-01-10 21:47 UTC, pascalgrimaud commented
Just a comment, according to your last commits.
In my opinion, it's important to have `Entity` suffix, like UserEntity or AuthorityEntity, used in secondary -> your commits are good :-)

So User and Authority can be used in domain, which more important

That's one of reason why, when using generator-jhipster, I try to add Entity suffix.

2022-01-16 15:20 UTC, pascalgrimaud commented
Thanks a lot @MSaguer : it's a huge work but it is needed. I'll review it soon !

2022-01-17 08:11 UTC, pascalgrimaud requested changes

2022-01-17 08:11 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseDomainService.java
> +    projectRepository.add(project, getPath(SOURCE, "resources"), "date_time_wrapper.xml", getPath(MAIN_RESOURCES, CHANGELOG));
not sure it should be added by default:

- sequence -> not needed by MySQL https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs#L28-L32
- date_time_wrapper -> https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs#L167-L180

This was added for https://github.com/jhipster/jhipster-sample-app/tree/5a3ca402497db3b4e9b88f4186b4183e364d02ba/src/test/java/io/github/jhipster/sample/repository/timezone but I'm not sure it is needed by default when adding liquibase

2022-01-17 08:11 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/user/sqldatabase/AuthorityRepository.java.mustache
> + * Spring Data JPA repository for the {@link Authority} entity.
```suggestion
 * Spring Data JPA repository for the {@link AuthorityEntity} entity.
```

2022-01-17 08:11 UTC, pascalgrimaud commented
Very good job @MSaguer ! I tested and it seems to work very well.
I have a few comments, specially about date_time_wrapper -> opened to discuss about it :)

2022-01-17 21:39 UTC, MSaguer commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/application/LiquibaseApplicationService.java
> +  public void addSqlUserChangelog(Project project, String sqlDabaseName) {
Global modification to user DatabaseType instead of string

2022-01-17 21:40 UTC, MSaguer commented on src/main/java/tech/jhipster/lite/generator/server/springboot/user/domain/SpringBootUserDomainService.java
> +    project.addConfig(USER_DATABASE_KEY, sqlDatabaseName);
Use id field instead of name that is already defined in Enumerate class

2022-01-17 21:40 UTC, MSaguer commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseDomainService.java
> +    projectRepository.add(project, getPath(SOURCE, "resources"), "date_time_wrapper.xml", getPath(MAIN_RESOURCES, CHANGELOG));
Remove these files

2022-01-17 21:41 UTC, MSaguer commented on src/main/resources/generator/server/springboot/user/sqldatabase/UserConstants.java.mustache
> +package {{packageName}}.user.infrastructure.secondary.{{sqlDatabaseName}};
New package generated

2022-01-17 21:41 UTC, MSaguer commented on src/main/resources/generator/server/springboot/user/sqldatabase/UserEntity.java.mustache
> +@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
Remove all cache options

2022-01-17 21:51 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseDomainService.java
> -    projectRepository.add(project, getPath(SOURCE, "resources"), "sequence.xml", getPath(MAIN_RESOURCES, CHANGELOG));
I was not sure about my last comment or maybe I was not clear enough.

When using liquibase + init, we don't need a sequence.
But when adding User with PostgreSQL, we need a sequence, as the UserEntity needs a sequence.
So maybe, we should add a sequence in User.xml and use a specific name to this sequence (instead of a global one): sequence_jhi_user for example.

What do you think?

2022-01-18 19:10 UTC, MSaguer commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseDomainService.java
> -    projectRepository.add(project, getPath(SOURCE, "resources"), "sequence.xml", getPath(MAIN_RESOURCES, CHANGELOG));
You're right. My cut was a little rough yesterday :)

I see two solutions here
- Add new service LiquibaseApplicationService.addSequenceGenerator(Project, DatabaseType) that could be called in user/postgresql. This would create a global sequence that could be used by all generated entities.
That's what is done in current jhipster generator
- Add the sequence definition in the user.xml file that would be specific to the user entity. Then each entity should define its own sequence.
I think I remember that jhipster generator firstly used a dedicated sequence for each generated entity.

I personnaly prefer the second solution (the one you proposed) just because data are strictly separated. One entity = one sequence.
The benefit of the first option would be to avoid mistakes when switching by error two different table fk.
Just for my informatin, was it the rationale for the generator modification or is there anything else?

to resume the fix, just to be sure :)
- date_time_wrapper is not needed and should stayed deleted
- specific sequence generator is declared in user.xml file

2022-01-18 19:19 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseDomainService.java
> -    projectRepository.add(project, getPath(SOURCE, "resources"), "sequence.xml", getPath(MAIN_RESOURCES, CHANGELOG));
Agree with your resume! Let's try separate sequence, linked to each entity

2022-01-22 16:17 UTC, pascalgrimaud commented
Thanks, will do the final review soon :-)

2022-01-22 22:21 UTC, pascalgrimaud approved these changes

2022-01-22 22:21 UTC, pascalgrimaud commented
Very good job @MSaguer 
There are still have some minor fix, but let's merge it first and do some minor PRs to fix it

2022-01-22 22:21 UTC, merged

2022-01-23 17:37 UTC, MSaguer commented
thanks @pascalgrimaud for having fixed the latest problems and for the bounty.
I've created the request https://opencollective.com/generator-jhipster/expenses/61903

2022-01-23 17:39 UTC, pascalgrimaud commented
@MSaguer : approved. Thanks for your hard work :)