jhlite custom: ignore all children of a parent module
jhipster/jhipster-lite pull request #5352
Opened 2023-02-13 16:41 UTC by renanfranca

Fix #4338

2023-02-13 16:44 UTC, renanfranca commented
I implemented the first request:
> keep current property, and improve the behavior to exclude this module and all dependant module

The second request, I add a comment at the properties `jhlite-hidden-resources.slugs` and increment the documentation:
> maybe, display the excluded modules at start, to avoid "silent" exclusions

@pascalgrimaud, could you tell me where do you want to display the hidden modules?

2023-02-14 06:40 UTC, pascalgrimaud commented
@renanfranca : maybe in the logs at startup, would be enough

2023-02-14 06:42 UTC, DamnClin requested changes

2023-02-14 06:42 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterHiddenResourcesProperties.java
> +    addNestedDependenciesBySlugs(modulesResources);
This can't be done here, the hidden modules logic must be moved in domain to make this calculation

2023-02-14 15:51 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/JHipsterHiddenResourcesProperties.java
> +    addNestedDependenciesBySlugs(modulesResources);
Thank you @DamnClin for pointing this out 😃 ! I pushed a new version to be reviewed 👍

2023-02-14 15:52 UTC, renanfranca commented
> @renanfranca : maybe in the logs at startup, would be enough

Thank you @pascalgrimaud , I ll try to do it 👍

2023-02-14 15:56 UTC, renanfranca commented
Hello @DamnClin,

This jhispter lite custom module impressed me!!! It actually runs the original jhipister lite project (backend and frontend) only by importing it as a dependency with maven!

That makes me so curious that I've been studying it, I learn how to do it using a classifier tag  (here is the article: https://medium.com/publicis-sapient-france/import-spring-boot-application-as-a-maven-dependency-a25e03e5c3a ). But I didn't know how the hipster lite did it, there wasn't any classifier tag...

What I want to do is to generate an application using jhlite module and it could be able to run with my changes which weren't merged yet.

if you could point me in the right direction, I appreciated it 😄

2023-02-14 17:38 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenResources.java
> +public class JHipsterHiddenResources {
Without looking too much at it I think it would be easier to update `JHipsterModulesResources` to take a `JHipsterHiddenModules` in constructor with `JHipsterHiddenModules` containing slugs and tags. This way we can build modules with hidden ones easily

2023-02-14 17:40 UTC, DamnClin commented
> What I want to do is to generate an application using jhlite module and it could be able to run with my changes which weren't merged yet.

* mvn install on your branch on JHipsterLite
* Generate an app with custom JHlite
* Update JHlite version in your generated app to use the snapshot one you just built

Haven't tried it now but I think I remember doing it when working on that feature

2023-02-14 20:17 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenResources.java
> +public class JHipsterHiddenResources {
Thank you for the fast response @DamnClin,
I am not so sure if I understand what you want me to do this time. So I implemented what I think I understand and I didn't rebase this time, I pushed a new commit to be easier to talk about the change and to undo it if I did all wrong 😅 .

2023-02-14 20:23 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenResources.java
> +public class JHipsterHiddenResources {
The idea is to update [JHipsterModulesResources](https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java): the class responsible of resources management to build it with the hidden resources and let it do the filtering logic (getting nested modules etc).

Your current `JHipsterHiddenResources` needs a collection of `JHipsterModuleResource` which is, in fact, a `JHipsterModulesResources` so I think it will be easier to do this filtering in `JHipsterModuleResource` or in [JHipsterLandscape](https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/module/domain/landscape/JHipsterLandscape.java) which is the next step, the one knowing the dependencies

2023-02-15 06:55 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenResources.java
> +public class JHipsterHiddenResources {
Aftertought: can't be in Landscape since we also want to hide them in patch, must be in `JHipsterHiddenResources`

2023-02-15 19:19 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenResources.java
> +public class JHipsterHiddenResources {
No new version here, need a force push?

2023-02-15 19:27 UTC, renanfranca commented
> 
> * mvn install on your branch on JHipsterLite
> * Generate an app with custom JHlite
> * Update JHlite version in your generated app to use the snapshot one you just built
> 
> Haven't tried it now but I think I remember doing it when working on that feature

I tried the `./mvnw install` but it didn't install the `jhlite-0.27.1-SNAPSHOT-test.jar` and when I run the generated app with the snapshot I got the following message `Failed to execute goal on project customjhlite: Could not resolve dependencies for project tech.jhipster.customjhlite:customjhlite:jar:0.0.1-SNAPSHOT: Could not find artifact tech.jhipster.lite:jhlite:jar:tests:0.27.1-SNAPSHOT`.

When I looked at the maven local repository and compare the generated files of the jhlite-0.27.0 version, it was generated the jhlite-0.27.0-test.jat (image below)

![image](https://user-images.githubusercontent.com/6011616/219130972-8612b1b8-0852-4d98-8611-89f23a4ea78e.png)

I studied that the `./mvnw install` should be enough to install the `jhlite-0.27.1-SNAPSHOT-test.jar`, Do you remember if have to do additional command?

2023-02-15 19:28 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenResources.java
> +public class JHipsterHiddenResources {
I am sorry @DamnClin , I forced push now 👍

2023-02-15 19:32 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenModules.java
> +  private final Collection<String> nestedDependenciesSlugs = new HashSet<>();
This should not be here, this mutable set is really hard to understand. Calculating nested hidden dependencies is JHipsterModulesResources responsibility

2023-02-15 19:40 UTC, DamnClin commented
Took a quick look to the test classifier and it was only built when deploying, dunno why it was done that way, did https://github.com/jhipster/jhipster-lite/pull/5381 to fix that, waiting for @pascalgrimaud approval

2023-02-15 19:43 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenModules.java
> +  private final Collection<String> nestedDependenciesSlugs = new HashSet<>();
@DamnClin, thanks! I'll do it soon!

2023-02-15 19:43 UTC, renanfranca commented
> Took a quick look to the test classifier and it was only built when deploying, dunno why it was done that way, did #5381 to fix that, waiting for @pascalgrimaud approval

Nice! good to know 👍

2023-02-16 14:22 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenModules.java
> +  private final Collection<String> nestedDependenciesSlugs = new HashSet<>();
Hello @DamnClin , I pushed a new version! Please, let me know what you think about it 😃 .

2023-02-16 15:45 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenModules.java
> +public class JHipsterHiddenModules {
Can be a record

2023-02-16 15:45 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenModules.java
> +    this.slugs = slugs;
You can use JHipsterCollections.immutable(...) to ensure that they are immutable and not null

2023-02-16 15:45 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private Collection<JHipsterModuleResource> allResourcesNestedDependenciesOf(
Can result in a stream instead of a collection

2023-02-16 15:45 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private List<String> allSlugsNestedDependenciesOf(Collection<JHipsterModuleResource> modulesResources, String slug) {
Can result in a stream instead of a collection

2023-02-16 15:45 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +    Collection<String> nestedDependencies = new HashSet<>();
With stream result you can flatMap all streams and toList() them

2023-02-16 17:06 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterHiddenModules.java
> +public class JHipsterHiddenModules {
Nice! Done 👍

2023-02-16 17:07 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private Collection<JHipsterModuleResource> allResourcesNestedDependenciesOf(
Cool! did 👍

2023-02-16 17:09 UTC, pascalgrimaud commented
@renanfranca : to ease the test, you can directly add the ignore in jhlite to test, instead of a jhlite-custom

2023-02-16 17:09 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +    Collection<String> nestedDependencies = new HashSet<>();
Thank you @DamnClin! Java Stream is easy to use but harder to master! That was so awesome, the code is much better now! Thanks for leading the steps, flatMap is so powerful!  I pushed the changes in a new commit! Let me know if its good, so I'll go to the log the hidden module feature 👍

2023-02-16 17:11 UTC, renanfranca commented
> @renanfranca : to ease the test, you can directly add the ignore in jhlite to test, instead of a jhlite-custom

Thank you @pascalgrimaud! 😃 👍

2023-02-16 17:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private Function<? super JHipsterModuleResource, ? extends Stream<JHipsterModuleResource>> moveToNextNestedResource(
You can remove the ? extends and ? super

2023-02-16 17:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +    final Collection<JHipsterModuleResource> childrensDependencies = this.getChildrensDependencies(slug, modulesResources);
You can remove the final, it is no useless in local var (still usefull for class attributes)

2023-02-16 17:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private boolean noMoreNestedResource(final Collection<JHipsterModuleResource> childrensDependencies) {
You can remove the final modifier

2023-02-16 17:16 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +    Collection<String> nestedDependencies = new HashSet<>();
No problem, it's really cool that you take them into account! Thanks

2023-02-16 17:27 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private Function<? super JHipsterModuleResource, ? extends Stream<JHipsterModuleResource>> moveToNextNestedResource(
Done 👍

2023-02-16 17:27 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +    final Collection<JHipsterModuleResource> childrensDependencies = this.getChildrensDependencies(slug, modulesResources);
Nice! Done 👍

2023-02-16 17:27 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private boolean noMoreNestedResource(final Collection<JHipsterModuleResource> childrensDependencies) {
Done 👍

2023-02-16 17:28 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +  private boolean noMoreNestedResource(final Collection<JHipsterModuleResource> childrensDependencies) {
Thanks @DamnClin, I pushed the new commit 👍

2023-02-16 18:52 UTC, renanfranca commented
Hello @DamnClin and @pascalgrimaud ,
I pushed the logging hidden modules slugs feature 👍

2023-02-17 06:30 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +      .forEach(resource -> hiddenSlugs.add(resource.slug().get()));
collect(Collectors.joining(", ")) instead of a mutation in a foreach but i don't really get the logic here, I think it's better to just get the hidden modules from the previous method and log them at once.

You can test logs using LogsSpy

2023-02-17 14:09 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +      .forEach(resource -> hiddenSlugs.add(resource.slug().get()));
Hello @DamnClin,
thanks for the LogsSpy, it is really cool!
I had to use Collectors.partitioningBy to get the hidden and not hidden modules at once. Because the hidden modules are defined by the slugs and the tags, so I had to check with the `JHipsterModulesResource` collection.

Maybe I didn't see the better approach you saw... 🤔 . Let me know if I went too far this time 😅 .

I pushed a new commit this time 👍

2023-02-17 15:35 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +      return !hidden.isEmpty();
use the accessors, not the properties (coverrage check will fail)

2023-02-17 15:36 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +        String hiddenModulesSlugs = hiddenSlugs();
you can inline this

2023-02-17 15:36 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +    private boolean hiddenIsPresent() {
`hasHiddenResources`?

2023-02-17 16:01 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +      return !hidden.isEmpty();
thanks, done 👍

2023-02-17 16:01 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +        String hiddenModulesSlugs = hiddenSlugs();
Thanks, @DamnClin for the fast response. pushed new version 👍

2023-02-17 16:02 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java
> +    private boolean hiddenIsPresent() {
much better, i'll do it now 👍

2023-02-19 19:49 UTC, DamnClin approved these changes

2023-02-19 19:50 UTC, merged

2023-02-19 21:05 UTC, renanfranca commented
Bounty Claimed https://opencollective.com/generator-jhipster/expenses/124093 😃 👍 

Thank you @pascalgrimaud !
Thank you @DamnClin for the fast response and for being patient 😄

2023-02-19 21:42 UTC, pascalgrimaud commented
@renanfranca : approved, thanks for your work