Add jib
jhipster/jhipster-lite pull request #554
Opened 2022-01-18 17:06 UTC by swarajsaaj

Add jib through a common docker context

2022-01-18 20:21 UTC, pascalgrimaud commented
Thanks @swarajsaaj !
I'll review it soon ;-)

2022-01-19 22:22 UTC, pascalgrimaud requested changes

2022-01-19 22:22 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/infrastructure/primary/rest/SpringBootDockerResource.java
> +@Tag(name = "Spring Boot")
I suggest to move to tag: Spring Boot - Tools

Then, I'll move async, devtools under this tag too

2022-01-19 22:22 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +                <port>8081</port>
the port should not be 8081, but the same one in application.properties, so it's the property `serverPort`

2022-01-19 22:24 UTC, pascalgrimaud commented
Few comments. Otherwise, I tested it and it works perfectly :)
good job

2022-01-20 12:19 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +                <port>8081</port>
@pascalgrimaud Shall I move `getServerPort` https://github.com/jhipster/jhipster-lite/blob/6243a3253b136b84a5c36d9068997fca3a90cd00/src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/web/domain/SpringBootMvcDomainService.java#L125 to `Project` class for common access?

2022-01-20 12:58 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +                <port>8081</port>
Yes I think it's a good idea. Possible to do it, in a separate PR first?

2022-01-20 13:04 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +                <port>8081</port>
Done prposed change  in [c7ad56](https://github.com/jhipster/jhipster-lite/pull/554/commits/c7ad56095c43f3435790095ea19bf53042428430)

2022-01-20 13:04 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/infrastructure/primary/rest/SpringBootDockerResource.java
> +@Tag(name = "Spring Boot")
Sure. done

2022-01-20 13:07 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/project/domain/ProjectTest.java
> +      assertThatThrownBy(() -> project.getIntegerConfig("serverPort"))
getServerPort() instead

2022-01-20 13:13 UTC, swarajsaaj commented on src/test/java/tech/jhipster/lite/generator/project/domain/ProjectTest.java
> +      assertThatThrownBy(() -> project.getIntegerConfig("serverPort"))
My bad, infact exception is never thrown, instead default 8080 is returned. Thanks for noticing (https://github.com/jhipster/jhipster-lite/pull/554/commits/83f5d228799d2a51a9ec89258fb5052e5977502e)

2022-01-20 14:48 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +                <port>8081</port>
as you moved the code, can you clean these import too plz ?

![image](https://user-images.githubusercontent.com/9156882/150361492-e609fcdf-c07d-45bb-8477-6772707bf764.png)

After that, it should be OK to be merged :)

2022-01-20 15:57 UTC, swarajsaaj commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +                <port>8081</port>
Removed, should we add the sonar quality gate in actions too as breaking step, is it possible for PRs in sonarcloud?

2022-01-20 16:04 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +                <port>8081</port>
See https://github.com/jhipster/jhipster-lite/pull/374/files

I tried to introduce code smell, but Sonarcloud didn't detect it...

2022-01-20 16:12 UTC, merged