Add Flyway
jhipster/jhipster-lite pull request #570
Opened 2022-01-22 13:46 UTC by Bolo89

- fix https://github.com/jhipster/jhipster-lite/issues/234

2022-01-23 09:36 UTC, pascalgrimaud requested changes

2022-01-23 09:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/technical/infrastructure/primary/global/ClockConfiguration.java
> +package tech.jhipster.lite.technical.infrastructure.primary.global;
```suggestion
package tech.jhipster.lite.technical.infrastructure.config;
```

2022-01-23 09:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/infrastructure/primary/rest/FlywayResource.java
> +  @PostMapping
It's because we'll have another API in this class to add user and authority sql files

```suggestion
  @PostMapping("/init")
```

2022-01-23 09:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/domain/Flyway.java
> +  public static final String DEFAULT_SQL_FILES_FOLDER = "db/migration";
Liquibase generates changelog in `src/main/resources/config/liquibase`

I know `db/migration` is the default folder of flyway. I wonder if we should let like this, or rename to have consistency with liquibase, maybe add `flyway`in the path ?

Some solutions:
- let like this (default config)
- rename to be like liquibase: `src/main/resources/config/flyway`
- rename Flyway to: `src/main/resources/flyway` and rename Liquibase to `src/main/resources/liquibase`

Which one do you prefer ? Do you have another suggestion ?

2022-01-23 09:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/domain/FlywayDomainService.java
> +    this.clock = clock;
we'll need this later, when adding new changelog (for user and authority) so need to keep this

2022-01-23 09:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/domain/FlywayDomainService.java
> +      "V${datetime}__init.sql",
to be simpler, I think we can named it to: `V00000000000000__init.sql` (similar to https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml)

2022-01-23 09:36 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/dbmigration/flyway/resources/V${datetime}__init.sql
> +-- Delete the init change log in the table 'flyway_schema_history' if this file is modified;
maybe rename this file to be simpler ? V00000000000000__init.sql

2022-01-23 09:40 UTC, pascalgrimaud commented
Another comment: can you add the API in CI tests plz ?
We could replace liquibase here: https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L55

2022-01-24 17:18 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/domain/Flyway.java
> +  public static final String DEFAULT_SQL_FILES_FOLDER = "db/migration";
As discussed, I prefer to keep the default flyway path (liquibase and flyway don't have link each other)

2022-01-24 17:27 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/flyway/infrastructure/primary/rest/FlywayResource.java
> +  @PostMapping
But the verb " POST " means that it's a creation ? So I think it's not useful, and we can use the verb " PUT " for update (add user and authority in this example) ?
I will do the change and use the "/init" to be "iso" with the existing.

2022-01-26 18:32 UTC, merged

2022-02-03 10:22 UTC, Bolo89 commented
Hello,

Bounty claimed at : https://opencollective.com/generator-jhipster/expenses/63105

2022-02-03 10:23 UTC, pascalgrimaud commented
@Bolo89 : approved