Add Angular
jhipster/jhipster-lite pull request #571
Opened 2022-01-22 17:50 UTC by qmonmert

Related to #294

2022-01-24 07:23 UTC, pascalgrimaud commented
It looks promising!

Few comments:
- missing generated tests, so we need to test the coverage manually
- organizing to an hexagonal architecture, I'll try to find help here
- maybe add some minimal CSS to home page ?

Another PRs:
- I think we should add the minimum coverage in another PR
- the packaging done by maven, can be added in another PR -> similar to what I did for Vue, I can take care of it

2022-01-24 19:51 UTC, qmonmert commented
@pascalgrimaud add some minimal CSS to home page ✅

![image](https://user-images.githubusercontent.com/9989211/150854210-477f9703-2c3b-48a6-b3c3-99cae2988e32.png)

2022-01-27 09:24 UTC, pascalgrimaud commented
Good job @qmonmert 
I'll review it soon to suggest how to organize the code

2022-01-27 09:37 UTC, qmonmert commented
@pascalgrimaud ok :)

2022-02-08 21:48 UTC, pascalgrimaud commented
some additional comment:
- you need to bump the current versions, otherwise, it's broken

```diff
+    "@angular/compiler-cli": "13.2.2",
+    "@angular/cli": "13.2.2",
+    "@angular-devkit/build-angular": "13.2.2",
+    "@angular-builders/jest": "13.0.3",
```

```diff
+    "@angular/router": "13.2.2",
+    "@angular/platform-browser-dynamic": "13.2.2",
+    "@angular/platform-browser": "13.2.2",
+    "@angular/forms": "13.2.2",
+    "@angular/core": "13.2.2",
+    "@angular/compiler": "13.2.2",
+    "@angular/common": "13.2.2",
+    "@angular/animations": "13.2.2"
```

- the `ng build` must have `--output-path=target/classes/static`

With these changes, you can use Frontend Maven Plugin, start the SpringBoot+Angular and it works fine

2022-02-11 13:58 UTC, wmarques commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +      "jasmine-core",
jasmine inutile si on part sur Jest à priori

2022-02-11 13:58 UTC, wmarques commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.component.css.mustache
> +:host {
Du coup là on garde le CSS généré par le CLI c'est l'idée  ?

2022-02-11 13:58 UTC, wmarques commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.component.ts.mustache
> +    this.title = 'JHipster Lite';
Pourquoi on fait pas title = 'JHipster Lite' direct ?  :)

2022-02-11 13:58 UTC, wmarques commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.module.ts.mustache
> +  providers: [],
providers à supprimer, pas utile on va surement faire du `providedIn: 'root'` partout

2022-02-12 12:34 UTC, qmonmert commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +      "jasmine-core",
yes, done

2022-02-12 12:34 UTC, qmonmert commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.module.ts.mustache
> +  providers: [],
yes, done

2022-02-12 12:35 UTC, qmonmert commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.component.css.mustache
> +:host {
@pascalgrimaud wanted a little of CSS, so I used the CSS generated by the CLI, we updated later

2022-02-12 20:18 UTC, chrisdns submitted a review, later dismissed

2022-02-12 20:18 UTC, chrisdns commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularDomainService.java
> +      .forEach((file, path) -> projectRepository.template(project, SOURCE_WEBAPP + "/" + path, file, getPath(MAIN_WEBAPP, path)));
maybe use `File.separator` here to avoid any kind of path issues depending on operating system

2022-02-12 20:21 UTC, chrisdns commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularDomainService.java
> +      .forEach((file, path) -> projectRepository.template(project, SOURCE_WEBAPP + "/" + path, file, getPath(MAIN_WEBAPP, path)));
maybe use `File.separator` here to avoid any kind of path issues depending on operating system

2022-02-12 20:33 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularDomainService.java
> +      .forEach((file, path) -> projectRepository.template(project, SOURCE_WEBAPP + "/" + path, file, getPath(MAIN_WEBAPP, path)));
In fact, you can use the getPath(...) method, it will do the job, so you don't need to care about using File separator

2022-02-12 20:47 UTC, qmonmert commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularDomainService.java
> +      .forEach((file, path) -> projectRepository.template(project, SOURCE_WEBAPP + "/" + path, file, getPath(MAIN_WEBAPP, path)));
thanks @chrisdns & @pascalgrimaud : done

2022-02-13 17:23 UTC, pascalgrimaud requested changes

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/resources/generator/client/angular/jest.conf.js
> +module.exports = {
plz add this part too:

```
  coverageThreshold: {
    global: {
      statements: 100,
      branches: 100,
      functions: 100,
      lines: 100,
    },
  },
```

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularDomainService.java
> +}
have a look at https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/client/vite/vue/core/domain/ViteVueDomainService.java#L116-L126

You need to add this jest config in generated `package.json`

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +    // @formatter:offProjectLocalRepository
maybe can be removed

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +    // @formatter:on
can be removed

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +    // @formatter:offProjectLocalRepository
```suggestion
    // @formatter:off
```

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +    return Map.ofEntries(
maybe `Map.of(` instead?

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularDomainService.java
> +      );
refactoring: can go into smaller private method

then, you need to throw exception if the getVersionInAngular is not found

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularDomainService.java
> +      );
refactoring: can go into smaller private method

then, you need to throw exception if the getVersionInAngular is not found

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.component.css.mustache
> +:host {
minor comment: can it be indent with 2 spaces, instead of 4?

2022-02-13 17:23 UTC, pascalgrimaud commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.component.html.mustache
> +    width="40"
indent with 2 spaces, instead of 4
I think you can use prettier in a generated project with Angular to pick the result

2022-02-13 17:31 UTC, pascalgrimaud requested changes

2022-02-13 17:31 UTC, pascalgrimaud commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.component.spec.ts.mustache
> +    it('Should synchronize account variable with current account', () => {
strange description of the tests, I think it's wrong here :)

2022-02-13 17:31 UTC, pascalgrimaud commented on src/main/resources/generator/client/angular/src/main/webapp/app/app.component.spec.ts.mustache
> +
try to format with prettier, this empty line should not be present

2022-02-13 17:31 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/client/angular/core/application/AngularApplicationServiceIT.java
> +    AngularAssert.assertAngularFiles(project);
can import static AngularAssert

2022-02-13 17:31 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/client/angular/core/application/AngularAssert.java
> +    assertFileContent(project, PACKAGE_JSON, "@angular-builders/jest" + DQ + ": ");
I think you can use Angular.devDependencies + stream()

2022-02-13 17:31 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/client/angular/core/application/AngularAssert.java
> +    assertFileContent(project, PACKAGE_JSON, "zone.js" + DQ + ": ");
same here, use Angular.dependencies() + stream

2022-02-13 17:35 UTC, qmonmert commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +    return Map.ofEntries(
`Map.of` is limited to 10 values, too small in this case

2022-02-13 17:35 UTC, pascalgrimaud commented
About structure, I think it would be better to have all app.* in `webapp/app/common/primary/app/`
It should look like:

![image](https://user-images.githubusercontent.com/9156882/153767206-5b2cd55b-3146-4bc2-a6b9-5f02f389f809.png)

2022-02-13 20:41 UTC, pascalgrimaud requested changes

2022-02-13 20:41 UTC, pascalgrimaud commented on src/main/resources/generator/client/angular/jest.conf.js
> +  testMatch: ['<rootDir>/src/main/webapp/app/**/@(*.)@(spec.ts)'],
```suggestion
  testMatch: [
    '<rootDir>/src/main/webapp/environments/**/@(*.)@(spec.ts)',
    '<rootDir>/src/main/webapp/app/**/@(*.)@(spec.ts)'
  ],
```

2022-02-13 20:43 UTC, pascalgrimaud commented
Can you add these files too plz ?

environment.spec.ts :

```typescript
import { environment } from './environment';

describe('environment', () => {
  it('production should be false', () => {
    expect(environment.production).toBeFalsy();
  });
});
```

environment.prod.spec.ts :

```typescript
import { environment } from './environment.prod';

describe('environment', () => {
  it('production should be true', () => {
    expect(environment.production).toBeTruthy();
  });
});
```

app-routing.module.spec.ts :

```typescript
import { AppRoutingModule } from './app-routing.module';

describe('AppRoutingModule', () => {
  it('should be defined', () => {
    expect(AppRoutingModule).toBeDefined();
  });
});
```

2022-02-13 20:55 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +      Map.entry("environment.prod.spec.ts", "environments"),
don't forget the AngularAssert too :)

2022-02-13 20:56 UTC, qmonmert commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/Angular.java
> +      Map.entry("environment.prod.spec.ts", "environments"),
I did not forget :)

2022-02-13 21:30 UTC, pascalgrimaud approved these changes

2022-02-13 21:30 UTC, merged

2022-02-13 21:30 UTC, pascalgrimaud commented
Really great job @qmonmert