Maven: extract property and get version
jhipster/jhipster-lite pull request #572
Opened 2022-01-22 20:21 UTC by DanielFran

Related with https://github.com/jhipster/jhipster-lite/issues/278

2022-01-22 20:22 UTC, DanielFran commented
@pascalgrimaud Is it OK for you?

2022-01-22 20:38 UTC, pascalgrimaud commented
Yes ping me when it's ready for review

2022-01-23 14:45 UTC, qmonmert commented on src/main/java/tech/jhipster/lite/generator/buildtool/generic/domain/BuildToolDomainService.java
> +    if (project.isMavenProject()) {
you can remove the `else`

```
if (project.isMavenProject()) {
    return mavenService.getVersion(name);
} 
throw new GeneratorException(EXCEPTION_NO_BUILD_TOOL);
```

2022-01-25 08:13 UTC, pascalgrimaud requested changes

2022-01-25 08:22 UTC, pascalgrimaud requested changes

2022-01-25 08:22 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenDomainService.java
> +    String property_tag_ini = new StringBuilder().append("<").append(name).append(".version").append(">").toString();
sonar code smell: use `propertyTagIni` instead

2022-01-25 08:22 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenDomainService.java
> +    String property_tag_end = new StringBuilder().append("</").append(name).append(".version").append(">").toString();
use `propertyTagEnd` instead

2022-01-25 08:52 UTC, DanielFran commented on src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenDomainServiceTest.java
> +        fileUtilsMock.when(() -> FileUtils.getPath(Mockito.anyString())).thenReturn("mypath");
Forget to fix the test, sorry.

2022-01-25 09:14 UTC, pascalgrimaud approved these changes

2022-01-25 09:15 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/generic/domain/BuildToolDomainService.java
> +    if (project.isMavenProject()) {
@DanielFran : can you do this minor change plz?

2022-01-25 14:26 UTC, DanielFran commented
@pascalgrimaud anything missing?

2022-01-25 14:29 UTC, pascalgrimaud commented
@DanielFran : yes, last comment from @qmonmert

![image](https://user-images.githubusercontent.com/9156882/150995689-715b3096-ef22-423a-ba7a-dd6592efe6f2.png)

2022-01-25 14:41 UTC, qmonmert approved these changes

2022-01-25 14:50 UTC, merged