add dark mode support
jhipster/jhipster-lite pull request #6024
Opened 2023-04-23 14:26 UTC by zhyd1997

support dark/light mode switch

Close: UX/UI: dark/light mode #2892

2023-04-24 05:21 UTC, DamnClin commented
LGTM. What's the behavior on the patches screen? (Since it's still in dark mode by default...)

2023-04-24 05:25 UTC, pascalgrimaud commented
@DamnClin : I don't think it's finished yet, as there is no switch button to change between light and dark

2023-04-24 05:25 UTC, zhyd1997 commented
Hi @DamnClin 

Thanks for your review, still work in progress, btw, how to resolve this error when running `npm run dev`? :eyes:

<img width="528" alt="Screenshot 2023-04-24 at 13 24 25" src="https://user-images.githubusercontent.com/31362988/233906925-eb92a990-5d6e-4f0e-a01f-cc3d0276c079.png">

2023-04-24 05:29 UTC, zhyd1997 commented
Hi @pascalgrimaud 

Switch button has been implemented on my side, but it doesn’t effect page styles, maybe put css variables in wrong places, debugg it...

https://user-images.githubusercontent.com/31362988/233907176-019463fb-aa92-4100-9aa8-b42663cc1da9.mov

> btw, the work can be done in my spare time, so let me know what do you think of it if this ticket has higher priority.

2023-04-24 05:34 UTC, pascalgrimaud commented
@zhyd1997 : thanks for your work and take your time, as it's an open source project :-)

I think you forget to start the backend, to access to api. Just run: `./mvnw`

2023-04-26 04:32 UTC, zhyd1997 commented
Hi team 👋 

Does someone knows how CSS is mapped and loaded or where is the root css used in global in the codebase? 👀

2023-04-26 04:44 UTC, pascalgrimaud commented
@zhyd1997 :
- the CSS uses a pattern library, following https://www.tikui.org/
- you can use this script to display the CSS `npm run tikui:serve` : https://github.com/jhipster/jhipster-lite/blob/main/package.json#L41
- all the CSS is in the `src/main/style` : https://github.com/jhipster/jhipster-lite/tree/main/src/main/style
- don't forget to add unit tests and e2e tests with Cypress :-)

2023-04-26 07:11 UTC, zhyd1997 commented
Blocked by https://github.com/jhipster/jhipster-lite/pull/6070.

2023-04-29 09:17 UTC, zhyd1997 commented
**QA Verify:**

- `patch` page (**dark**) and `landscape` page (**light**):

https://user-images.githubusercontent.com/31362988/235294948-8eb7e3e1-4cc2-45a6-81fd-c3cccc663914.mov

- `landscape` page (**dark**):

https://user-images.githubusercontent.com/31362988/235295005-e6e82498-9883-437e-a83a-0980ee4ea28a.mov

- `patch` page (**light**):

https://user-images.githubusercontent.com/31362988/235295070-e60746bc-4647-4c24-8b63-7720025ad9b3.mov

2023-04-29 09:27 UTC, zhyd1997 commented
Hi 👋 @pascalgrimaud @DamnClin 

The PR is marked as **Ready for Review**, PTAL when you are available. 

Thanks 🙏

2023-04-30 05:47 UTC, DamnClin commented
cc @Gnuk you can have a look at it?

2023-04-30 07:14 UTC, Gnuk requested changes

2023-04-30 07:14 UTC, Gnuk commented on src/main/webapp/app/common/primary/header/Header.component.ts
> +  mounted() {
I'm globally not sure about the place of this logic. I think the header is too specific, but maybe it's related on the missing secondary adapter.

2023-04-30 07:14 UTC, Gnuk commented on src/main/webapp/app/common/primary/header/Header.component.ts
> +    setTheme(theme: 'light-theme' | 'dark-theme') {
I think it's the only method needed here to change the theme through a repository

2023-04-30 07:14 UTC, Gnuk commented on src/main/webapp/app/common/primary/header/Header.vue
> +        <label for="switch">Toggle</label>
How we know the theme is light or dark ?

2023-04-30 07:14 UTC, Gnuk commented on src/main/webapp/app/module/primary/module-parameters/ModuleParameters.vue
> +    color: #fff;
Why this color is not using a token? (even if the token is provided by a CSS variable)

2023-04-30 07:14 UTC, Gnuk commented on src/main/webapp/app/module/primary/modules-patch/ModulesPatch.vue
> +    color: #ffffff;
Why this color is not provided by a token?

2023-04-30 07:14 UTC, Gnuk commented on src/test/javascript/cypress/integration/Landscape.spec.ts
> +    cy.get('#switch').should('exist');
Maybe use a data selector instead of an id

2023-04-30 07:14 UTC, Gnuk commented on src/test/javascript/cypress/integration/Landscape.spec.ts
> +    cy.get('.jhlite-layout--body').should('have.css', 'background-color', 'rgb(255, 255, 255)');
Maybe just check the theme is dark or light with the class.

2023-04-30 07:14 UTC, Gnuk commented on src/test/javascript/cypress/integration/Patch.spec.ts
> +    it('Should change theme after toggle switch theme button', () => {
Same as previous comments.

2023-04-30 07:14 UTC, Gnuk commented on src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
> +      vi.spyOn(window, 'matchMedia').mockReturnValue(mediaQueryListStub);
If you inject a repository, you don't have to spy global window behavior.

2023-04-30 07:14 UTC, Gnuk commented on src/test/javascript/spec/setup/setup.ts
> +Object.defineProperty(window, 'matchMedia', {
If you use a repository you don't have to do that.

2023-04-30 07:14 UTC, Gnuk commented on vitest.config.ts
> +    setupFiles: ['src/test/javascript/spec/setup/setup.ts'],
I think you don't have to make a setup file of you respect the hexagonal architecture principle by doing a secondary adapter to get and change the theme and inject a fake window and a fake local storage inside the constructor. So from the domain, the secondary port may just have a way to choose a theme and a way to get the theme.

2023-04-30 11:30 UTC, zhyd1997 commented on src/main/style/root/_root.scss
> +  --brand-800: #045085;
Hi @Gnuk 

Thanks for your review!

Any suggestions here? 👀

2023-04-30 11:32 UTC, Gnuk commented on src/main/style/root/_root.scss
> +  --brand-800: #045085;
Yes, by using the prefix 'jhlite-' like all other style parts. And also by reusing colours from sass token variables.

2023-04-30 14:25 UTC, zhyd1997 commented on src/test/javascript/cypress/integration/Landscape.spec.ts
> +    cy.get('.jhlite-layout--body').should('have.css', 'background-color', 'rgb(255, 255, 255)');
How?

check `:root.dark-theme` or `:root.light-theme` ?

2023-04-30 14:30 UTC, zhyd1997 commented on src/test/javascript/cypress/integration/Landscape.spec.ts
> +    cy.get('.jhlite-layout--body').should('have.css', 'background-color', 'rgb(255, 255, 255)');
How? 👀 

check `:root.dark-theme` or `:root.light-theme` ?

2023-05-01 02:59 UTC, zhyd1997 commented on src/test/javascript/cypress/integration/Landscape.spec.ts
> +    cy.get('.jhlite-layout--body').should('have.css', 'background-color', 'rgb(255, 255, 255)');
Done: https://github.com/jhipster/jhipster-lite/pull/6024/commits/4e33a4877bfbc3dec8990d71803f363e4ef08ad6

2023-05-01 04:29 UTC, zhyd1997 commented on vitest.config.ts
> +    setupFiles: ['src/test/javascript/spec/setup/setup.ts'],
the most challenging thing!

have no idea how to do it.

```ts
class ThemeButton {
  private themeStorage: ThemeStorage;
  private window: Window;

  constructor(themeStorage: ThemeStorage, window: Window) {
    this.themeStorage = themeStorage;
    this.window = window;
  }

  // ...

  private getTheme() {
    return this.themeStorage.get(THEME_STORAGE_KEY);
  }

  private setTheme(theme: Theme) {
    this.themeStorage.set(THEME_STORAGE_KEY, theme);
    this.window.document.documentElement.className = theme;
  }
}

class FakeThemeStorage implements ThemeStorage {
  // ...
}

class FakeWindow {
  document = {
    documentElement: {
      className: ''
    }
  };
}

const themeButton = new ThemeButton(new FakeThemeStorage(), new FakeWindow());
```

This doesn't work.

2023-05-01 11:43 UTC, Gnuk requested changes

2023-05-01 13:39 UTC, zhyd1997 commented on src/main/webapp/app/common/secondary/LocalStorage.ts
> +export default class LocalStorageAdapter implements Storage {
Thanks 🙏 but what's the usage of `win` and `storage`, `getMediaPreference` need global `window` object.

Sorry, not familiar with OOP design principle.

2023-05-01 14:06 UTC, Gnuk commented on src/main/webapp/app/common/secondary/LocalStorage.ts
> +export default class LocalStorageAdapter implements Storage {
You have to make an intance of the LocalWindowThemeRepository by passing the window and the localstorage from a provider (in the main file) then you'll be able to inject it using the domain interface from your component

2023-05-02 03:24 UTC, zhyd1997 commented on src/main/webapp/app/common/secondary/LocalStorage.ts
> +export default class LocalStorageAdapter implements Storage {
Great Tips.

Thanks!

2023-05-02 22:58 UTC, zhyd1997 commented
Hi @Gnuk

All things are done!

2023-05-06 06:25 UTC, Gnuk commented
I think I will contribute to complete this PR when I'm available. What do you think about this ?

2023-05-06 06:27 UTC, zhyd1997 commented
@Gnuk What's wrong? 👀

2023-05-06 06:47 UTC, Gnuk commented
> @Gnuk What's wrong? 👀 

Nothing, it's just a suggestion but I can continue reviewing until it's ok if you prefer. It's just to because I'm a little busy and feedbacks will not be consistent all the time.

2023-05-06 06:55 UTC, zhyd1997 commented
Sorry for disturbed you, anyway, thanks for taking so much your time to review my PR, and you can continue to  contribute to the PR!

2023-05-06 07:02 UTC, Gnuk requested changes
Sorry if I'm not exhaustive.

2023-05-06 07:02 UTC, Gnuk commented on src/test/javascript/spec/common/primary/theme-button/ThemeButton.spec.ts
> +    expect(localWindowThemeRepository.choose.called).toBe(true);
I think it's not a relevant test because it's true all the time here. Maybe you want to know the called value? Maybe you want to know how many calls? Maybe you want something else?

2023-05-06 07:08 UTC, Gnuk commented
> Sorry for disturbed you @Gnuk, anyway, thanks for taking so much your time to review my PR, and you can continue to  contribute to the PR!

Don't worry, it's not a problem, it's more about frustration you can have to receive late feedbacks ^^. You know it's just a free software, so you don't disturb me. It was just a suggestion to help you and to prevent long feedbacks ;)

2023-05-13 06:51 UTC, zhyd1997 commented on src/main/webapp/app/common/primary/theme-button/ThemeButton.vue
> +<style>
Hi @Gnuk 

Sorry for a little busy at the last week, follow the pattern as the `Landscape` shows:

https://github.com/jhipster/jhipster-lite/blob/main/src/main/webapp/app/module/primary/landscape/Landscape.vue

2023-05-29 07:41 UTC, DamnClin commented
Waking up from hibernation :D. Where are we on this?

2023-05-29 07:46 UTC, zhyd1997 commented
> Waking up from hibernation :D. Where are we on this?

Something need to review :) because I have no knowledge about the architecture and design method of the repo.

2023-05-29 07:47 UTC, DamnClin commented
> > Waking up from hibernation :D. Where are we on this?
> 
> Something need to review :) because I have no knowledge about the architecture and design method of the repo.

Ok, do you need help?

2023-05-29 07:48 UTC, zhyd1997 commented
@DamnClin waiting for @Gnuk 's review.

2023-05-29 07:55 UTC, Gnuk commented
Sorry, I was not available the two past weeks, I'm still busy today.

2023-05-29 07:56 UTC, zhyd1997 commented
@Gnuk Sure, if you review it in anytime.

2023-06-26 05:37 UTC, pascalgrimaud commented
As a some reviews have been done, maybe it can be merged, and then some improvements can be done later ?
What do you think @Gnuk ?

2023-07-07 09:39 UTC, merged

2023-07-07 14:32 UTC, zhyd1997 commented
@pascalgrimaud Sure

2023-07-07 15:17 UTC, zhyd1997 commented
After investigation, these files missing their own unit tests instead of testing them in component spec files:

https://sonarcloud.io/component_measures?id=jhipster_jhipster-lite&metric=coverage&view=list

Need add test files in this folder: https://github.com/jhipster/jhipster-lite/tree/main/src/test/javascript/spec/module/secondary

Will submit a PR in the next few days.