Share module properties between landscape and patch screens
jhipster/jhipster-lite pull request #6091
Opened 2023-04-27 19:55 UTC by renanfranca

Fix #3371

2023-04-28 10:50 UTC, renanfranca commented
Hello @DamnClin,
I implemented it using LocalStorage. When you have the time, please, let me know if it is enough.
Thank you in advance 😄 👍

2023-04-28 11:29 UTC, DamnClin commented
I'm afraid I won't be able to have a look at it soon... @Gnuk can you check?

2023-04-28 20:58 UTC, Gnuk requested changes

2023-04-28 20:58 UTC, Gnuk commented on src/main/webapp/app/module/domain/ModuleParametersRepository.ts
> +  getRef(): Ref<Map<K, V>>;
I don't understand why you're using a infrastructure notion on your Repository, I think it's a hexagonal architecture violation. Because inside the domain, it's not normal to have things like Vue.

2023-04-28 20:58 UTC, Gnuk commented on src/main/webapp/app/module/domain/ModuleParametersRepository.ts
> +export interface ModuleParametersRepository<K, V> {
Maybe I'm wrong but you seems to not use the generics here when you're trying to implements this repository.

2023-04-28 20:58 UTC, Gnuk commented on src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
> +    const moduleParametersValues = moduleParameters.getRef();
It's a bit confusing to me to see a usage of a ref from a repository cause it's a reactive notion from the framework and it's not agnostic.

2023-04-29 03:02 UTC, renanfranca commented on src/main/webapp/app/module/domain/ModuleParametersRepository.ts
> +  getRef(): Ref<Map<K, V>>;
Hello. @Gnuk !
Thank you for the fast response 👏👏

You are right! I will try another approach which avoid hexagonal architecture violation .

It's my first time working with Vie framework.
I am going to implement it as soon as possible,,,,😃

2023-04-29 03:06 UTC, renanfranca commented on src/main/webapp/app/module/domain/ModuleParametersRepository.ts
> +export interface ModuleParametersRepository<K, V> {
Hou are right, I should use in the interface the same type i use  at the repository.

2023-04-29 03:08 UTC, renanfranca commented on src/main/webapp/app/module/primary/modules-patch/ModulesPatch.component.ts
> +    const moduleParametersValues = moduleParameters.getRef();
I understand, thank you! I will try a different approach as soon as possible 👍

2023-05-02 11:11 UTC, renanfranca commented
Hello @Gnuk,
I pushed the changes in a new commit `avoid hexagonal architecture violation`. Please, let me know what you think.

2023-05-02 11:37 UTC, Gnuk requested changes

2023-05-02 11:37 UTC, Gnuk commented on src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
> +    localStorage.setItem(this.STORAGE_KEY, JSON.stringify(Array.from(map.entries())));
Please inject localStorage using a constructor and pass it when you make the instance from the main.

2023-05-02 11:37 UTC, Gnuk commented on src/test/javascript/spec/module/primary/modules-patch/ModulesPatchComponent.spec.ts
> +  sinon.stub(window, 'localStorage').value(stubLocalStorage);
With a constructor field you have no longer to add a stub on global window.

2023-05-02 19:33 UTC, renanfranca commented on src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
> +    localStorage.setItem(this.STORAGE_KEY, JSON.stringify(Array.from(map.entries())));
Thanks for the clear instruction @Gnuk,
that's much better!

2023-05-02 19:33 UTC, renanfranca commented on src/test/javascript/spec/module/primary/modules-patch/ModulesPatchComponent.spec.ts
> +  sinon.stub(window, 'localStorage').value(stubLocalStorage);
Thanks!
Nice! Much better!

2023-05-02 19:36 UTC, renanfranca commented
Hi @Gnuk,
I pushed a new commit `create a constructor to receive localStorage as a parameter` to be reviewed.

2023-05-02 20:34 UTC, Gnuk requested changes

2023-05-02 20:34 UTC, Gnuk commented on src/test/javascript/spec/module/secondary/LocalStorageModuleParametersRepository.spec.ts
> +  const mockLocalStorage = (() => {
Maybe you're creating a fake, so you can name this fakeStorage. Then you don't need to define a localStorage on the window because you're mutating the existing one and it's not needed because now you can just inject your fake. Then you can use it as a function instead of calling it directly after the definition.

At the end you may have something like this:

```typescript
const fakeStorage = (): Storage => {
  //...
};
```

And to use it from a test case (inside an `it`):

```typescript
const storage = fakeStorage();
// ...
```

2023-05-03 16:29 UTC, renanfranca commented on src/test/javascript/spec/module/secondary/LocalStorageModuleParametersRepository.spec.ts
> +  const mockLocalStorage = (() => {
Thanks, @Gnuk for the clear instructions!
I did as you requested. I pushed a new commit  `use a fakeStorage instead of mockLocalStorage` to be reviewed when you have the time 👍

2023-05-05 20:13 UTC, renanfranca commented
Hello @Gnuk,
I remove the sonar bug fix from here because it is handled by this issue https://github.com/jhipster/jhipster-lite/issues/6146 . So I rebase my changes in a single commit, let me know if you think this issue is fixed.

Thank you 😄

2023-05-06 06:23 UTC, Gnuk submitted a review, later dismissed

2023-05-06 06:23 UTC, Gnuk commented on src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
> +    } else {
Else is not needed because you use return from the previous condition

2023-05-06 11:17 UTC, renanfranca commented on src/main/webapp/app/module/secondary/LocalStorageModuleParametersRepository.ts
> +    } else {
Thank you @Gnuk!

I did as you requested and I pushed a new version with that change 😃 👍

2023-05-06 12:37 UTC, Gnuk approved these changes

2023-05-06 17:17 UTC, renanfranca commented
@Gnuk, I am sorry! I pressed the request review button by mistake! I didn't know what that button do. Have a nice weekend 😃👍

2023-05-06 19:42 UTC, Gnuk approved these changes

2023-05-08 12:45 UTC, merged

2023-05-08 15:54 UTC, renanfranca commented
Bounty Claimed https://opencollective.com/generator-jhipster/expenses/138076
Thank you @pascalgrimaud!
Thank you @Gnuk for the detailed reviews and I learn a lot about vue and frontend!

2023-05-08 15:58 UTC, pascalgrimaud commented
@Gnuk : if you want to claim 100$ bounty for time spending to review it, plz do it and link here