Fix #579 : Use spring boot dependencies bom instead of spring boot pa…
jhipster/jhipster-lite pull request #626
Opened 2022-01-31 14:55 UTC by beatfreaker

related to #579

2022-01-31 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=626) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=626) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=626) it.</sub>

2022-01-31 15:42 UTC, pascalgrimaud commented
@beatfreaker : thanks for your contribution. Can you rebase against main branch plz? Just did a quick fix, related to liquibase

2022-01-31 19:49 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootDomainService.java
> +            .additionalElements(
Unless I'm wrong, this part should not change. You need to add another part for plugin management

You can have a look at:
- https://github.com/jhipster/jhipster-sample-app/blob/main/pom.xml#L354-L357
- https://github.com/jhipster/jhipster-sample-app/blob/main/pom.xml#L764-L784

2022-01-31 19:54 UTC, beatfreaker commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootDomainService.java
> +            .additionalElements(
Got it, and adding that logic within `addSpringBootMavenPlugin()` is good, or should we create new method specifically for adding plugin into `<pluginManagement>` ?

2022-01-31 20:46 UTC, beatfreaker commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootDomainService.java
> +            .additionalElements(
Didn't add below comment, is it fine ? or we should add it ?

```xml
<!--
    Enable the line below to have remote debugging of your application on port 5005
    <jvmArguments>-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005</jvmArguments>
-->
```

2022-01-31 20:47 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootDomainService.java
> +            .additionalElements(
No need I think. Never used it myself :-)

2022-01-31 21:02 UTC, pascalgrimaud commented
I'll review and test it tomorrow :-)

2022-02-01 07:48 UTC, pascalgrimaud requested changes

2022-02-01 07:48 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootDomainService.java
> +                      </execution>
```suggestion
                      <execution>
                        <goals>
                          <goal>repackage</goal>
                        </goals>
                      </execution>
```

2022-02-01 07:48 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/core/domain/SpringBootDomainService.java
>              .version((String) project.getConfig("springBootVersion").orElse(version))
```suggestion
            .version("\\${spring-boot.version}")
```

2022-02-01 08:12 UTC, pascalgrimaud commented
@beatfreaker : I think the test needs to be updated too ;)

2022-02-01 08:24 UTC, beatfreaker commented
> @beatfreaker : I think the test needs to be updated too ;)

sorry forgot to test it, as tried to provide quick update using `github.dev web editor` my bad.

2022-02-01 08:38 UTC, pascalgrimaud approved these changes

2022-02-01 08:39 UTC, pascalgrimaud commented
Thanks and congrats for your 1st contribution @beatfreaker !

2022-02-01 08:39 UTC, merged

2022-02-01 09:33 UTC, beatfreaker commented
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/62764

2022-02-01 09:46 UTC, pascalgrimaud commented
@beatfreaker : approved