Add history
jhipster/jhipster-lite pull request #638
Opened 2022-02-02 18:18 UTC by Bolo89

2022-02-02 20:04 UTC, pascalgrimaud commented
Huge work, thanks a lot @Bolo89 !
Could you try to fix the failure with Windows plz? You can have the details here: https://github.com/jhipster/jhipster-lite/runs/5041186201?check_suite_focus=true

Then I'll review it soon.

2022-02-03 08:17 UTC, pascalgrimaud requested changes

2022-02-03 08:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/history/package-info.java
> +@tech.jhipster.lite.SharedKernel
can be changed to BusinessContext, as the context `history` is not called by other context

2022-02-03 08:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/history/domain/GeneratorHistoryData.java
> +  public GeneratorHistoryData setValues(List<GeneratorHistoryValue> values) {
not sure we need a setter here. Instead, we should need only a addValue method

2022-02-03 08:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/history/domain/GeneratorHistoryDomainService.java
> +public class GeneratorHistoryDomainService implements GeneratorHistoryService {
No need this domain service. In fact, instead of doing this:

applicationService -> service (port in) -> domainService (impl) -> interface repository (port out) -> impl repository

You could do:

applicationService -> interface repository (port out) -> impl repository

If I'm not clear enough, tell me

2022-02-03 08:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/history/domain/GeneratorHistoryValue.java
> +public class GeneratorHistoryValue {
use record (Java17)

2022-02-03 08:17 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/history/application/GeneratorGeneratorHistoryApplicationServiceIT.java
> +class GeneratorGeneratorHistoryApplicationServiceIT {
```suggestion
class GeneratorHistoryApplicationServiceIT {
```

2022-02-03 08:20 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/common/domain/JsonUtils.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
we are in common.domain, and should not depend on external libraries. But I think we already didn't respect that, for other files -> we should do something here, but can be done in another PR

2022-02-03 17:28 UTC, pascalgrimaud approved these changes

2022-02-03 17:28 UTC, merged

2022-02-09 17:47 UTC, Bolo89 commented
bounty claimed at: https://opencollective.com/generator-jhipster/expenses/63793

2022-02-09 18:42 UTC, pascalgrimaud commented
@Bolo89 : approved