Fix #619 : Add integration test for UserJpaRepository
jhipster/jhipster-lite pull request #639
Opened 2022-02-02 18:19 UTC by beatfreaker

Related to #619

2022-02-02 18:44 UTC, beatfreaker commented
@pascalgrimaud test are failing because of `autoIncrement=true` is not present, should I fix it in this PR only, or it should be handle as separate issue ?

2022-02-02 18:51 UTC, pascalgrimaud commented
Better to fix it separately, in another PR

2022-02-02 19:35 UTC, beatfreaker commented
As we want to add `autoincrement` only for mysql is it okay to expect database in input request body as below
And use it in mustache template to render it conditionally ?

```json
{
  "folder": "/tmp/jhlite/undertow-simplecache",
  "generator-jhipster": {
    "projectName": "Beer Project",
    "baseName": "beer",
    "prettierDefaultIndent": 2,
    "packageName": "tech.jhipster.beer",
    “database”: “mysql”
  }
}

```

2022-02-02 19:44 UTC, pascalgrimaud commented
No need, in liquibase code, we have the code which can know if it's MySQL database:
https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/generator/server/springboot/dbmigration/liquibase/domain/LiquibaseDomainService.java#L129

I can take care of this fix if you want?
I can address it in the next couple of minutes if needed

2022-02-02 20:20 UTC, pascalgrimaud commented
- just done the fix https://github.com/jhipster/jhipster-lite/pull/640

Can you rebase plz?

2022-02-03 07:47 UTC, pascalgrimaud requested changes

2022-02-03 07:47 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/user/sqldatabase/UserJpaRepositoryIT.java.mustache
> +  @Transactional
you can remove this `@Transactional`

2022-02-03 07:53 UTC, pascalgrimaud approved these changes

2022-02-03 08:18 UTC, merged

2022-02-03 08:18 UTC, pascalgrimaud commented
Thanks and good job @beatfreaker !
This was important, as you can see, we manage to find some issues :)

2022-02-03 09:23 UTC, beatfreaker commented
Bounty claimed at [https://opencollective.com/generator-jhipster/expenses/63101](https://opencollective.com/generator-jhipster/expenses/63101)

2022-02-03 09:35 UTC, pascalgrimaud commented
@beatfreaker : approved !