Init front jhipster lite
jhipster/jhipster-lite pull request #668
Opened 2022-02-11 15:41 UTC by nonomoho

Related #295

2022-02-11 16:00 UTC, nonomoho commented on jest.config.js
> +    '!**/*AsyncModule.ts',
Remove unused things

2022-02-11 17:17 UTC, pascalgrimaud commented
@nonomoho @seraphinandrieux : ping when it's ready for review

2022-02-11 17:25 UTC, nonomoho commented
It's ok, we reviewed it!

2022-02-11 20:14 UTC, pascalgrimaud requested changes

2022-02-11 20:14 UTC, pascalgrimaud commented on package.json
> +    "format": "prettier . --write",
is it the same thing than prettier:format ?

2022-02-11 20:14 UTC, pascalgrimaud commented on package.json
> +    "vue": "^3.2.25"
possible to use fixed version ?

2022-02-11 20:14 UTC, pascalgrimaud commented on src/main/webapp/app/common/primary/app/App.html
> +<div id="app">{{ jhipsterLite }}</div>
little bit strange to have this file: `App.html`
Is it intended ? should we include it directly in `App.vue` file ?

2022-02-11 20:14 UTC, pascalgrimaud commented on src/test/javascript/spec/common/primary/app/App.spec.ts
> +import { VueWrapper } from '@vue/test-utils';
maybe we could merge these 2 imports in 1 ?

2022-02-11 21:10 UTC, pascalgrimaud commented
another comment: we should include jest-sonar-reporter, otherwise, we won't be at 100% coverage in SonarCloud

2022-02-12 10:19 UTC, pascalgrimaud commented on package.json
> +    "format": "prettier . --write",
not important, can be changed later if needed

2022-02-12 10:19 UTC, pascalgrimaud commented on src/main/webapp/app/common/primary/app/App.html
> +<div id="app">{{ jhipsterLite }}</div>
not important, can be changed later if needed

2022-02-12 10:31 UTC, pascalgrimaud approved these changes

2022-02-12 10:31 UTC, merged

2022-02-14 13:06 UTC, seraphinandrieux commented
$250 bounty claim for https://github.com/jhipster/jhipster-lite/issues/295 
Link to open collective: https://opencollective.com/generator-jhipster/expenses/64192

2022-02-14 13:29 UTC, pascalgrimaud commented
@nonomoho : approved
@seraphinandrieux : approved

thanks for your hard work