ci: improved ci to not launch some tests.
jhipster/jhipster-lite pull request #6718
Opened 2023-06-29 14:42 UTC by zhyd1997

Close: https://github.com/jhipster/jhipster-lite/issues/6651

2023-06-30 05:19 UTC, pascalgrimaud commented
Thanks @zhyd1997 !
I'll have a look soon :-)

2023-06-30 05:29 UTC, pascalgrimaud requested changes

2023-06-30 05:29 UTC, pascalgrimaud commented on .github/workflows/github-actions.yml
> +          if [ "${{ env.md5sum_pom_xml }}" == "${{ steps.cache_md5sum.outputs.md5sum_pom_xml }}" ]; then
I don't think it's enough
We should compare the md5 of the generated project, including all existing files
Because if there is a change in package.json, with this solution, it won't be detect so no build

Some ideas which need to be discussed:
- generate a tar or zip, then calculate the md5
- use something like md5deep or checksumdir

2023-06-30 06:01 UTC, zhyd1997 commented on .github/workflows/github-actions.yml
> +          if [ "${{ env.md5sum_pom_xml }}" == "${{ steps.cache_md5sum.outputs.md5sum_pom_xml }}" ]; then
> We should compare the md5 of the generated project, including all existing files

Expensive Operation

2023-06-30 06:16 UTC, pascalgrimaud commented on .github/workflows/github-actions.yml
> +          if [ "${{ env.md5sum_pom_xml }}" == "${{ steps.cache_md5sum.outputs.md5sum_pom_xml }}" ]; then
locally, it's very fast, so not an expensive operation, just need to clear some files before
that's why it's not an easy ticket :)

2023-07-01 14:30 UTC, zhyd1997 commented on .github/workflows/github-actions.yml
> +          if [ "${{ env['md5sum_${{ matrix.app }}'] }}" == "${{ steps.cache_md5sum.outputs['MD5SUM_${{ matrix.app }}'] }}" ]; then
this line of code need to update:

Currently it equals to

`if [ "" == "" ]; then`

2023-07-07 09:42 UTC, zhyd1997 commented
Hi @pascalgrimaud 

Sorry 🙏  for long time no reply, seems that it's hard for me to access env variable in github actions.

Can someone continue to work on this task based on this commit and your idea? 👀

2023-07-07 09:44 UTC, pascalgrimaud commented
Thanks @zhyd1997 : fine, I'll improve your work as soon as I can

2023-12-08 05:20 UTC, closed without merging