WIP - Feat/issue/283 kafka broker
jhipster/jhipster-lite pull request #674
Opened 2022-02-12 13:36 UTC by fdelbrayelle

:warning: WIP - Do NOT merge

2022-02-12 15:11 UTC, pascalgrimaud commented
I convert this PR to draft, so no need to worry about merging it accidentaly

2022-02-12 15:46 UTC, pascalgrimaud requested changes

2022-02-12 15:46 UTC, pascalgrimaud commented
Have a look at generate.sh to add these 2 API, so it will be really tested

2022-02-14 13:20 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/application/KafkaApplicationService.java
> +  public void addProducer(final Project project) {
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:20 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +    projectRepository.template(
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:20 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +      "src/main/" + project.getPackageNamePath() + "/config",
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:20 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +      "src/main/" + project.getPackageNamePath() + "/service/kafka/producer",
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:20 UTC, fdelbrayelle commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +    result.put("kafka.bootstrap-servers", "localhost:9092");
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:20 UTC, fdelbrayelle commented on src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
> +    zookeeper:
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:20 UTC, fdelbrayelle commented on src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainServiceTest.java
> +public class KafkaDomainServiceTest {
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:20 UTC, fdelbrayelle commented on src/test/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/infrastructure/primary/rest/KafkaResourceIT.java
> +public class KafkaResourceIT {
Done : https://github.com/jhipster/jhipster-lite/pull/674/commits/018fa6547528fea30768829ecf1bca68dc635914

2022-02-14 13:23 UTC, fdelbrayelle commented
@pascalgrimaud Done too for `generate.sh`: https://github.com/jhipster/jhipster-lite/pull/674/commits/7080733708ca5c2a7712152035da909560834e17

2022-02-15 16:17 UTC, fdelbrayelle commented
- Add configuration in `application-test.properties`
- ExtendWith Test Contains in `@IntegrationTest`
- Add a new configuration for tests-ci
- Generated code coverage
- Rename `KafkaProperties` to `KafkaProducerProperties` (for the secondary and distinct with the consumer properties in the primary)

2022-02-27 14:21 UTC, pascalgrimaud commented
Don't forget to rebase and resolve conflict on generate.sh. FYI, this file has changed a lot

2022-03-05 17:20 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +elif [[ $application == 'kafkaapp' ]]; then
you need to update github-actions.yml file too :) otherwise, the CI won't use it

2022-03-05 18:47 UTC, fdelbrayelle commented on tests-ci/generate.sh
> +elif [[ $application == 'kafkaapp' ]]; then
It's already pushed:

```
      matrix:
        app:
          - fullapp
          - oauth2app
          - mysqlapp
          - mariadbapp
          - flywayapp
          - undertowapp
          - eurekaapp
          - consulapp
          - mongodbapp
          - angularapp
          - reactapp
          - vueapp
          - kafkaapp
```

2022-03-09 19:18 UTC, DanielFran commented on src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
> +  zookeeper:
Since zookeper has been deprecated in kafka 2.8.0, maybe we should use now by default the kraft mode?

https://github.com/confluentinc/cp-all-in-one/blob/7.0.1-post/cp-all-in-one-kraft/docker-compose.yml

2022-03-10 10:12 UTC, fdelbrayelle commented on src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
> +  zookeeper:
It's deprecated but not production ready AFAIK :thinking:

2022-03-10 10:50 UTC, DanielFran commented on src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
> +  zookeeper:
I agree, but docker configuration is just for testing, do not believe you will use the docker file for production ;)

https://developer.confluent.io/learn/kraft/
https://developer.confluent.io/podcast/apache-kafka-30-improving-kraft-and-an-overview-of-new-features

2022-03-10 11:03 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
> +  zookeeper:
Docker Configuration for Integration Tests should be similar, in term of architecture, to the production
If we decide to use Zookeeper+Kafka when running the application, we should do the same for Integration Tests.

So for now, I think we should keep Zookeeper+Kafka, nothing is urgent to remove Zookeeper later.
Then as soon it's ready for prod, then we'll do it.

2022-03-11 09:23 UTC, fdelbrayelle commented on src/main/resources/generator/server/springboot/broker/kafka/kafka.yml.mustache
> +  zookeeper:
Yep that's right @DanielFran.

OK @pascalgrimaud let's wait before to make a new PR to remove ZooKeeper when it will be ready with KRaft.

2022-03-18 16:07 UTC, DanielFran requested changes

2022-03-18 16:07 UTC, DanielFran commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/Kafka.java
> +  public static final String KAFKA_DOCKER_VERSION = "7.0.1";
You can now define docker image version directly from a dockerfile to be updated automatically: https://github.com/jhipster/jhipster-lite/pull/1010

2022-03-18 16:07 UTC, DanielFran commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +      final String secondaryKafkaPath = "technical/infrastructure/secondary/kafka";
Please use common constants (see https://github.com/jhipster/jhipster-lite/pull/1073)

2022-03-18 16:07 UTC, DanielFran commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/Zookeeper.java
> +  public static final String ZOOKEEPER_DOCKER_VERSION = "7.0.1";
You can now define docker image version directly from a dockerfile to be updated automatically: https://github.com/jhipster/jhipster-lite/pull/1010

2022-03-18 16:07 UTC, DanielFran commented on src/main/resources/generator/server/springboot/broker/kafka/KafkaTestContainerExtension.java.mustache
> +      final KafkaContainer kafkaContainer = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:7.0.1")).withNetwork(null);
You can now define docker image version directly from a dockerfile to be updated automatically: https://github.com/jhipster/jhipster-lite/pull/1010

2022-03-18 16:17 UTC, pascalgrimaud requested changes

2022-03-18 16:17 UTC, pascalgrimaud commented on README.md
> +- Apache Kafka as a Broker
you could create a new section `Broker` instead maybe ?

2022-03-18 16:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/domain/DefaultConfig.java
> +  public static final String DASHERIZED_BASE_NAME = "base-name";
not need, I'll explain why, in another comment

2022-03-18 16:17 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/broker/kafka/domain/KafkaDomainService.java
> +    result.put("kafka.consumer.'[group.id]'", DASHERIZED_BASE_NAME);
here, you want to get the baseName, in kebab case

You need to use something like:

```
String baseNameInKebab = WordUtils.kebabCase(project.getBaseName().orElse(DEFAULT_BASE_NAME))
```

2022-03-19 17:17 UTC, pascalgrimaud approved these changes

2022-03-19 17:18 UTC, merged

2022-04-18 19:07 UTC, fdelbrayelle commented
Bug bounty claimed here: https://opencollective.com/generator-jhipster/expenses/73079 

Thank you :pray:

2022-04-18 19:19 UTC, pascalgrimaud commented
@fdelbrayelle : approved, thanks for your work