Add eureka client
jhipster/jhipster-lite pull request #679
Opened 2022-02-12 18:05 UTC by Bolo89

- fix https://github.com/jhipster/jhipster-lite/issues/280

2022-02-12 18:26 UTC, pascalgrimaud commented
Thanks @Bolo89 : I'll review it soon

2022-02-13 18:15 UTC, pascalgrimaud commented
I think we should add some configs here: https://github.com/jhipster/jhipster-sample-app-microservice/blob/main/src/main/resources/config/application.yml#L27-L42

The current properties are not enough IMO

Currently:
![image](https://user-images.githubusercontent.com/9156882/153768281-84212a1d-ead1-4310-bf71-bae77b0ea9e8.png)

The instance id should be like this:
![image](https://user-images.githubusercontent.com/9156882/153768731-c2bfff6f-827f-4f14-b0dd-21fa3b4fd7ee.png)

2022-02-13 18:25 UTC, pascalgrimaud requested changes

2022-02-13 18:25 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/eureka/domain/EurekaDomainService.java
> +  }
I think this method should be smart, I mean:
- if the bootstrap.properties already exist, we should add the config in existing files
- if the file doesn't exist, we could create it like this

So I think the feature spring cloud config should be updated with the similar logic

2022-02-13 18:25 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/eureka/infrastructure/primary/EurekaResource.java
> +  @ApiResponse(responseCode = "500", description = "An error occurred while adding Spring Cloud Eureka Client config")
```suggestion
  @ApiResponse(responseCode = "500", description = "An error occurred while adding Spring Cloud Eureka Client")
```

2022-02-13 18:25 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/springcloud/eureka/infrastructure/primary/EurekaResourceIT.java
> +    Project project = ProjectDTO.toProject(projectDTO);
```suggestion
    ProjectDTO projectDTO = readFileToObject("json/chips.json", ProjectDTO.class).folder(tmpDirForTest());
    Project project = ProjectDTO.toProject(projectDTO);
```

2022-02-14 21:39 UTC, pascalgrimaud commented
@Bolo89 : don't hesitate to ping me if it's finished and it needed a 2nd review

2022-02-16 17:57 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/eureka/domain/EurekaDomainService.java
> +  }
done, for eureka, consul and spring cloud config

2022-02-17 08:42 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/springcloud/common/domain/SpringCloudCommonDomainService.java
> +  public static final String KEY_PROPERTY_SEPARATOR = "=";
I think we can move it to Constants

2022-02-17 08:43 UTC, pascalgrimaud submitted a review, later dismissed

2022-02-17 08:44 UTC, pascalgrimaud commented
needed some manuel tests from my side and it can be merged

2022-02-17 17:32 UTC, pascalgrimaud approved these changes

2022-02-17 21:23 UTC, merged

2022-02-17 21:23 UTC, pascalgrimaud commented
thanks a lot for the work here, @Bolo89 !

2022-02-26 09:14 UTC, Bolo89 commented
Bounty claimed at: https://opencollective.com/generator-jhipster/expenses/65313