Implementing keyboard navigation for Landscape screen
jhipster/jhipster-lite pull request #6815
Opened 2023-07-09 23:13 UTC by abdelfetah18

Fix #3151

2023-07-09 23:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=6815) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=6815) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=6815) it.</sub>

2023-07-09 23:15 UTC, abdelfetah18 commented
Hi,
i did implement the keyboard navigation feature as you can see in the video.



https://github.com/jhipster/jhipster-lite/assets/62770167/698a8f82-2d06-4c8a-9314-aa1380a49d6f


**CTRL** + **LeftArrow**: navigate to the first dependency.
**CTRL** + **RightArrow**: navigate to the first dependent.

**Enter** to toggle the Module.

**left arrow**, **right arrow**, **up arrow**, **down arrow** to navigate between modules.

is this the correct behavior ??

2023-07-10 04:10 UTC, DamnClin commented
Hello, thanks for your contribution! Space to toggle module seems more natural no?

The properties form navigation still works?

2023-07-10 11:14 UTC, abdelfetah18 commented
> Hello, thanks for your contribution! Space to toggle module seems more natural no?

you are right, space is better


> The properties form navigation still works?

yes

2023-07-10 11:17 UTC, DamnClin commented
I won't be able to review the code for a long time. @Gnuk any chance you can review this?

2023-07-10 11:59 UTC, Gnuk requested changes

2023-07-10 11:59 UTC, Gnuk commented on src/main/webapp/app/module/primary/landscape/Landscape.component.ts
> +      if (ArrowDown && keyboard_event.ctrlKey == false) landscapeNavigation.value?.goDown();
Maybe you can refactor this function and eventually split in multiple one because of the repetitions.

2023-07-10 11:59 UTC, Gnuk commented on src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
> +          const distance = Math.abs(module_html_element.getBoundingClientRect().y - current_module_html.getBoundingClientRect().y);
Maybe there is something to rework in this class because of multiple similar blocks.

2023-07-10 11:59 UTC, Gnuk commented on src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
> +      expect(applicationListener.removeEventListener.calledTwice).toBe(true);
It's really strange to have this average of tests and it not seems a lot relevant. Maybe you can add behaviors using cypress to have a better relevant coverage.

2023-07-10 12:09 UTC, abdelfetah18 commented on src/main/webapp/app/module/primary/landscape/Landscape.component.ts
> +      if (ArrowDown && keyboard_event.ctrlKey == false) landscapeNavigation.value?.goDown();
okay i will do that

2023-07-10 20:49 UTC, abdelfetah18 commented
I have pushed a new commits to fix problems you told me about,
and i implemented a tests.

2023-07-13 12:51 UTC, abdelfetah18 commented
Any updates ?

2023-07-14 09:41 UTC, DamnClin requested changes
Some refactoring to do. A global one (I don't add comment for every impacted line): create blocks for ifs, inlined if are really hard to pick

2023-07-14 09:41 UTC, DamnClin commented on src/main/webapp/app/module/primary/landscape/Landscape.component.ts
> +    const handle_keyboard = (event: Event): void => {
We try to keep our methods camelCase

2023-07-14 09:41 UTC, DamnClin commented on src/main/webapp/app/module/primary/landscape/Landscape.component.ts
> +    const handleNavigationKeys = (code: string, ctrlKey: boolean) => {
This looks a lot like something that case be refactorized using a union type of navigation. Can you try doing that?

And this needs a return type in the signature

2023-07-14 09:41 UTC, DamnClin commented on src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
> +    const element_index = next_level.elements.findIndex(element => {
This lambda is really hard to understand, I think this needs refactoring to ease readbility. Extracting methods to add business meaning can be an idea

2023-07-14 09:41 UTC, DamnClin commented on src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
> +    // Iterate throw Element and Modules until you get the smallest one.
If you feel need for a comment explaining what the code is doing that probably means you need a refactoring so the code is crystal clear :D

2023-07-14 09:41 UTC, DamnClin commented on src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
> +      await wrapper.vm.$nextTick();
probably not needed

2023-07-14 10:10 UTC, Gnuk commented
> cc @Gnuk can you make a review on that (following updates), I can find some time to do it in the upcoming days if needed.

Sorry I was busy and I'm busy until this weekend too.

I've just seen the message now and also the review. So thank you :)

2023-07-14 15:23 UTC, abdelfetah18 commented on src/main/webapp/app/module/primary/landscape/Landscape.component.ts
> +    const handle_keyboard = (event: Event): void => {
okay

2023-07-14 15:24 UTC, abdelfetah18 commented on src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
> +    const element_index = next_level.elements.findIndex(element => {
i will do that

2023-07-14 15:25 UTC, abdelfetah18 commented on src/main/webapp/app/module/primary/landscape/LandscapeNavigation.ts
> +    // Iterate throw Element and Modules until you get the smallest one.
i will try to make my code clear as much as possible

2023-07-14 15:29 UTC, abdelfetah18 commented on src/test/javascript/spec/module/primary/landscape/LandscapeComponent.spec.ts
> +      await wrapper.vm.$nextTick();
I will check that

2023-07-15 22:26 UTC, abdelfetah18 commented
Is this Refactorizing better ?
```typescript
type Navigation = "ArrowLeft" | "ArrowRight" | "ArrowUp" | "ArrowDown";
type NavigationAction = {
  [key in Navigation] : string
};

const isNavigation = (code: string) : code is Navigation => {
  return ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", "Space"].includes(code);
}

const handleNavigation = (code : Navigation, ctrl : boolean) : void => {
  if(!landscapeNavigation.value){
    return;
  }

  if(code as string === "Space"){
    toggleModule(landscapeNavigation.value.getSlug());
    return;
  }
  
  let navAction : NavigationAction = {
    ArrowUp: "goUp",
    ArrowDown: "goDown",
    ArrowLeft: ctrl ? "goToDependencie" : "goLeft",
    ArrowRight: ctrl ? "goToDependent" : "goRight"
  };

  landscapeNavigation.value[navAction[code] as keyof LandscapeNavigation]();
}

const handleKeyboard = (event: Event): void => {
  const keyboardEvent = event as KeyboardEvent;

  if(isNavigation(keyboardEvent.code) && landscapeNavigation.value){
    handleNavigation(keyboardEvent.code, keyboardEvent.ctrlKey);
    emphasizeModule(landscapeNavigation.value.getSlug());
  }
};
```

2023-07-16 07:57 UTC, DamnClin commented
Still some work to do, no need to cast your valuer as string and the actions can extracted but yep, I think it's way easier to understand, thanks for your work

2023-07-24 18:10 UTC, DamnClin approved these changes

2023-07-24 18:10 UTC, merged

2023-07-24 19:34 UTC, abdelfetah18 commented
> Congratz for your first contribution and sorry for the review delay :)

Thank you