feat: Add MongoDB Support
jhipster/jhipster-lite pull request #690
Opened 2022-02-13 09:37 UTC by juliensadaoui

Related to #421 

Add MongoDB Support with Spring Data

You can do:

- POST /api/projects/init
- POST /api/build-tools/maven
- POST /api/build-tools/maven
- POST /api/servers/spring-boot/mvc/web/tomcat
- POST /api/servers/spring-boot/databases/mongodb

2022-02-14 21:27 UTC, pascalgrimaud requested changes

2022-02-14 21:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/application/MongodbApplicationService.java
> +  }
not sure these methods are needed, only init is necessary I think

2022-02-14 21:27 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/infrastructure/config/MongodbBeanConfiguration.java
> +  public final SpringBootCommonService springBootCommonService;
change public to private

2022-02-14 21:28 UTC, pascalgrimaud requested changes

2022-02-14 21:28 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/application/MongodbApplicationServiceIT.java
> +    assertFileContent(
all these assert can be implemented in MongodbAssert, in static method. Then, it can be reused in MongodbResourceIT

2022-02-14 21:29 UTC, pascalgrimaud commented
can you add a new configuration in:
- new json file
- generate.sh
- github-actions.yml

So MongoDB will be really tested in CI

2022-02-14 21:37 UTC, pascalgrimaud requested changes

2022-02-14 21:37 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/mongodb/TestContainersSpringContextCustomizerFactory.java.mustache
> +import {{packageName}}.MongoDbTestContainerExtension;
```suggestion
import {{packageName}}.MongodbTestContainerExtension;
```

2022-02-14 21:37 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/mongodb/TestContainersSpringContextCustomizerFactory.java.mustache
> +      MongoDBContainer container = (MongoDBContainer) MongoDbTestContainerExtension.getThreadContainer().get();
```suggestion
      MongoDBContainer container = (MongoDBContainer) MongodbTestContainerExtension.getThreadContainer().get();
```

2022-02-14 21:37 UTC, pascalgrimaud commented
The generated code is not well convered:

```
[INFO] Analyzed bundle 'jhipster' with 19 classes
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.DateToZonedDateTimeConverter: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.DurationToLongConverter: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.LocalDateTimeToDateConverter: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.LongToDurationConverter: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.DateToLocalDateTimeConverter: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.DateToLocalDateConverter: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.LocalDateToDateConverter: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.mycompany.myapp.technical.infrastructure.secondary.mongodb.JSR310DateConverters.ZonedDateTimeToDateConverter: branches covered ratio is 0.50, but expected minimum is 1.00
```

2022-02-15 07:32 UTC, pascalgrimaud requested changes

2022-02-15 07:32 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/database/mongodb/MongodbDatabaseConfiguration.java.mustache
> +@EnableMongoRepositories({ "com.mycompany.myapp" })
Should be variable packageName

2022-02-15 08:55 UTC, juliensadaoui commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/application/MongodbApplicationService.java
> +  }
I think so, too. It's done.

2022-02-15 08:56 UTC, juliensadaoui commented on src/main/resources/generator/server/springboot/database/mongodb/TestContainersSpringContextCustomizerFactory.java.mustache
> +import {{packageName}}.MongoDbTestContainerExtension;
Done

2022-02-15 09:04 UTC, juliensadaoui commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/mongodb/infrastructure/config/MongodbBeanConfiguration.java
> +  public final SpringBootCommonService springBootCommonService;
done

2022-02-15 09:28 UTC, juliensadaoui commented
> Another comment:
> 
>     * I don't know if it's normal to be able to start the application, without starting MongoDB
> 
> 
> ```
> INFO] Attaching agents: []
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::                (v2.6.3)
> 
> 2022-02-14 22:54:14.900  INFO 15203 --- [           main] com.mycompany.myapp.JhipsterApp          : Starting JhipsterApp using Java 17.0.1 on xpspgr with PID 15203 (/home/pgrimaud/tmp/04-mongodb/target/classes started by pgrimaud in /home/pgrimaud/tmp/04-mongodb)
> 2022-02-14 22:54:14.903  INFO 15203 --- [           main] com.mycompany.myapp.JhipsterApp          : No active profile set, falling back to default profiles: default
> 2022-02-14 22:54:16.080  INFO 15203 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2022-02-14 22:54:16.080  INFO 15203 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.56]
> 2022-02-14 22:54:16.171  INFO 15203 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> 2022-02-14 22:54:16.951  INFO 15203 --- [           main] com.mycompany.myapp.JhipsterApp          : Started JhipsterApp in 2.561 seconds (JVM running for 2.891)
> 2022-02-14 22:54:16.960  INFO 15203 --- [           main] com.mycompany.myapp.JhipsterApp          : 
> ----------------------------------------------------------
>   Application 'jhipster' is running!
>   Local: 	http://localhost:8080/
>   External: 	http://127.0.1.1:8080/
>   Profile(s): 	[]
> ----------------------------------------------------------
> ^C[INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  8.296 s
> [INFO] Finished at: 2022-02-14T22:54:20+01:00
> [INFO] ------------------------------------------------------------------------
> 
> 22:54:20 in ~/tmp/04-mongodb on  main [!?] took 10s 
> ➜ docker ps -a
> CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
> 
> 22:54:22 in ~/tmp/04-mongodb on  main [!?]
> ```

It's normal because we don't use of spring data repositories in this generation. Unlike PosgreSQL or MySQL, Spring Data Mongodb don't connect to server without repositories

2022-02-15 17:17 UTC, pascalgrimaud approved these changes

2022-02-15 17:17 UTC, merged