Refactor RestAppPage formatting (#7033) - Improved  method with prope…
jhipster/jhipster-lite pull request #7052
Opened 2023-07-31 18:19 UTC by jayasekharreddy-telluri

…r line breaks and indentation

2023-08-01 17:53 UTC, DamnClin requested changes
You also need to rewrite your commit message

2023-08-01 17:53 UTC, DamnClin commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +public static <S, T> Rest{{baseName}}Page<T> from({{baseName}}Page<S> source, Function<S, T> mapper) {
still need a 2 spaces indentation for the whole methode

2023-08-04 10:36 UTC, pascalgrimaud commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +  Assert.notNull("source", source);
it is still not perfect, as you broke the format:

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/3dbcc612-3002-4394-8725-8cfb56c48637)

2023-08-04 11:00 UTC, jayasekharreddy-telluri commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +  Assert.notNull("source", source);
<img width="574" alt="image" src="https://github.com/jhipster/jhipster-lite/assets/123527399/4461fc75-de3a-4f69-b7d1-cbd699ee8b7a">
is the above thing is fine?

2023-08-04 12:23 UTC, pascalgrimaud commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +  Assert.notNull("source", source);
no, it's still wrong. You can follow the original ticket, the modification is really simple:
- see https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache#L35-L36
- add a empty line between l35 and l36
- add correct space at l36

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/3677f2ed-cd11-47d6-8bfc-1676403e614e)

In your PR, you modify the line 33 which is correct
Same modification for line 44, which is already correct

2023-08-05 04:22 UTC, jayasekharreddy-telluri commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +  Assert.notNull("source", source);
<img width="651" alt="image" src="https://github.com/jhipster/jhipster-lite/assets/123527399/bf359c14-bd61-498c-b4f3-07c5911f82f6">

 hi @pascalgrimaud  is that fine now?

2023-08-05 15:32 UTC, DamnClin commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +}
This closing bracket needs the two spaces :)

2023-08-05 17:23 UTC, pascalgrimaud commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +  Assert.notNull("source", source);
Still not. See my comment above :-)

2023-08-06 06:19 UTC, jayasekharreddy-telluri commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +}
<img width="637" alt="image" src="https://github.com/jhipster/jhipster-lite/assets/123527399/9fa27f79-d25f-4063-819c-6e19075d8977">

i hope now its ok 🙄?

2023-08-06 07:12 UTC, DamnClin commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +}
The screenshot is ok but you need to push your code

2023-08-06 07:37 UTC, pascalgrimaud commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +}
L33, 34, 35, 37 are still wrong for me

2023-08-06 07:42 UTC, jayasekharreddy-telluri commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +}
<img width="659" alt="image" src="https://github.com/jhipster/jhipster-lite/assets/123527399/f9c91c3a-a069-4020-89f7-51b7ab28ffd5">
 
now its correct?

2023-08-06 07:59 UTC, pascalgrimaud commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +}
Yes I think :-)

2023-08-06 09:23 UTC, pascalgrimaud approved these changes

2023-08-06 09:24 UTC, merged

2023-08-06 10:22 UTC, jayasekharreddy-telluri commented on src/main/resources/generator/server/pagination/rest/main/RestAppPage.java.mustache
> +}
finally completed😊