Gh codespace
jhipster/jhipster-lite pull request #708
Opened 2022-02-14 08:44 UTC by matthieulapatate

fix #662

2022-02-14 09:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=708) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=708) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=708) it.</sub>

2022-02-14 09:41 UTC, pascalgrimaud commented
@matthieulapatate : you commit with root user, so wrong config :)

2022-02-17 21:38 UTC, pascalgrimaud requested changes

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/domain/Codespace.java
> +public class Codespace {
useless class, can be deleted

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceDomainService.java
> +import static tech.jhipster.lite.generator.project.domain.Constants.MAIN_RESOURCES;
not used, can be removed

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/application/CodespaceApplicationService.java
> +package tech.jhipster.lite.generator.setup.codespace.application;
change location from codespace -> codespaces

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/application/CodespaceApplicationService.java
> +public class CodespaceApplicationService {
CodespaceApplicationService -> CodespacesApplicationService

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceDomainService.java
> +  public void addDocker(Project project) {
```suggestion
  public void addDockerfile(Project project) {
```

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceDomainService.java
> +  public void addJSON(Project project) {
```suggestion
  public void addConfig(Project project) {
```

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceService.java
> +package tech.jhipster.lite.generator.setup.codespace.domain;
```suggestion
package tech.jhipster.lite.generator.setup.codespaces.domain;
```

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceService.java
> +public interface CodespaceService {
```suggestion
public interface CodespacesService {
```

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/infrastructure/config/CodespaceBeanConfiguration.java
> +package tech.jhipster.lite.generator.setup.codespace.infrastructure.config;
```suggestion
package tech.jhipster.lite.generator.setup.codespaces.infrastructure.config;
```

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/infrastructure/primary/rest/CodespaceResource.java
> +  @Operation(summary = "Init", description = "Init Maven project with pom.xml and wrapper")
the summary is incorrect

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/infrastructure/primary/rest/CodespaceResource.java
> +  @ApiResponse(responseCode = "500", description = "An error occurred while initializing Maven project")
the description is incorrect

2022-02-17 21:38 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespace/infrastructure/primary/rest/CodespaceResource.java
> +  @GeneratorStep(id = "codespace")
```suggestion
  @GeneratorStep(id = "codespaces")
```

2022-02-17 21:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/application/CodespaceApplicationServiceIT.java
> +public class CodespaceApplicationServiceIT {
no need public

2022-02-17 21:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/application/CodespaceAssertFiles.java
> +
missing private constructor

2022-02-17 21:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/application/CodespaceApplicationServiceIT.java
> +import static tech.jhipster.lite.TestUtils.assertFileContent;
not used

2022-02-17 21:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceDomainServiceTest.java
> +public class CodespaceDomainServiceTest {
empty class ? no test ?

2022-02-17 21:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceTest.java
> +public class CodespaceTest {
useless, remove

2022-02-17 21:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/infrastructure/config/CodespaceBeanConfigurationIT.java
> +public class CodespaceBeanConfigurationIT {
remove public

2022-02-17 21:38 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/infrastructure/primary/rest/CodespaceResourceIT.java
> +public class CodespaceResourceIT {
remove public

2022-02-17 21:38 UTC, pascalgrimaud commented
More generally, plz rename codespace -> codespaces
See https://github.com/features/codespaces

2022-02-18 09:19 UTC, matthieulapatate commented on src/test/java/tech/jhipster/lite/generator/setup/codespace/domain/CodespaceDomainServiceTest.java
> +public class CodespaceDomainServiceTest {
Strange that coverage tests didn't detected that miss.

2022-02-18 10:23 UTC, pascalgrimaud requested changes

2022-02-18 10:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/domain/CodespacesDomainService.java
> +  public void addJSON(Project project) {
```suggestion
  public void addConfig(Project project) {
```

2022-02-18 10:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/domain/CodespacesDomainService.java
> +  public void addDocker(Project project) {
```suggestion
  public void addDockerfile(Project project) {
```

2022-02-18 10:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/infrastructure/primary/rest/CodespacesResource.java
> +  @Operation(summary = "Github Codespaces", description = "Init github codespace configuration files")
```suggestion
  @Operation(summary = "GitHub Codespaces", description = "Init GitHub Codespaces configuration files")
```

2022-02-18 10:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/infrastructure/primary/rest/CodespacesResource.java
> +  @ApiResponse(responseCode = "500", description = "An error occurred while initializing Github Codespace files.")
```suggestion
  @ApiResponse(responseCode = "500", description = "An error occurred while initializing GitHub Codespace files.")
```

2022-02-18 10:23 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/infrastructure/primary/rest/CodespacesResource.java
> +  @GeneratorStep(id = "github codespaces")
```suggestion
  @GeneratorStep(id = "github-codespaces")
```

2022-02-18 10:23 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespaces/application/CodespacesApplicationServiceIT.java
> +public class CodespacesApplicationServiceIT {
```suggestion
class CodespacesApplicationServiceIT {
```

2022-02-18 10:23 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespaces/application/CodespacesAssertFiles.java
> +
missing private constructor

2022-02-18 10:23 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/setup/codespaces/domain/CodespacesDomainServiceTest.java
> +public class CodespacesDomainServiceTest {
```suggestion
class CodespacesDomainServiceTest {
```

2022-02-18 15:50 UTC, pascalgrimaud requested changes

2022-02-18 15:50 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/application/CodespacesApplicationService.java
> +  public CodespacesApplicationService(CodespacesService codespaceService) {
```suggestion
  public CodespacesApplicationService(CodespacesService codespacesService) {
```

2022-02-18 15:50 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/application/CodespacesApplicationService.java
> +    this.codespacesService = codespaceService;
```suggestion
    this.codespacesService = codespaceServices;
```

2022-02-18 15:50 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/setup/codespaces/infrastructure/primary/rest/CodespacesResource.java
> +  @ApiResponse(responseCode = "500", description = "An error occurred while initializing GitHub Codespace files.")
```suggestion
  @ApiResponse(responseCode = "500", description = "An error occurred while initializing GitHub Codespaces files.")
```

2022-02-19 09:02 UTC, pascalgrimaud commented
I fixed the last items and committed directly to your branch.
Then, I managed to test the code:
- generate a project
- add Codespaces
- go into .devcontainer folder
- build the image: `docker build -t jhipster/codespaces . --build-arg NODE_VERSION='lts/*'`
- start the container: `docker run --rm -it jhipster/codespaces bash`
- then, I manage to check the different version of tools:

![image](https://user-images.githubusercontent.com/9156882/154794206-6caa7004-f653-414c-ab11-18e5dff9a8af.png)

2022-02-19 09:22 UTC, pascalgrimaud approved these changes

2022-02-19 09:22 UTC, merged