feat: Add Github Actions support
jhipster/jhipster-lite pull request #717
Opened 2022-02-14 16:25 UTC by Hawkurane

Fixes https://github.com/jhipster/jhipster-lite/issues/422

You can do:

POST /api/projects/init
POST /api/github-actions/init

2022-02-14 19:24 UTC, pascalgrimaud requested changes

2022-02-14 19:24 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/infrastructure/config/GithubActionsBeanConfiguration.java
> +import org.springframework.objenesis.SpringObjenesis;
Strange import

2022-02-14 19:24 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/infrastructure/primary/rest/GithubActionsResource.java
> +  @GeneratorStep(id = "init")
Should be github-actions, as init is already used

2022-02-14 19:24 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/domain/GithubActionsDomainService.java
> +    projectRepository.template(project, SOURCE, GITHUB_ACTIONS_YML, GITHUB_ACTIONS_FOLDER);
You forgot to add setup config
See https://github.com/jhipster/jhipster-lite/blob/main/.github/actions/setup/action.yml

2022-03-05 11:15 UTC, pascalgrimaud commented
I'm changing it to draft, as there are still some work to do

2022-03-05 16:28 UTC, Hawkurane commented
Hello @pascalgrimaud i've just pushed the changes concerning the reviews you've made me.

Concerning the generate.sh i'm unsure how to approach this since I don't think there's any real way of checking generated github-actions files besides visually looking the website itself...

If you have any advice LMK :)

2022-03-05 16:43 UTC, pascalgrimaud commented
Thanks a lot @Hawkurane 

About real final tests, I plan to automate a generated project + push to a repository, so it will trigger github actions there :-)

2022-03-05 17:14 UTC, pascalgrimaud requested changes

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/domain/GithubActionsService.java
> +  void init(Project project);
I'd rename to: `addGitHubActionsForMaven`

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/domain/GithubActionsService.java
> +  void addYmls(Project project);
not sure we need this

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/infrastructure/primary/rest/GithubActionsResource.java
> +@Tag(name = "Github Actions")
```suggestion
@Tag(name = "GitHub Actions")
```

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/infrastructure/primary/rest/GithubActionsResource.java
> +  @Operation(summary = "Init Github Actions YML file")
```suggestion
  @Operation(summary = "Add GitHub Actions YML files")
```

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/infrastructure/primary/rest/GithubActionsResource.java
> +  @ApiResponse(responseCode = "500", description = "An error occurred while initializing the github-actions.yml.mustache file")
```suggestion
  @ApiResponse(responseCode = "500", description = "An error occurred while adding GitHub Actions")
```

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/infrastructure/primary/rest/GithubActionsResource.java
> +  @PostMapping("/init")
```suggestion
  @PostMapping("/maven")
```

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/githubactions/infrastructure/primary/rest/GithubActionsResource.java
> +  public void init(@RequestBody ProjectDTO projectDTO) {
I'd rename to `addGitHubActionsForMaven`, but if you don't like it, simply ignore my comment

2022-03-05 17:14 UTC, pascalgrimaud commented on src/main/resources/generator/githubactions/.github/workflows/github-actions.yml.mustache
> +        ./mvnw clean verify
Problem with indent

```suggestion
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:{{=<% %>=}}
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Test: run tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
```

2022-03-05 17:29 UTC, pascalgrimaud commented
and your code works well (after fixing the indent): see https://github.com/pascalgrimaud/jhlite-sample-app/pull/1

2022-03-05 19:01 UTC, Hawkurane commented
@pascalgrimaud thank you for the review,
In the end, i've added a callApi "/api/github-actions/maven" step every time there's a call for the maven build-tools. WDYT?

2022-03-05 19:12 UTC, pascalgrimaud commented
@Hawkurane : I'd prefer to put it in `fullapp` as it's specific, but in the end, it won't impact the build, so it's fine, like you wish :)

2022-03-05 19:12 UTC, pascalgrimaud approved these changes

2022-03-05 19:12 UTC, merged