Pr/419
jhipster/jhipster-lite pull request #722
Opened 2022-02-15 08:12 UTC by seraphinandrieux

Still not finished.
Has to do same with postgre sql and fix IT orders properties.

2022-02-15 08:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=722) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=722) it.</sub>

2022-02-15 08:14 UTC, seraphinandrieux commented
- relates #419

2022-02-15 08:42 UTC, pascalgrimaud commented
@seraphinandrieux :
- you need to rebase against upstream remote, as your branch is not up-to-dated
- after that, you need to solve some conflict
- can you update the title too plz?

2022-02-15 08:46 UTC, seraphinandrieux commented
> @seraphinandrieux :
> 
> * you need to rebase against upstream remote, as your branch is not up-to-dated
> * after that, you need to solve some conflict
> * can you update the title too plz?

 Totally agree,
 I just pull requested if some people want to check => I will do it in the day.
 Sorry about title, I'm fixing that right now

2022-02-15 17:33 UTC, pascalgrimaud requested changes

2022-02-15 17:33 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/database/common/domain/CommonDatabase.java
> +package tech.jhipster.lite.generator.server.springboot.database.common.domain;
There is already an existing database/sqlcommon : maybe we should put your code inside this context, instead of creating a new one?

2022-02-15 17:33 UTC, pascalgrimaud commented on pom.xml
> +          <source>16</source>
why this change?

2022-02-16 08:28 UTC, seraphinandrieux commented
PR still not ready for reviewing.

I still have to fix 1 IT for PostgreSQL when initializing => It seems to return a 500 have to investigate why.
Could extract some duplicated code between MySQL.java and PostgreSql.java into CommonDatabase

2022-02-17 07:36 UTC, pascalgrimaud commented
Thanks @seraphinandrieux : I'll review it soon

2022-02-19 08:46 UTC, pascalgrimaud commented
As discussed together:
- the logic should stay in PostgreSQL and MySQL
- only extract in Sql Common the properties (jpa, hibernate, etc), the common lib

The work can be done in different smalls PR.

The reason is mainly for maintenance:
- when someone wants to improve or fix PostgreSQL part, he/she doesn't need to worry about other database (MySQL, MariaDB etc)
- it's important to not do the same mistakes than in generator-jhipster by regrouping all these technologies together, and having complex templates / complex logics, forcing the contributor to test all databases when only improving 1 single technology

2022-02-20 10:10 UTC, seraphinandrieux commented
@pascalgrimaud I did as discussed in this MR the refacto.
For now, it should be ok, please could you review it and check if I missed something.

Thx :)

2022-02-20 11:28 UTC, pascalgrimaud commented
Thanks @seraphinandrieux I'll try to review it asap :-)

2022-02-21 13:05 UTC, pascalgrimaud commented
@seraphinandrieux : the coverage is at 99.97%, probably missing private constructor in SQLCommon :)

2022-02-21 13:37 UTC, seraphinandrieux commented
> 
U right, intelliJ didn't detected, next time I'll run sonar analysis :)

2022-02-21 22:05 UTC, pascalgrimaud approved these changes

2022-02-21 22:13 UTC, merged

2022-02-22 08:12 UTC, seraphinandrieux commented
$200 bounty claimed : https://opencollective.com/generator-jhipster/expenses/64890

2022-02-22 08:12 UTC, pascalgrimaud commented
@seraphinandrieux : approved