okta platinum sponser removed
jhipster/jhipster-lite pull request #7224
Opened 2023-08-20 05:49 UTC by sagar-subedi

Fixes #7223: Removes Okta from platinum section of sponsors in Readme.md

2023-08-20 05:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=7224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=7224) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=7224) it.</sub>

2023-08-21 14:32 UTC, pascalgrimaud requested changes
you can completely delete the `### Platinum Sponsors` section, including table of Okta

2023-08-21 14:32 UTC, pascalgrimaud commented on README.md
> -      </td>
wrong sponsor, it's okta, not entando

2023-08-21 17:06 UTC, sagar-subedi commented
okta along with the who platinum sponsor removed, and entando is left untouched.

2023-08-21 17:06 UTC, sagar-subedi commented
*whole

2023-08-22 05:50 UTC, pascalgrimaud commented on README.md
> +     <td align="center" valign="middle">
```suggestion
      <td align="center" valign="middle">
```

2023-08-22 09:19 UTC, pascalgrimaud requested changes

2023-08-22 09:19 UTC, pascalgrimaud commented on README.md
```suggestion
### Gold Sponsors

```

2023-08-22 11:12 UTC, pascalgrimaud approved these changes

2023-08-22 13:09 UTC, pascalgrimaud commented
Thanks and congrats for your 1st contribution @sagar-subedi

2023-08-22 13:09 UTC, merged

2023-08-22 13:44 UTC, sagar-subedi commented
Feels like a great beginning to my open source journey. Thanks to the community.