Angular: use single version in dependencies
jhipster/jhipster-lite pull request #7397
Opened 2023-09-05 22:04 UTC by murdos

Fixes #3836

2023-09-06 06:13 UTC, pascalgrimaud requested changes

2023-09-06 06:13 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/module/domain/packagejson/PackageJsonDependency.java
> +  public boolean equals(Object obj) {
You can exclude it from coverage

2023-09-06 06:13 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/module/domain/packagejson/PackageJsonDependency.java
> +  @Override
Same, exclude it

2023-09-06 06:13 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/module/domain/packagejson/PackageJsonDependency.java
> +  @Override
Same, exclude it too

2023-09-06 20:58 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/domain/packagejson/PackageJsonDependency.java
> +  @Override
Done!

2023-09-07 12:13 UTC, pascalgrimaud approved these changes

2023-09-07 12:13 UTC, merged