Add styling in index html of vue generated project
jhipster/jhipster-lite pull request #749
Opened 2022-02-16 11:40 UTC by matthieulapatate

fix #721

2022-02-17 07:39 UTC, seraphinandrieux requested changes

2022-02-17 07:39 UTC, seraphinandrieux commented on src/main/java/tech/jhipster/lite/generator/client/vite/vue/core/infrastructure/primary/rest/ViveVueResource.java
> +  @Operation(summary = "Add some style to index page")
You should explain than you also init Vue + vite?

Here it suggests you already had init the project

2022-02-17 07:39 UTC, seraphinandrieux commented on src/test/java/tech/jhipster/lite/generator/client/vite/vue/core/domain/ViteVueDomainServiceTest.java
> +  void shouldAddStyledViteVue() {
This test is not really finished.

Here you check no exception, it could happens when the method do just nothing.
You should verify the correct port are called with arguments you specified in your method

2022-02-17 07:39 UTC, seraphinandrieux commented on src/test/java/tech/jhipster/lite/generator/client/vite/vue/core/infrastructure/primary/rest/ViveVueResourceIT.java
> +  void shouldAddStyledViteVue() throws Exception {
Same here, especially an integration test, in this test you have to check if the specif files related to styled vue are generated.

So first step to check if the status is OK is done perfect, now go further and assert the files are generated with correct content :)

2022-02-18 19:19 UTC, pascalgrimaud commented
I'm closing this, in favor of https://github.com/jhipster/jhipster-lite/pull/762
I took your commits in my other PR

2022-02-18 19:19 UTC, closed without merging

2022-02-18 19:20 UTC, pascalgrimaud commented
The problem is because of `main` branch, so I couldn't commit into your branch to improve it