#743 add vite react
jhipster/jhipster-lite pull request #750
Opened 2022-02-16 14:30 UTC by flcarre

realted to #743 

- POST /api/projects/init
- POST /api/vite/react
- npm i
- npm run dev

2022-02-16 15:08 UTC, pascalgrimaud requested changes

2022-02-16 15:08 UTC, pascalgrimaud commented on package.json
> +    "react": "^17.0.2",
wrong place, it should not be in main package.json, used by the generator

2022-02-16 15:08 UTC, pascalgrimaud commented on package.json
> +    "@vitejs/plugin-react": "^1.2.0",
wrong place, it should not be in main package.json, used by the generator

2022-02-16 15:10 UTC, pascalgrimaud commented
Could you add a new config here:
- new json here: https://github.com/jhipster/jhipster-lite/tree/main/tests-ci/config
- new config in https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh
- and new config in github actions: :https://github.com/jhipster/jhipster-lite/blob/main/.github/workflows/github-actions.yml#L96-L101

So we are sure Vite/React is tested in CI

2022-02-17 09:49 UTC, flcarre commented on package.json
> +    "@vitejs/plugin-react": "^1.2.0",
Ok, vitejs/plugin-vue is in the main package.json, is this a mistake ?

2022-02-17 09:49 UTC, flcarre commented on package.json
> +    "react": "^17.0.2",
Vue is in the main package.json, is this a mistake ?

2022-02-17 09:53 UTC, pascalgrimaud commented on package.json
> +    "@vitejs/plugin-react": "^1.2.0",
no, because the generator contains a front part with Vite+Vue! We'll build a front part to replace swagger, so the work already started.
There are 2 distinct subjects:
- the generator with front part to replace swagger (you can check at http://localhost:7471)
- generate the front part in a new project (angular, react, vite/vue, etc.)

2022-02-17 09:57 UTC, flcarre commented
> 

I add it in generate.sh but i don't know how to do in the 2 others config, can i have an exemple ?

2022-02-17 10:02 UTC, pascalgrimaud commented
> > 
> 
> I add it in generate.sh but i don't know how to do in the 2 others config, can i have an exemple ?

1st part
- duplicate one file in https://github.com/jhipster/jhipster-lite/tree/main/tests-ci/config and edit it
- be careful on the path value, and the name of the json file (should be similar)

2nd part
- add the new entry here: https://github.com/jhipster/jhipster-lite/blob/main/.github/workflows/github-actions.yml#L96-L101

2022-02-17 10:05 UTC, flcarre commented
> 1st part
> 
> * duplicate one file in https://github.com/jhipster/jhipster-lite/tree/main/tests-ci/config and edit it
> * be careful on the path value, and the name of the json file (should be similar)
> 
> 2nd part
> 
> * add the new entry here: https://github.com/jhipster/jhipster-lite/blob/main/.github/workflows/github-actions.yml#L96-L101

so i create a config, and i have to add this config in github-actions in generation/strategy/matrix/app ? the name of the config file must be something like ```tomcat-vite-react``` ?

2022-02-17 10:06 UTC, flcarre commented on package.json
> +    "@vitejs/plugin-react": "^1.2.0",
ok got it !

2022-02-17 10:08 UTC, pascalgrimaud commented
> so i create a config, and i have to add this config in github-actions in generation/strategy/matrix/app ? the name of the config file must be something like `tomcat-vite-react` ?

Yes, sounds good :)

2022-02-17 10:54 UTC, pascalgrimaud commented on package.json
> +    "axios": "^0.26.0",
plz revert this, using `^` is a pain, in Node ecosystem, we prefer using fixed version

2022-02-17 11:33 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/vite/react"
in an existing project, you can't add vue + react at the same time. You need to create a new config here

2022-02-18 09:49 UTC, flcarre commented
i guess i forgot something in the config but i can't get it

2022-02-19 06:43 UTC, pascalgrimaud commented
Some conflict to resolve

2022-02-19 07:09 UTC, pascalgrimaud commented
Thanks a lot for your hard work here @flcarre 
I'm preparing right now a new release of JHipster Lite v0.0.10, and I'll review this one soon. It means, it can be included in the next release v0.0.11 :)

2022-02-19 07:42 UTC, flcarre commented
Nice 🙂

2022-02-19 10:20 UTC, pascalgrimaud commented
I didn't finish to test it, but I have already 2 comments:
- after building, there is a generated file at root folder. The target folder should be changed I think
- need to add index.tsx to Sonar ignore, as it is not needed in coverage, like index.ts for Angular and Vue

2022-02-19 10:41 UTC, flcarre commented
> * need to add index.tsx to Sonar ignore, as it is not needed in coverage, like index.ts for Angular and Vue

I'm not sure to understand, i need to exclude it somewhere else of jest.config.js ?

`  collectCoverageFrom: [
    'src/main/webapp/**/*.{js,ts,vue}',
    '!src/main/webapp/**/*.component.ts',
    '!src/main/webapp/app/main.ts',
    '!**/*.d.ts',
  ],`

2022-02-19 11:40 UTC, pascalgrimaud commented
The exclusion for Sonar to add is here: https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/sonar/sonar-fullstack-project.properties.mustache#L17

2022-02-19 18:08 UTC, pascalgrimaud requested changes

2022-02-19 18:08 UTC, pascalgrimaud commented on src/main/resources/generator/client/vite/react/src/test/javascript/spec/common/primary/app/App.test.tsx.mustache
> +
empty line, can be removed

2022-02-19 18:08 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/client/vite/react/core/application/ViteReactAssert.java
> +    assertFileContent(project, PACKAGE_JSON, "vite" + DQ + ": ");
could use something like https://github.com/jhipster/jhipster-lite/blob/main/src/test/java/tech/jhipster/lite/generator/client/vite/vue/core/application/ViteVueAssert.java#L16-L17

So it will reduce the code here

2022-02-19 18:08 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot/mvc/web/tomcat"
can be changed to simply `springboot` (which is a new function)

2022-02-19 18:08 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/servers/spring-boot"
duplicated part, tomcat-mysql-ehcachexml is already defined
It's probably because of merge conflict, can you remove it plz ?

2022-02-19 18:08 UTC, pascalgrimaud commented on src/main/resources/generator/dependencies/vite/react/package.json
> +{
This file is really important, as it contains all dependencies related to React. But it needed to be updated automatically by dependabot. For that, you need to add a new section in `dependabot.yml` file. See similar for Vite/Vue: https://github.com/jhipster/jhipster-lite/blob/main/.github/dependabot.yml#L55-L61

2022-02-19 19:15 UTC, pascalgrimaud requested changes

2022-02-19 19:15 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/vite/react/core/domain/ViteReact.java
> +      Map.entry("vite-env.d.ts", "src/main/webapp/app"),
extract src/main/webapp/app to a variable -> it's for fixing code smells with Sonar

2022-02-20 06:09 UTC, pascalgrimaud commented on src/main/resources/generator/client/vite/react/src/test/javascript/spec/common/primary/app/App.test.tsx.mustache
> +})
It was not the end of line, but the empty line 14 to remove (which would be removed by prettier too)

2022-02-20 06:11 UTC, pascalgrimaud commented on tests-ci/generate.sh
> -elif [[ $filename == 'springboot' ]]; then
The line 85 and 86 should be kept :-)
This config is not used in CI but can be used locally as I do

2022-02-20 07:05 UTC, pascalgrimaud approved these changes

2022-02-20 07:13 UTC, merged

2022-02-20 07:13 UTC, pascalgrimaud commented
Thanks and congrats for your contribution @flcarre

2022-02-21 16:18 UTC, flcarre commented
https://opencollective.com/generator-jhipster/expenses/64816

2022-02-21 16:21 UTC, pascalgrimaud commented
@flcarre : approved :)