Add svelte kit
jhipster/jhipster-lite pull request #760
Opened 2022-02-18 15:49 UTC by flcarre

related to #746 
 
- POST /api/projects/init
- POST /api/svelte
- npm i
- npm run dev

2022-02-20 07:38 UTC, flcarre commented
i can't add a reviewer @pascalgrimaud but i think this pr is ok

2022-02-20 08:11 UTC, pascalgrimaud commented
Ok, I'll review it soon :-)

2022-02-24 15:39 UTC, flcarre commented
> @flcarre : can you resolve the conflict plz?

done !

2022-02-24 15:43 UTC, pascalgrimaud commented
Thanks @flcarre : for your information, I'm preparing a new release with React. The next one will include Svelte ;)

2022-02-24 15:49 UTC, pascalgrimaud requested changes

2022-02-24 15:49 UTC, pascalgrimaud commented on tests-ci/config/tomcat-svelte.json
> +      "packageName": "tech.jhipster.beer"
```suggestion
    "folder": "/tmp/jhlite/svelteapp",
    "generator-jhipster": {
      "projectName": "SvelteApp Project",
      "baseName": "svelteapp",
      "packageName": "tech.jhipster.svelteapp"
```

2022-02-24 15:49 UTC, pascalgrimaud commented on tests-ci/config/tomcat-svelte.json
> +      "packageName": "tech.jhipster.beer"
you need to rename this file to svelteapp.json too

2022-02-24 15:51 UTC, pascalgrimaud commented
In the meantime, to keep consistency, can you rework to have similar home page plz ?

![image](https://user-images.githubusercontent.com/9156882/155558854-9305a3a3-c0c3-46fe-8ae7-1be45a6cd526.png)

![image](https://user-images.githubusercontent.com/9156882/155558926-aa89cb48-dd88-4635-9548-591b8dc25bcc.png)

2022-02-25 08:27 UTC, flcarre commented
where can i find the jhipster logo in orange ?

2022-02-25 09:11 UTC, pascalgrimaud commented
Just added here:
- https://github.com/jhipster/jhipster-artwork/pull/20
- available at https://github.com/jhipster/jhipster-artwork/tree/main/logos/lite

2022-02-25 16:33 UTC, flcarre commented
i can build on my computer, maybe i missed the ci config ?

2022-02-25 16:37 UTC, pascalgrimaud requested changes

2022-02-25 16:37 UTC, pascalgrimaud commented on tests-ci/config/svelteapp.json
> +    "folder": "/tmp/jhlite/tomcat-svelte",
```suggestion
    "folder": "/tmp/jhlite/svelteapp",
```

2022-02-25 16:37 UTC, pascalgrimaud commented on tests-ci/config/svelteapp.json
> +      "packageName": "tech.jhipster.beer"
```suggestion
      "projectName": "SvelteApp Project",
      "baseName": "svelteapp",
      "prettierDefaultIndent": 2,
      "packageName": "tech.jhipster.svelteapp"
```

2022-02-27 06:36 UTC, pascalgrimaud commented
@flcarre : can you update your branch with upstream main plz? Lot of improvements have been done in the CI and it will impact your modification in generate sh file

2022-02-27 06:39 UTC, flcarre commented
need i to separate styled home page to empty home page ?

2022-02-27 06:46 UTC, pascalgrimaud commented
I don't understand exactly the question.

Do you mean 2 different pull requests ? -> as you wish, you can do the code here

Do you mean 2 different api ? -> yes, as it is done with other fronts

2022-02-27 06:49 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +elif [[ $filename == 'svelteapp' ]]; then
The variable has been renamed to $application

2022-02-27 06:53 UTC, flcarre commented
> Do you mean 2 different api ? -> yes, as it is done with other fronts

Ok i'll do it so

2022-02-27 14:16 UTC, pascalgrimaud requested changes

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +      getPath(SOURCE, "src/tests/spec/common/primary/app"),
Should be test, without additional 's'

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +      "src/tests/javascript/spec/common/primary/app"
Same, no 's' in test

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +    String destinationPrimary = "src/main/webapp/app/common/primary/app";
This path can be a constant, probably the reason of sonar code smells in CI

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +    String destinationAssets = "src/main/webapp/assets";
Same comment about assets, maybe constant to clean sonar code smell

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/resources/generator/client/svelte/.prettierrc
> +	"useTabs": true,
The init already generates a prettierrc file, no need this one

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/resources/generator/client/svelte/babel.config.cjs
> +    presets: [['@babel/preset-env', { targets: { node: 'current' } }], ['@babel/preset-typescript', { targets: { node: 'current' } }]]
Just a question. Do we really need babel?
Another comment : missing format (indent) here

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/resources/generator/client/svelte/src/main/webapp/routes/index.svelte.mustache
> +    import App from '../app/common/primary/app/App.svelte';
Format / indent

2022-02-27 14:16 UTC, pascalgrimaud commented on src/main/resources/generator/client/svelte/src/tests/spec/common/primary/app/App.spec.ts.mustache
> +    const { container } = render(App);
Format / indent

2022-02-27 14:16 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/client/svelte/core/infrastructure/primary/rest/SvelteResourceIT.java
> +}
Missing test for the other api

2022-02-27 14:16 UTC, pascalgrimaud commented on tests-ci/config/svelteapp.json
> +    "prettierDefaultIndent": 2,
This prettier config can be removed (see other config like vueapp)

2022-02-27 17:20 UTC, pascalgrimaud requested changes

2022-02-27 17:20 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +      "type": "module",
because of this, I can't do a single git commit. There are a lot of error:

```
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/tmp/jhlite/svelteapp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///tmp/jhlite/svelteapp/.lintstagedrc.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadConfig (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/loadConfig.js:72:20)
    at async searchConfig (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/getConfigGroups.js:78:34)
    at async getConfigGroups (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/getConfigGroups.js:97:3)
    at async runAll (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/runAll.js:122:24)
    at async lintStaged (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/index.js:58:17)
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/tmp/jhlite/svelteapp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///tmp/jhlite/svelteapp/.lintstagedrc.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadConfig (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/loadConfig.js:72:20)
    at async searchConfig (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/getConfigGroups.js:78:34)
    at async getConfigGroups (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/getConfigGroups.js:97:3)
    at async runAll (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/runAll.js:122:24)
    at async lintStaged (file:///tmp/jhlite/svelteapp/node_modules/lint-staged/lib/index.js:58:17)
Configuration could not be found.
husky - pre-commit hook exited with code 1 (error)
```

2022-02-27 17:20 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "build", "svelte-kit build",
the build does not generate file in target/classes/static, so the current app doesn't work with java backend

2022-02-27 17:20 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "dev", "svelte-kit dev",
need to add "start" alias too, which will do the same thing than "dev"

it should use the localhost:9000 to be consistent with other front too

2022-02-27 17:21 UTC, pascalgrimaud commented
strange display of application too:

![image](https://user-images.githubusercontent.com/9156882/155892575-6b92da98-e95e-41cd-99a5-b1dd79cb2d0e.png)

2022-02-28 06:00 UTC, flcarre commented on src/main/resources/generator/client/svelte/src/tests/spec/common/primary/app/App.spec.ts.mustache
> +    const { container } = render(App);
where ?

2022-02-28 06:03 UTC, flcarre commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "dev", "svelte-kit dev",
both "start" and "dev" should use port 9000 ?

2022-02-28 06:08 UTC, pascalgrimaud commented on src/main/resources/generator/client/svelte/src/tests/spec/common/primary/app/App.spec.ts.mustache
> +    const { container } = render(App);
The default indent should be 2 spaces, not 4

2022-02-28 06:10 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "dev", "svelte-kit dev",
Yes, generator-jhipster uses this port 9000 for the front, so I'd like to be consistent

2022-02-28 06:20 UTC, flcarre commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +      "type": "module",
how to reproduce  ?

2022-03-01 06:29 UTC, flcarre commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "build", "svelte-kit build",
We'll need to wait this issue closed: https://github.com/sveltejs/kit/issues/4052, any other idea ?

2022-03-01 06:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "build", "svelte-kit build",
@vishal423 : an idea about this? How did you solve this issue in your blueprint?

2022-03-01 06:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "build", "svelte-kit build",
@flcarre : you can try to have a look at https://github.com/jhipster/jhipster-sample-app-svelte, as I'm on phone, it's hard to try to find the solution :-D

2022-03-01 06:50 UTC, pascalgrimaud commented
@flcarre : you still have prettier errors.

To check error: `npm run prettier:check`
To format: `npm run prettier:format`

Anyway, it should format automatically when you commit, unless you use different tools in IDE or something else, which didn't trigger the git commit hook

2022-03-01 06:59 UTC, flcarre commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "build", "svelte-kit build",
ok find the solution thx !

2022-03-04 17:20 UTC, pascalgrimaud commented
I'm reviewing this, but I don't know if I should merge this, as you told me you won't probably have time to maintain it, @flcarre 

What do you think @vishal423 ?

2022-03-04 17:23 UTC, pascalgrimaud commented
I didn't manage to test it properly. To reproduce my issue:

- start JHipster Lite: `./mvnw spring-boot:run`
- generate svelteapp: `./tests-ci/generate.sh svelteapp`
- go into svelteapp folder: `cd /tmp/jhlite/svelteapp/`
- launch install: `npm i`
- commit: `git init && git add . && git commit -m 'init'`

Here the errors:

![image](https://user-images.githubusercontent.com/9156882/156811593-8dad386a-3625-4a66-b717-76e17e1736cc.png)

2022-03-04 17:34 UTC, pascalgrimaud requested changes

2022-03-04 17:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +        "check,watch", "svelte-check --tsconfig ./tsconfig.json --watch",
maybe typo? should be `check:watch` instead?

2022-03-04 17:34 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/client/svelte/core/domain/SvelteDomainService.java
> +      "type": "module",
didn't see your comment before. Generate a project, launch npm install, then just try to commit

2022-03-04 17:34 UTC, pascalgrimaud commented on src/main/resources/generator/client/svelte/src/main/webapp/routes/index.svelte.mustache
> +
remove this 1st empty line

2022-03-04 17:34 UTC, pascalgrimaud commented on src/main/resources/generator/client/svelte/src/test/spec/common/primary/app/App.spec.ts.mustache
> +import App from '../../../../../../main/webapp/app/common/primary/app/App.svelte';
maybe can use alias @ here ?

2022-03-04 17:34 UTC, pascalgrimaud commented on tests-ci/generate.sh
> +  callApi "/api/svelte"
better to test /styled

2022-03-04 17:37 UTC, pascalgrimaud commented
You need to update the generated gitignore to add `/.svelte-kit` too

2022-03-04 17:50 UTC, vishal423 commented
> I'm reviewing this, but I don't know if I should merge this, as you told me you won't probably have time to maintain it, @flcarre
> 
> What do you think @vishal423 ?

I guess the initial integration is already in place. To add more features to bring it in parity with other UI frameworks, we need some dedicated efforts initially and constant maintenance. I am already much occupied in blueprint and other priorities and wouldn't be able to support much over here. Maybe we can ask for volunteers on Twitter?

2022-03-04 17:55 UTC, pascalgrimaud commented
Another option would be simply to merge it, with minimal features for Svelte:
- init with home page

If it doesn't work any more in the future, it could be simply disabled, then we can easily delete it.

The philosophy of JHipster Lite is not to bring same features between other UI frameworks. Each contributor will lead his part, that's all. That's why I'm asking you @vishal423 but I can understand if you prefer using blueprint, no worry.

2022-03-04 17:56 UTC, vishal423 commented
> I didn't manage to test it properly. To reproduce my issue:
> 
>     * start JHipster Lite: `./mvnw spring-boot:run`
> 
>     * generate svelteapp: `./tests-ci/generate.sh svelteapp`
> 
>     * go into svelteapp folder: `cd /tmp/jhlite/svelteapp/`
> 
>     * launch install: `npm i`
> 
>     * commit: `git init && git add . && git commit -m 'init'`
> 
> 
> Here the errors:
> 
> ![image](https://user-images.githubusercontent.com/9156882/156811593-8dad386a-3625-4a66-b717-76e17e1736cc.png)

It seems few generated files are not ES module. We just need to rename such files to end with `cjs` extension.

2022-03-05 11:17 UTC, pascalgrimaud commented
Changing it to draft
As soon as someone wants to fix the last items and plan to **maintain** it in the future, I will merge it

2022-03-08 05:39 UTC, flcarre commented
i can maintain svelte i like this techno, i will not end a feature by week but i can maintain svelte

2022-03-08 05:49 UTC, pascalgrimaud commented
@flcarre : ok thanks a lot. Let's try to fix the last items I mentionned. I'll do my best to help too

2022-03-08 06:46 UTC, flcarre commented
once `.lintstagedrc.js` can be changed to `.lintstagedrc.cjs` in svelteapp, i can run `npm install` `npm run test``npm run dev` `npm run build` `npm run preview` i can init and push to a new repo

2022-03-15 07:08 UTC, pascalgrimaud commented
Thanks for your hard work here @flcarre 
I'll review it soon :-)

2022-03-16 17:31 UTC, pascalgrimaud approved these changes

2022-03-16 17:47 UTC, merged

2022-03-17 16:51 UTC, flcarre commented
Finally merged ! 🎉

Thanks ! https://opencollective.com/generator-jhipster/expenses/67785

2022-03-17 21:12 UTC, pascalgrimaud commented
@flcarre : approved :-) thanks for your work here