added toString to better understand debugging sessions
jhipster/jhipster-lite pull request #7729
Opened 2023-10-12 17:45 UTC by anderskristian

I'm leaning to contribute to jhipster-lite
This PR contains toString() improvements to see what values are in variables when debugging and trying to learn how the system works.

I know that this is a very small thing. I just like to see the relevant data when I'm debugging

2023-10-12 17:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=7729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=7729) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=7729) it.</sub>

2023-10-12 19:41 UTC, pascalgrimaud commented
Thanks for your contribution @anderskristian 
But I think you won't pass the CI because of missing unit tests :-)

2023-10-13 17:59 UTC, anderskristian commented
Okay I will try to make unit tests on the to string methods

2023-10-14 17:50 UTC, anderskristian commented
> Thanks for your contribution @anderskristian But I think you won't pass the CI because of missing unit tests :-)

I have added unit tests

2023-10-14 18:05 UTC, DamnClin requested changes
Can you try to stick to the unit testing style on the project?

2023-10-14 18:05 UTC, DamnClin commented on src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPort.java
> +    if (get() == DEFAULT_PORT) return "default";
displaying defaults port seems totally ok to me (instead of "default" string)

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleSlugTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
We are using static imports stating at 1, can you update your IDE configuration to stick to this?

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleSlugTest.java
> +  void testToString() {
We are using shouldXXXWhenYYY style for tests naming, ex here: `shouldGetNameAsToString`, can you update?

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleSlugTest.java
> +    final String name = "init";
The whole test can be one lined: `assertThat(new new JHipsterModuleSlug("init")).hasToString("init")`

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/file/JHipsterDestinationTest.java
> +  void testToString() {
Same as [JHipsterModuleSlugTest.java](https://github.com/jhipster/jhipster-lite/pull/7729/files#diff-6e274b89e45317a386fc14af626a85139e8b855f08c5dc7db05aca616e99dbd4)

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/file/JHipsterFileContentTest.java
> +  void testToString() {
Same as [JHipsterModuleSlugTest.java](https://github.com/jhipster/jhipster-lite/pull/7729/files#diff-6e274b89e45317a386fc14af626a85139e8b855f08c5dc7db05aca616e99dbd4)

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/file/JHipsterSourceTest.java
> +  void testToString() {
Same as [JHipsterModuleSlugTest.java](https://github.com/jhipster/jhipster-lite/pull/7729/files#diff-6e274b89e45317a386fc14af626a85139e8b855f08c5dc7db05aca616e99dbd4)

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterModulePropertiesTest.java
> +  void testToString() {
Same as [JHipsterModuleSlugTest.java](https://github.com/jhipster/jhipster-lite/pull/7729/files#diff-6e274b89e45317a386fc14af626a85139e8b855f08c5dc7db05aca616e99dbd4)

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPortTest.java
> +  void testToString() {
Same as [JHipsterModuleSlugTest.java](https://github.com/jhipster/jhipster-lite/pull/7729/files#diff-6e274b89e45317a386fc14af626a85139e8b855f08c5dc7db05aca616e99dbd4)

2023-10-14 18:05 UTC, DamnClin commented on src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPortTest.java
> +    final JHipsterServerPort normal = new JHipsterServerPort(null);
Split in 2 dedicated tests if you want to test 2 cases

2023-10-14 21:19 UTC, anderskristian commented on src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleSlugTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
I actually have not seen that change that idea has made. 
I will stick to the standard in the project 🙂

Personally I find that static imports changes the java language and makes the code less readable. So I normally tries to avoid static imports due to the readability for people that might not know the statics.

2023-10-14 21:20 UTC, anderskristian commented on src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPort.java
> +    if (get() == DEFAULT_PORT) return "default";
Should I read this so you prefer to see 8080?

2023-10-14 21:51 UTC, anderskristian commented on src/test/java/tech/jhipster/lite/module/domain/JHipsterModuleSlugTest.java
> +    final String name = "init";
I have made all tests one lines so toString() is performed in the assert statement.

2023-10-14 21:53 UTC, anderskristian commented on src/test/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPortTest.java
> +    final JHipsterServerPort normal = new JHipsterServerPort(null);
I have dropped the second test, because I have dropped the 'default'

2023-10-15 05:46 UTC, DamnClin submitted a review, later dismissed
In the project we are naming tests shouldXXXWhenYYY (si no testXXX) but that's not a big deal. LGTM, thanks for your contribution

2023-10-15 10:58 UTC, anderskristian commented
I can see that I still have a problem in the test.
I should use a test with **..hasToString** ...

I have never thought about using hasToString ( I did not know it existed 😳)
I find that check so amazing. It is great. 
So thanks a lot to the **team**  🥰. This weekend I learned quite a lot ... even about toString() 🫠

2023-10-15 17:30 UTC, merged

2023-10-15 17:30 UTC, DamnClin commented
Congratz for your contribution :)