Add Java prerequisites, when adding Maven
jhipster/jhipster-lite pull request #7804
Opened 2023-10-22 14:08 UTC by qmonmert

Fix #7025

2023-10-22 14:25 UTC, pascalgrimaud commented on src/main/resources/generator/init/README.md.mustache
> +<!-- jhipster-needle-prerequisites -->
Instead of adding a needle, I think we can add and use a dedicated section ## Prerequisites

What do you think?

2023-10-22 14:40 UTC, qmonmert commented on src/main/resources/generator/init/README.md.mustache
> +<!-- jhipster-needle-prerequisites -->
Not sure to understand because if we want add other prerequisites for others modules we can with this

2023-10-22 14:53 UTC, pascalgrimaud commented on src/main/resources/generator/init/README.md.mustache
> +<!-- jhipster-needle-prerequisites -->
What I suggest is to use `## Prerequisites` as needle, instead of `<!-- jhipster-needle-prerequisites -->`

1st time:

```
## Prerequisites

```

2nd time, after adding Java:

```
## Prerequisites

### Java

blablabla...

```

3rd time, adding another prerequisites:

```
## Prerequisites

### Node

blablabla...

### Java

blablabla...

```

2023-10-22 15:02 UTC, qmonmert commented on src/main/resources/generator/init/README.md.mustache
> +<!-- jhipster-needle-prerequisites -->
ok I try that

2023-10-24 09:36 UTC, qmonmert commented on src/main/resources/generator/init/README.md.mustache
> +<!-- jhipster-needle-prerequisites -->
@pascalgrimaud I did it

2023-10-24 09:40 UTC, pascalgrimaud commented on src/main/resources/generator/init/README.md.mustache
> +<!-- jhipster-needle-prerequisites -->
Thanks, so does it work well / better ?

2023-10-24 09:41 UTC, qmonmert commented on src/main/resources/generator/init/README.md.mustache
> +<!-- jhipster-needle-prerequisites -->
yes

2023-10-24 10:05 UTC, pascalgrimaud requested changes

2023-10-24 10:05 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/buildtool/maven/domain/MavenModuleFactory.java
> +      .prerequisitesJavaCommand(JAVA_PREREQUISITES)
would rename to prerequisites(...) instead

2023-10-24 10:05 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
> +    public JHipsterModuleBuilder prerequisitesJavaCommand(String prerequisitesJavaCommand) {
rename to prerequisites(...)

2023-10-24 10:05 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
> +      shortcuts.prerequisitesJavaCommand(prerequisitesJavaCommand);
rename to prerequisites(...)

2023-10-24 11:30 UTC, qmonmert commented on src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
> +    public JHipsterModuleBuilder prerequisitesJavaCommand(String prerequisitesJavaCommand) {
done

2023-10-24 11:30 UTC, qmonmert commented on src/main/java/tech/jhipster/lite/module/domain/JHipsterModule.java
> +      shortcuts.prerequisitesJavaCommand(prerequisitesJavaCommand);
done

2023-10-24 12:35 UTC, pascalgrimaud approved these changes

2023-10-24 12:35 UTC, merged

2023-10-24 12:35 UTC, pascalgrimaud commented
Adding a small bounty for rewarding your work. Thanks @qmonmert

2023-10-24 18:19 UTC, qmonmert commented
thanks @pascalgrimaud I appreciate :) https://opencollective.com/generator-jhipster/expenses/168099

2023-10-24 20:35 UTC, pascalgrimaud commented
@qmonmert : approved :-))