Add 'anchor points' in landscape
jhipster/jhipster-lite pull request #7854
Opened 2023-10-25 15:14 UTC by abdelfetah18

Fix #3966

2023-11-02 16:56 UTC, pascalgrimaud commented
can you resolve current conflict in this branch plz @abdelfetah18 ?

@Gnuk : any chance you have a quick look on this plz?

2023-11-13 10:50 UTC, Gnuk requested changes

2023-11-13 10:50 UTC, Gnuk commented on src/main/style/atom/chip/_chip.scss
> +  &.-left-anchor-point::before {
A lot of code seems to be duplicated in the next sections, maybe it's possible to mutualize. Also, lot of magic values with same value, maybe it's possible to add variables to be more explicit.

2023-11-13 10:53 UTC, abdelfetah18 commented on src/main/style/atom/chip/_chip.scss
> +  &.-left-anchor-point::before {
because of me using psuedo element when i try to avoid it,
the psuedo elements stops working

2023-11-13 11:08 UTC, abdelfetah18 commented on src/main/style/atom/chip/_chip.scss
> +  &.-left-anchor-point::before {
and if i make it like this:
```sass
&.-anchor-point {
    position: absolute;
    top: calc(50% - 6px);
    outline: solid 1px var(--jhlite-chip-default-anchor-color);
    border: 3px solid var(--jhlite-chip-bg-color);
    border-radius: 50%;
    background-color: var(--jhlite-chip-default-anchor-color);
    width: 6px;
    height: 6px;
    content: '';
    
    &--left::before {
      left: -6px;
    }
  
    &--right::after {
      right: -6px;
    }
  }
```

the generated css code will look like this:
```sass
.jhlite-chip.-anchor-point {
  position: absolute;
  top: calc(50% - 6px);
  outline: solid 1px var(--jhlite-chip-default-anchor-color);
  border: 3px solid var(--jhlite-chip-bg-color);
  border-radius: 50%;
  background-color: var(--jhlite-chip-default-anchor-color);
  width: 6px;
  height: 6px;
  content: "";
}
.jhlite-chip.-anchor-point--left::before {
  left: -6px;
}
.jhlite-chip.-anchor-point--right::after {
  right: -6px;
}
```
which makes the styles on psuedo elements not working

2023-11-13 11:20 UTC, abdelfetah18 commented on src/main/style/atom/chip/_chip.scss
> +  &.-left-anchor-point::before {
I found a solution using `@extend`, which is:

Putting this on the top of the file:
```sass
%anchor-point {
  position: absolute;
  top: calc(50% - 6px);
  outline: solid 1px var(--jhlite-chip-default-anchor-color);
  border: 3px solid var(--jhlite-chip-bg-color);
  border-radius: 50%;
  background-color: var(--jhlite-chip-default-anchor-color);
  width: 6px;
  height: 6px;
  content: '';
}
```

and then 
```sass
&.-left-anchor-point::before {
  @extend %anchor-point;
  left: -6px;
}
  
&.-right-anchor-point::after {
  @extend %anchor-point;
  right: -6px;
}
```

@Gnuk, Is this good ?

2023-11-13 18:19 UTC, Gnuk commented on src/main/style/atom/chip/_chip.scss
> +  &.-left-anchor-point::before {
Yes, it's better

2023-11-24 07:32 UTC, merged

2023-11-24 07:33 UTC, pascalgrimaud commented
Thanks @abdelfetah18 for your work and your patience

2023-11-24 09:10 UTC, abdelfetah18 commented
> Thanks @abdelfetah18 for your work and your patience

You're very welcome