Update README.md
jhipster/jhipster-lite pull request #7911
Opened 2023-10-31 02:18 UTC by ADHIRAJ-12

Updated commands for cloning and running the project.

2023-10-31 02:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=7911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=7911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=7911) it.</sub>

2023-10-31 09:19 UTC, pascalgrimaud commented
thanks for your contribution @ADHIRAJ-12 : I added some small comments

2023-10-31 10:17 UTC, pascalgrimaud requested changes

2023-10-31 10:17 UTC, pascalgrimaud commented
Oh sorry, I forgot to publish my comments

2023-10-31 10:24 UTC, ADHIRAJ-12 commented on README.md
> +Open your code editor and type the following command  to clone:
oh that's absolutely correct !

2023-10-31 10:31 UTC, ADHIRAJ-12 reviewed
made the changes as suggested

2023-10-31 16:11 UTC, pascalgrimaud commented
Still not good. The missing space is here, between each blocks:

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/e7852677-1777-4bde-8469-4b2b99d4f1ba)

2023-10-31 16:31 UTC, ADHIRAJ-12 reviewed
added spaces according to the original code

2023-10-31 16:34 UTC, ADHIRAJ-12 reviewed
done sir

2023-10-31 17:01 UTC, pascalgrimaud commented on README.md
> +To go into the folder type:
```suggestion

To go into the folder type:

```

2023-10-31 17:02 UTC, pascalgrimaud commented on README.md
> +bash./mvnw
The syntax is still wrong, and this part should be unchanged

2023-11-03 21:19 UTC, pascalgrimaud commented
the CI failed, need to run prettier

2023-11-04 04:32 UTC, closed without merging