add license module
jhipster/jhipster-lite pull request #7982
Opened 2023-11-07 15:07 UTC by cvirieux

Fix #7102

2023-11-07 16:10 UTC, pascalgrimaud commented
The CI failed, probably because of the merge of your other PR. You need to rebase and fix conflict

2023-11-07 17:53 UTC, murdos requested changes
I think it would be simpler to have only one module that would build multiple `JHipsterModule`, as done for e.g. by `CucumberAuthenticationModuleConfiguration`

2023-11-07 17:55 UTC, murdos commented on src/main/resources/generator/setup/license/MIT.txt
> +Copyright [YEAR] [COPYRIGHT HOLDER]
I think we could generate with the current year during generation

2023-11-08 09:55 UTC, cvirieux commented on src/main/resources/generator/setup/license/MIT.txt
> +Copyright [YEAR] [COPYRIGHT HOLDER]
I have updated my code to add current year directly in the factory.

This is my first time working with mustache file so I don't know if it's the correct way to do it. Let me know if there is a better way

2023-11-08 12:48 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/setup/license/domain/LicenseModuleFactory.java
> +        .add(from("setup/license/MIT.txt.mustache"), to("./LICENSE.txt"))
You can create a constant `SOURCE`:
`private static final JHipsterSource SOURCE = from("setup").append("license");`

And then use it here with the `template(String)` method that allows you to omit the `.mustache` suffix:
```suggestion
        .add(SOURCE.template("MIT.txt"), to("./LICENSE.txt"))
```

2023-11-08 12:48 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/setup/license/domain/LicenseModuleFactory.java
> +      .add(from("setup/license/Apache.txt"), to("./LICENSE.txt"))
Following previous comment suggesting to introduce a `SOURCE` constant:

```suggestion
      .add(SOURCE.append("Apache.txt"), to("./LICENSE.txt"))
```

2023-11-08 12:48 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/setup/license/domain/LicenseModuleFactory.java
> +        .add(from("setup/license/MIT.txt.mustache"), to("./LICENSE.txt"))
Usually we omit `./` (same for Apache):
```suggestion
        .add(from("setup/license/MIT.txt.mustache"), to("LICENSE.txt"))
```

2023-11-08 12:48 UTC, murdos commented on src/main/resources/generator/setup/license/MIT.txt
> +Copyright [YEAR] [COPYRIGHT HOLDER]
It looks fine!
I've added a few more suggestions, and then it'll be ok for me :-)

2023-11-08 12:51 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/setup/license/infrastructure/primary/LicenseModuleConfiguration.java
> +      .apiDoc("MIT license", "Add MIT license file")
The fist argument is the group, so I think it should be the same for all module resources. 
```suggestion
      .apiDoc("License", "Add MIT license file")
```

2023-11-08 13:34 UTC, murdos submitted a review, later dismissed

2023-11-08 13:35 UTC, murdos commented
> Quick question : do you want me to squash all my commits or this is done during the merge ?

We usually don't squash during merge, so it's up to you :-)

2023-11-08 14:23 UTC, merged