Add package-info.java in dummy feature
jhipster/jhipster-lite pull request #8069
Opened 2023-11-18 17:36 UTC by qmonmert

Fix #7965

2023-11-19 07:24 UTC, pascalgrimaud requested changes

2023-11-19 07:24 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/mvc/dummy/feature/main/package-info.java.mustache
> +@{{packageName}}.SharedKernel
I think it's business context, not a shared karnel

2023-11-19 14:07 UTC, qmonmert commented on src/main/resources/generator/server/springboot/mvc/dummy/feature/main/package-info.java.mustache
> +@{{packageName}}.SharedKernel
you're right, I fix

2023-11-20 05:34 UTC, pascalgrimaud approved these changes

2023-11-20 05:34 UTC, merged