add tailwindcss to thymeleaf template module
jhipster/jhipster-lite pull request #8358
Opened 2023-12-12 11:39 UTC by renanfranca

See #4339

2023-12-12 11:46 UTC, renanfranca commented
I've created the tests and decided to open this draft pull request before moving forward with the implementation. This is to keep everyone informed about my current work. Please feel free to provide any comments or suggestions.

I will add the tailwindcss from the list:
* [x] thymeleaf
* webjars
* htmx
* alpine
* **tailwind**
* (or bootstrap)
* [X] skeleton layout and index files

2023-12-12 23:03 UTC, atomfrede commented
Great @renanfranca, together with https://github.com/jhipster/jhipster-lite/pull/8327 I guess we are done with a first feature complete version.

2023-12-13 00:14 UTC, renanfranca commented
> Great @renanfranca, together with https://github.com/jhipster/jhipster-lite/pull/8327 I guess we are done with a first feature complete version.

Thanks, @atomfrede, for taking a look! That's great news!

2023-12-13 19:58 UTC, renanfranca commented
Hi @atomfrede !

I attempted to use the live reload feature as described in the README.md, but unfortunately, it didn't work. I also ran the project from https://github.com/wimdeblauwe/ttcli, and encountered the same issue with live reload not functioning.

I've nearly completed all the necessary steps, but now I'm looking to modify the index file to incorporate TailwindCSS classes following the application of the TailwindCSS module.

2023-12-13 21:22 UTC, atomfrede commented
Need to check how its done. Wims approach is a little different from what I usually use with gradle and spring devtool and the live reload server. What issues did you encounter?

2023-12-13 21:31 UTC, renanfranca commented
> Need to check how its done. Wims approach is a little different from what I usually use with gradle and spring devtool and the live reload server. What issues did you encounter?

I change the index.html file and it didn't live reload. I had to stop and rerun the spring boot application to see the change.

2023-12-14 03:21 UTC, renanfranca commented
> Need to check how its done. Wims approach is a little different from what I usually use with gradle and spring devtool and the live reload server. What issues did you encounter?

@atomfrede : I forgot to add the spring-boot-devtools module, It works really well after adding this module 😄. I update the Thymeleaf readme file with this information. 

It is almost done, I am going to improve the index.html with tailwindcss 👍

2023-12-18 15:10 UTC, atomfrede commented
Awesome @renanfranca will have look later today. I would say let's get https://github.com/jhipster/jhipster-lite/pull/8327 merged first, I guess there will be some conflicts afterwards.

2023-12-18 15:27 UTC, renanfranca commented
Thanks @atomfrede ! I agree! I will rebase and solve the conflicts after merging the other pull request 👍

2023-12-30 22:50 UTC, atomfrede commented
@renanfranca Can you rebase?

2023-12-30 23:33 UTC, renanfranca commented
> @renanfranca Can you rebase?

I will do it when my daughter sleeps 😅

2023-12-31 03:31 UTC, renanfranca commented
@atomfrede It is done 😉 !

I wish you happy holidays and a Happy New Year! 🥳

2023-12-31 11:22 UTC, atomfrede approved these changes
Nice work.

2023-12-31 11:32 UTC, murdos commented on src/test/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactoryTest.java
> +        "\"watch:html\": \"onchange \\\"src/main/resources/templates/**/*.html\\\" -- npm-run-all --serial build:css build:html\""
it might be clearer with a text block (using three double-quote marks):
```suggestion
        """
        "watch:html": "onchange \"src/main/resources/templates/**/*.html\" -- npm-run-all --serial build:css build:html"
        """
```

2023-12-31 11:32 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactory.java
> +        .addScript(scriptKey("watch:html"), scriptCommand("onchange \\\\\\\"src/main/resources/templates/**/*.html\\\\\\\" -- npm-run-all --serial build:css build:html"))
I previously add issues with quote escaping with bun: https://github.com/jhipster/jhipster-lite/pull/7613/files
It seems using simple quote solve the issue, both for bun and npm.

2024-01-02 15:54 UTC, renanfranca commented on src/test/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactoryTest.java
> +        "\"watch:html\": \"onchange \\\"src/main/resources/templates/**/*.html\\\" -- npm-run-all --serial build:css build:html\""
@murdos: Thank you for the detailed review! The code is now much more readable!

2024-01-02 15:55 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactory.java
> +        .addScript(scriptKey("watch:html"), scriptCommand("onchange \\\\\\\"src/main/resources/templates/**/*.html\\\\\\\" -- npm-run-all --serial build:css build:html"))
It is done! 😄

2024-01-02 15:56 UTC, renanfranca commented
@murdos: Thank you! I pushed a new version!

2024-01-02 15:59 UTC, DanielFran requested changes

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "@babel/cli": "^7.23.4",
```suggestion
    "@babel/cli": "7.23.4",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "autoprefixer": "^10.4.16",
```suggestion
    "autoprefixer": "10.4.16",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "browser-sync": "^2.29.3",
```suggestion
    "browser-sync": "2.29.3",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "cssnano": "^6.0.1",
```suggestion
    "cssnano": "6.0.1",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "mkdirp": "^3.0.1",
```suggestion
    "mkdirp": "3.0.1",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "npm-run-all": "^4.1.5",
```suggestion
    "npm-run-all": "4.1.5",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "onchange": "^7.1.0",
```suggestion
    "onchange": "7.1.0",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "path-exists-cli": "^2.0.0",
```suggestion
    "path-exists-cli": "2.0.0",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "postcss": "^8.4.32",
```suggestion
    "postcss": "8.4.32",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "postcss-cli": "^11.0.0",
```suggestion
    "postcss-cli": "11.0.0",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "recursive-copy-cli": "^1.0.20",
```suggestion
    "recursive-copy-cli": "1.0.20",
```

2024-01-02 15:59 UTC, DanielFran commented on src/main/resources/generator/dependencies/common/package.json
> +    "tailwindcss": "^3.3.6",
```suggestion
    "tailwindcss": "3.3.6",
```

2024-01-02 16:12 UTC, renanfranca commented
Thank you, @DanielFran! I've pushed a new version. Could that be the reason why the bot didn't update those dependency versions?"

2024-01-02 16:20 UTC, DanielFran commented
> Thank you, @DanielFran! I've pushed a new version. Could that be the reason why the bot didn't update those dependency versions?"

Probably

2024-01-02 23:01 UTC, murdos submitted a review, later dismissed

2024-01-08 20:04 UTC, atomfrede approved these changes

2024-01-08 20:05 UTC, atomfrede commented
@renanfranca Can you fix the conflicts?

2024-01-08 21:17 UTC, renanfranca commented
> @renanfranca Can you fix the conflicts?

@atomfrede : Cool! I pushed the new version 👍

2024-01-08 21:29 UTC, murdos commented
@DanielFran: is that ok for you now? Since you requested changes, I can't merge the PR.

2024-01-08 22:21 UTC, DanielFran approved these changes

2024-01-08 22:22 UTC, merged