Minor refactorings
jhipster/jhipster-lite pull request #8686
Opened 2024-01-19 21:03 UTC by gzsombor

Small changes, which I thought make sense.

2024-01-19 22:16 UTC, murdos requested changes

2024-01-19 22:16 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPort.java
> -    Assert.field("serverPort", serverPort).min(1).max(65_535);
Why are you removing this assertion?

2024-01-19 22:16 UTC, murdos commented on src/main/resources/generator/buildtool/maven/pom.xml.mustache
> +    <java.version>{{javaVersion}}</java.version>
What is your intent? 
Generated code only compiles with java 21+
By allowing user to change this property to any value, there's great chance that the generated project doesn't work.

2024-01-19 22:21 UTC, gzsombor commented on src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPort.java
> -    Assert.field("serverPort", serverPort).min(1).max(65_535);
The assertion is moved into the default constructor, so it's still apply

2024-01-19 22:24 UTC, gzsombor commented on src/main/resources/generator/buildtool/maven/pom.xml.mustache
> +    <java.version>{{javaVersion}}</java.version>
The user can't change the property, it is set in the JHipsterModuleProperties as a final variable.
I don't want to repeat the same 21 in every template, and make it clear what's that number is about.
So I can write a template, without the need to constantly update, whenever a new java version is released.

2024-01-19 22:27 UTC, murdos approved these changes

2024-01-20 09:14 UTC, pascalgrimaud commented
Happy to see you here @gzsombor !
I didn't expect you followed this project. Thanks for your help and your contribution :)

2024-01-20 09:14 UTC, merged