Add git init script when initializing project
jhipster/jhipster-lite pull request #869
Opened 2022-02-28 11:20 UTC by matthieulapatate

fix #670 
Directory is generated but return an error while working.

2022-02-28 16:36 UTC, pascalgrimaud commented
It's because you didn't respect the architecture. See the errors in logs:

```
Error:  tech.jhipster.lite.HexagonalArchTest.domainShouldNotInteractWithOutside  Time elapsed: 0.786 s  <<< FAILURE!
java.lang.AssertionError: 
Architecture Violation [Priority: MEDIUM] - Rule 'no classes that reside in any package ['..domain..'] should depend on classes that reside in any package ['..application..', '..infrastructure..', '..primary..', '..secondary..'], because Domain should not interact with application, infrastructure, primary or secondary' was violated (1 times):
Constructor <tech.jhipster.lite.generator.init.domain.InitDomainService.<init>(tech.jhipster.lite.generator.packagemanager.npm.domain.NpmService, tech.jhipster.lite.generator.project.domain.ProjectRepository, java.util.concurrent.Executor)> references class object <tech.jhipster.lite.generator.packagemanager.npm.infrastructure.secondary.NpmLocalRepository> in (InitDomainService.java:35)
	at tech.jhipster.lite.HexagonalArchTest.domainShouldNotInteractWithOutside(HexagonalArchTest.java:188)

Error:  tech.jhipster.lite.HexagonalArchTest.shouldNotHaveFrameworkDependenciesInContext  Time elapsed: 0.04 s  <<< FAILURE!
java.lang.AssertionError: 
Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in any package ['tech.jhipster.lite.generator.init.domain..'] should only depend on classes that reside in any package ['tech.jhipster.lite.generator.init.domain..', 'java..', 'org.slf4j..', 'org.apache.commons.lang3..', 'tech.jhipster.lite.error..', 'tech.jhipster.lite.generator.server.springboot.cache.common..', 'tech.jhipster.lite.generator.server.springboot.database.sqlcommon..', 'tech.jhipster.lite.generator.server.springboot.springcloud.common..', 'tech.jhipster.lite.generator.server.springboot.common..', 'tech.jhipster.lite.generator.packagemanager.npm..', 'tech.jhipster.lite.generator.project..', 'tech.jhipster.lite.generator.buildtool.generic..', 'tech.jhipster.lite.generator.buildtool.gradle..', 'tech.jhipster.lite.generator.buildtool.maven..', 'tech.jhipster.lite.common..'], because Domain model should only depend on himself and a very limited set of external dependencies' was violated (1 times):
Field <tech.jhipster.lite.generator.init.domain.InitDomainService.timeout> is annotated with <org.springframework.beans.factory.annotation.Value> in (InitDomainService.java:0)
	at tech.jhipster.lite.HexagonalArchTest.lambda$shouldNotHaveFrameworkDependenciesInContext$12(HexagonalArchTest.java:121)
	at tech.jhipster.lite.HexagonalArchTest.shouldNotHaveFrameworkDependenciesInContext(HexagonalArchTest.java:113)
```

Then, you don't need to add all these codes as the `ProjectRepository` contains already the method `gitInit`

2022-03-07 14:46 UTC, pascalgrimaud requested changes

2022-03-07 14:46 UTC, pascalgrimaud commented on a
> +[INFO] Scanning for projects...
why do you commit this file ?

2022-03-07 14:46 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/init/domain/InitDomainService.java
> +    addGitInit(project);
it is not tested by unit test or integration test

2022-03-08 05:57 UTC, pascalgrimaud requested changes

2022-03-08 16:50 UTC, pascalgrimaud commented
@matthieulapatate : still waiting your squash, to have 1 single commit

2022-03-08 16:59 UTC, matthieulapatate commented
> @matthieulapatate : still waiting your squash, to have 1 single commit

Might be good right ?

2022-03-08 17:45 UTC, pascalgrimaud commented
good, it can be merged, thanks @matthieulapatate

2022-03-08 17:46 UTC, pascalgrimaud approved these changes

2022-03-08 17:46 UTC, merged