Docker: Add dockerfile
jhipster/jhipster-lite pull request #879
Opened 2022-02-28 18:01 UTC by beatfreaker

Fixes #585

2022-02-28 18:05 UTC, pascalgrimaud commented
Plz, can you add the call in the CI too plz?
https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L76

2022-02-28 18:09 UTC, beatfreaker commented
> Plz, can you add the call in the CI too plz? https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/generate.sh#L76

Yes, will handle it

2022-02-28 19:36 UTC, pascalgrimaud requested changes

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/project/domain/Constants.java
> +  public static final String DOCKER_FILE = "Dockerfile";
It's 1 single word, so I'd suggest to rename to DOCKERFILE

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/application/SpringBootDockerApplicationService.java
> +  public void addDockerFile(Project project) {
```suggestion
  public void addDockerfile(Project project) {
```

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/application/SpringBootDockerApplicationService.java
> +    this.springBootDockerService.addDockerFile(project);
```suggestion
    this.springBootDockerService.addDockerfile(project);
```

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +  public void addDockerFile(Project project) {
```suggestion
  public void addDockerfile(Project project) {
```

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/infrastructure/primary/rest/SpringBootDockerResource.java
> +  @GeneratorStep(id = "jib")
Should not be jib, it could be: dockerfile

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/infrastructure/primary/rest/SpringBootDockerResource.java
> +  public void addDockerFile(@RequestBody ProjectDTO projectDTO) {
```suggestion
  public void addDockerfile(@RequestBody ProjectDTO projectDTO) {
```

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/docker/Dockerfile
> +    ./mvnw package -Pgcp -DskipTests && \
Should remove the gcp profile

2022-02-28 19:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/docker/application/SpringBootDockerApplicationServiceIT.java
> +  void shouldAddDockerFile() {
```suggestion
  void shouldAddDockerfile() {
```

2022-02-28 19:36 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/docker/infrastructure/primary/rest/SpringBootDockerResourceIT.java
> +    mavenApplicationService.init(project);
No need maven for this test

2022-02-28 19:36 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/infrastructure/primary/rest/SpringBootDockerResource.java
> +  @PostMapping("/docker-file")
```suggestion
  @PostMapping("/dockerfile")
```

2022-03-01 07:08 UTC, pascalgrimaud requested changes

2022-03-01 07:08 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/docker/Dockerfile
> +EXPOSE 8080
```suggestion
EXPOSE {{serverPort}}
```

2022-03-01 07:08 UTC, pascalgrimaud commented on src/main/resources/generator/server/springboot/docker/Dockerfile
> +FROM openjdk:17-slim
this file needs to be renamed to Dockerfile.mustache (because of dynamic serverPort)

2022-03-01 07:08 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/docker/domain/SpringBootDockerDomainService.java
> +    projectRepository.add(project, DOCKER_SOURCE, DOCKERFILE);
```suggestion
    project.addConfig("serverPort", 8080);
    projectRepository.template(project, DOCKER_SOURCE, DOCKERFILE);
```

2022-03-01 07:08 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/docker/application/SpringBootDockerApplicationServiceIT.java
> +    assertFileExist(project, "Dockerfile");
```suggestion
    assertFileExist(project, "Dockerfile");
    assertFileContent(project, "Dockerfile", "EXPOSE 8080");
```

2022-03-01 07:08 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/server/springboot/docker/application/SpringBootDockerApplicationServiceIT.java
> +
you can add this another test too:

```java
  @Test
  void shouldAddDockerfileWithDifferentPort() {
    Project project = tmpProject();
    project.addConfig("serverPort", 7419);
    initApplicationService.init(project);

    springBootDockerApplicationService.addDockerfile(project);

    assertFileExist(project, "Dockerfile");
    assertFileContent(project, "Dockerfile", "EXPOSE 7419");
  }
```

2022-03-01 07:10 UTC, pascalgrimaud commented
@beatfreaker : just tested it, and it works well. Last comments from my side to handle dynamic port, with serverPort in configuration

2022-03-01 07:43 UTC, beatfreaker commented
> @beatfreaker : just tested it, and it works well. Last comments from my side to handle dynamic port, with serverPort in configuration

Handled, and thank you for explaining it with the code samples.

2022-03-01 08:01 UTC, pascalgrimaud approved these changes

2022-03-01 08:01 UTC, merged

2022-03-01 16:25 UTC, pascalgrimaud commented
@beatfreaker : approved :) thanks for your work