replace default server port when property has custom value
jhipster/jhipster-lite pull request #8825
Opened 2024-02-02 21:40 UTC by alerGeek

PR fix frontend properties:
 - replace default value (8080) for Angular Module
 - replace default value (8080) for React Module
 - replace default value (8080) for ThymeLeaf Module

PR fix README.md files/properties for ouath docker image.

Fix #8824

2024-02-02 21:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=8825) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-lite?pullRequest=8825) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-lite?pullRequest=8825) it.</sub>

2024-02-02 22:21 UTC, murdos requested changes
Thanks for the PR! 
I made a few suggestions to simplify things

2024-02-02 22:21 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactory.java
> +        .addScript(scriptKey("watch:serve"), scriptCommand("browser-sync start --no-inject-changes --proxy localhost:%s --files 'target/classes/templates' 'target/classes/static'".formatted(getServer
There's no reason to redefine the default 8080 port in every module, it's already defined in [JHipsterServerPort](https://github.com/jhipster/jhipster-lite/blob/af7e03921f55183e544c38fd3d23718eb5b18a9b/src/main/java/tech/jhipster/lite/module/domain/properties/JHipsterServerPort.java#L6) so you can just use:
```suggestion
        .addScript(scriptKey("watch:serve"), scriptCommand("browser-sync start --no-inject-changes --proxy localhost:%s --files 'target/classes/templates' 'target/classes/static'".formatted(properties.serverPort().get())))
```
and remove the `getServerPort()` method below.

2024-02-02 22:21 UTC, murdos commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactory.java
> +        .in(path("proxy.conf.json"))
Rather than doing a replacement, you should turn `proxy.conf.json` to a template that will use the `serverPort` properties:
- rename `proxy.conf.json` in src/main/resources/generator/client/angular/core/ to `proxy.conf.json.mustache` and replace `8080` by `{{serverPort}}`
- change line `.add(SOURCE.file("proxy.conf.json"), to("proxy.conf.json"))` to `.addTemplate(SOURCE.file("proxy.conf.json"), to("proxy.conf.json"))`

2024-02-03 05:28 UTC, alerGeek commented on src/main/java/tech/jhipster/lite/generator/server/springboot/thymeleaf/template/domain/ThymeleafTemplateModuleFactory.java
> +        .addScript(scriptKey("watch:serve"), scriptCommand("browser-sync start --no-inject-changes --proxy localhost:%s --files 'target/classes/templates' 'target/classes/static'".formatted(getServer
Thanks! I was not sure if the serverPort property is generated as well when no spring-boot-mvc-empty module is added. I have removed unnecessary method

2024-02-03 05:30 UTC, alerGeek commented on src/main/java/tech/jhipster/lite/generator/client/angular/core/domain/AngularModuleFactory.java
> +        .in(path("proxy.conf.json"))
Done. I have did the same to vte.config.ts in React Module. However, as I was not able to add the addTemple without the batch, I had to modify it to:
```
...
        .batch(SOURCE, to("."))
          .addTemplate("proxy.conf.json")
          .and()
...
```

2024-02-03 06:38 UTC, murdos approved these changes

2024-02-03 06:47 UTC, merged

2024-02-03 06:54 UTC, murdos commented
Congrats @alerGeek for your first contribution :-)