fix gradle dependencies order code smell
jhipster/jhipster-lite pull request #9079
Opened 2024-02-28 18:35 UTC by renanfranca

Fix #9078

2024-02-28 18:40 UTC, murdos commented on src/main/resources/generator/buildtool/gradle/build.gradle.kts.mustache
>    // jhipster-needle-gradle-dependencies
If we want to be consistent, I guess that it should be:
```suggestion
  // jhipster-needle-gradle-implementation-dependencies
```

2024-02-28 18:42 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
> +      default -> GRADLE_DEPENDENCY_NEEDLE;
I suggest to remove TEST_COMPILE_ONLY and TEST_RUNTIME_ONLY values from GradleDependencyScope, since they're currently not used.
And remove this `default` branch: it's better to fully use pattern matching so each new value will have to be explicitly mapped.
This is related to my comment https://github.com/jhipster/jhipster-lite/issues/9078#issuecomment-1969582626: we'll need additional needles for compileOnly and runtimeOnly

2024-02-28 18:44 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
> +        determineGradleDependencyNeedle(gradleScope)
Naming suggestion:
```suggestion
        needleForGradleDependencyScope(gradleScope)
```

2024-02-28 18:47 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
> +      default -> GRADLE_DEPENDENCY_NEEDLE;
NB : GradleDependencyScope.API should also be removed :)

2024-02-28 19:04 UTC, renanfranca commented
@murdos : Thank you for the fast review! I implemented the bearer minimum to solve the particular reported code smell, when another scenario of dependencies code smells appears I am going to fix it.

I tried `./tests-ci/generate.sh gradleapp gradle yml` on my PC and the dependencies got in the correct order:

```gradle
dependencies {
  implementation(libs.protobuf.java)
  implementation(libs.commons.lang3)
  implementation(platform(libs.spring.boot.dependencies))
  implementation(libs.spring.boot.starter)
  implementation(libs.spring.boot.configuration.processor)
  implementation(libs.spring.boot.starter.validation)
  implementation(libs.spring.boot.starter.web)
  implementation(libs.spring.boot.starter.actuator)
  implementation(libs.spring.boot.starter.data.jpa)
  implementation(libs.hikariCP)
  implementation(libs.hibernate.core)
  implementation(libs.liquibase.core)
  implementation(libs.spring.boot.starter.security)
  implementation(libs.jjwt.api)
  implementation(libs.springdoc.openapi.starter.webmvc.ui)
  implementation(libs.springdoc.openapi.starter.webmvc.api)
  // jhipster-needle-gradle-implementation-dependencies
  runtimeOnly(libs.postgresql)
  runtimeOnly(libs.jjwt.impl)
  runtimeOnly(libs.jjwt.jackson)
  // jhipster-needle-gradle-runtime-dependencies

  testImplementation(libs.protobuf.java.util)
  testImplementation(libs.spring.boot.starter.test)
  testImplementation(libs.reflections)
  testImplementation(libs.testcontainers.postgresql)
  testImplementation(libs.h2)
  testImplementation(libs.spring.security.test)
  testImplementation(libs.cucumber.junit.platform.engine)
  testImplementation(libs.cucumber.java)
  testImplementation(libs.cucumber.spring)
  testImplementation(libs.junit.platform.suite)
  // jhipster-needle-gradle-test-dependencies
}
```

2024-02-28 20:25 UTC, murdos requested changes

2024-02-28 20:25 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
> -      case PROVIDED -> GradleDependencyScope.COMPILE_ONLY;
Sorry, but I would like to keep this one. 
Even if the PROVIDED scope is not used yet in any modules in jhlite, it might be used in some custom jhlite, and the mapping is correct, I don't see a reason to remove it.

2024-02-28 20:45 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
> -      case PROVIDED -> GradleDependencyScope.COMPILE_ONLY;
No problem, I will keep it 👍. In that case, should I create a needle for compileOnly?

2024-02-28 21:11 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
> -      case PROVIDED -> GradleDependencyScope.COMPILE_ONLY;
Yes, I think it's necessary. Please let me know if you don't have time to do it, I'll do it.

2024-02-28 21:18 UTC, renanfranca commented on src/main/java/tech/jhipster/lite/module/infrastructure/secondary/javadependency/gradle/GradleCommandHandler.java
> -      case PROVIDED -> GradleDependencyScope.COMPILE_ONLY;
> Yes, I think it's necessary. Please let me know if you don't have time to do it, I'll do it.

Thank you 😊,  I can't do it today, only tomorrow morning. You can do it if you want 👍

2024-02-29 10:46 UTC, renanfranca commented
@murdos : I pushed the changes, please, let me know if it's ok 😁

2024-02-29 11:50 UTC, murdos approved these changes

2024-02-29 11:51 UTC, murdos commented
@renanfranca : it's perfect, thanks! Sorry I finally wasn't able to work on it yesterday as I initially proposed.

2024-02-29 11:51 UTC, merged

2024-02-29 12:00 UTC, renanfranca commented
> @renanfranca : it's perfect, thanks! Sorry I finally wasn't able to work on it yesterday as I initially proposed.

It's cool, let's keep going! 😎