Manage maven version similarly as the other dependency versions are m…
jhipster/jhipster-lite pull request #9353
Opened 2024-03-25 18:07 UTC by gzsombor

…anaged

2024-03-25 18:13 UTC, DanielFran commented on src/main/resources/generator/buildtool/maven/pom.xml.mustache
> +    <maven.version>{{mavenVersion}}</maven.version>
@gzsombor @pascalgrimaud @murdos If maven.version is used to enforce minimum maven version with maven-enforcer-plugin (like in the generator-jhipster), this should be version 3.2.5.

See https://maven.apache.org/docs/history.html:
![image](https://github.com/jhipster/jhipster-lite/assets/3706415/3c29bd95-29e4-4826-9029-4c20001bd441)

2024-03-25 19:56 UTC, murdos commented on src/main/resources/generator/dependencies/pom.xml
> +    <maven.version>3.9.6</maven.version>
Maven wrapper version is already managed by renovate that automatically update it, so I don't really see the added value with theses changes:
![image](https://github.com/jhipster/jhipster-lite/assets/155828/ed4328bb-e568-4702-bea0-aa8073cbdd4e)

2024-03-25 19:56 UTC, murdos commented on src/main/resources/generator/buildtool/maven/pom.xml.mustache
> +    <maven.version>{{mavenVersion}}</maven.version>
@DanielFran I agree. We previously had a similar discussion: https://github.com/jhipster/jhipster-lite/pull/8933#discussion_r1493830805
I however think that requiring 3.2.5 is way too low. Recent (3.8+) maven versions contains a lot of improvements and it would be a shame to not raise the bar a little. 
If we require 3.2.5 version, then the enforce verification doesn't have much value.

2024-03-25 21:55 UTC, gzsombor commented on src/main/resources/generator/buildtool/maven/pom.xml.mustache
> +    <maven.version>{{mavenVersion}}</maven.version>
Ok, I'm going to rename the mavenVersion to 'latestMavenVersion' or something like that, and keep 'enforcer-plugin' as is

2024-03-25 22:00 UTC, gzsombor commented on src/main/resources/generator/dependencies/pom.xml
> +    <maven.version>3.9.6</maven.version>
My main goal is to have a way to get the current maven/gradle version from a module - as I try to create a jhipster module to create [Mise configuration](https://mise.jdx.dev/), so I could have a minimal, declarative project setup.  
Any alternative idea, how and where can I get those values ? I would rather not duplicate that constant in that module.

2024-03-26 07:03 UTC, murdos commented on src/main/resources/generator/dependencies/pom.xml
> +    <maven.version>3.9.6</maven.version>
The main issue is that by doing that you're breaking automatic update of maven wrapper.
The source of truth for maven wrapper version in jhipster-lite is `src/main/resources/generator/buildtool/maven/.mvn/wrapper/maven-wrapper.properties` since it's handled by our automatic dependencies updater (renovate).

If for your specific needs you need to get the maven wrapper version used by jhipster-lite, you could implement a reader, **in your own module**, that will extract the version from `src/main/resources/generator/buildtool/maven/.mvn/wrapper/maven-wrapper.properties`:
`mise/domain/MavenWrapperVersionReader.java`
```java
interface MavenWrapperVersionReader {
  Version readVersion();
}
```
implemented by
`mise/infractructure/secondary/FilesystemMavenWrapperVersionReader.java`
```java
@Component
class FilesystemMavenWrapperVersionReader implements MavenWrapperVersionReader {
  @Override
  public Version readVersion() {
  // load generator/buildtool/maven/.mvn/wrapper/maven-wrapper.properties content from classpath
  // using a regexp to extract maven version
  }
}

2024-03-29 22:31 UTC, murdos requested changes
As stated in [this comment](https://github.com/jhipster/jhipster-lite/pull/9353/files#r1538680751) this is breaking automatic maven wrapper updates with renovate

2025-01-10 08:04 UTC, murdos commented
Closing this PR since it's outdated and requires more design discussions.

2025-01-10 08:04 UTC, closed without merging