Fix #8654 : Make realmName and clientScopeName customizable
jhipster/jhipster-lite pull request #9366
Opened 2024-03-26 07:05 UTC by gzsombor

2024-03-26 07:18 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactory.java
> +    var clientScopeName = properties.getOrDefaultString(CLIENT_SCOPE_NAME, "jhipster_client");
I think we should use the same values than the current existing ones (which are the same than in generator-jhipster): jhipster

2024-03-26 07:30 UTC, gzsombor commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactory.java
> +    var clientScopeName = properties.getOrDefaultString(CLIENT_SCOPE_NAME, "jhipster_client");
Honestly, having jhipster as a default for every imaginable value is not the wisest pattern :grinning:

2024-03-26 07:55 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactory.java
> +    var clientScopeName = properties.getOrDefaultString(CLIENT_SCOPE_NAME, "jhipster_client");
Ahah, I think the same than you. But I'd prefer keeping jhipster as default because:
- avoid breaking change for existing app
- closed to generator-jhipster so it's a little bit compatible

2024-03-26 08:08 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactory.java
> +      .put("clientScopeName", clientScopeName);
I think we need to add some rules for this, maybe? Avoid space, avoid strange char, etc?

2024-03-26 08:15 UTC, pascalgrimaud commented
@gzsombor : something I wanted to tell you -> I'm really happy to see to here, in this project and doing contributions. Thanks so much for helping this project! :heart:

2024-03-26 19:06 UTC, gzsombor commented
> @gzsombor : something I wanted to tell you -> I'm really happy to see to here, in this project and doing contributions. Thanks so much for helping this project! ❤️

That is really nice of you! I'm happy if I could help - and have enough time to do that :)

2024-03-26 19:07 UTC, gzsombor commented on src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/security/oauth2/core/domain/OAuth2ModuleFactory.java
> +      .put("clientScopeName", clientScopeName);
Yes, that's a very valid point

2024-04-26 20:47 UTC, murdos requested changes

2024-04-26 20:47 UTC, murdos commented on src/main/java/tech/jhipster/lite/module/domain/JHipsterSlug.java
> +    Assert.field("slug", slug).notBlank().urlSafeSingleWord(() -> new InvalidJHipsterSlugException(slug));
I'm not very fond of this refactoring, I think we loose some expressiveness and ease of understanding.
I'd rather keep each pattern constant hidden in each class even if it looks like duplicated, and don't introduce custom exception generated by `Assert.field(.., ..)`.

2024-04-29 20:44 UTC, gzsombor commented on src/main/java/tech/jhipster/lite/module/domain/JHipsterSlug.java
> +    Assert.field("slug", slug).notBlank().urlSafeSingleWord(() -> new InvalidJHipsterSlugException(slug));
I think, calling a function `urlSafeSingleWord()` with proper and javadoc is lightyear ahead more expressive than trying to decipher `Pattern.compile("^[a-z0-9-]+$")` or to check if two pattern are the same or not.
 We could get rid of these custom InvalidJHipsterModuleTagException/ UrlSafeSingleWordException/InvalidJHipsterSlugException and just use a plain old IllegalArgumentException, that would help reducing the unnecessary verbosity.

2024-05-24 19:23 UTC, merged