Add first e2e tests
jhipster/jhipster-lite pull request #969
Opened 2022-03-09 14:39 UTC by Franceq34

2022-03-09 16:11 UTC, pascalgrimaud requested changes
revert the package-lock change plz

2022-03-09 20:55 UTC, pascalgrimaud approved these changes

2022-03-09 20:55 UTC, merged

2022-04-27 09:08 UTC, Franceq34 commented
$100 bounty claimed => https://opencollective.com/generator-jhipster/expenses/74247

2022-04-27 09:12 UTC, pascalgrimaud commented
@Franceq34 : approved