Create History API
jhipster/jhipster-lite pull request #994
Opened 2022-03-11 08:24 UTC by seraphinandrieux

- Fix #935

2022-03-11 09:43 UTC, pascalgrimaud requested changes

2022-03-11 09:43 UTC, pascalgrimaud commented on pom.xml
> +      <groupId>io.swagger</groupId>
why do you use this? we don't need it as we migrate from springfox to springdoc
You can have a look at: https://springdoc.org/migrating-from-springfox.html

2022-03-11 10:05 UTC, seraphinandrieux commented on pom.xml
> +      <groupId>io.swagger</groupId>
Aaaaa ok np I'm changing that perfect thanks :)

2022-03-11 20:29 UTC, Bolo89 requested changes

2022-03-11 20:29 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/history/infrastructure/primary/HistoryResource.java
> +    @Parameter(description = "Project path to get history") @RequestParam(value = "folder", required = false) String folder
I think that the folder is required ? 
@RequestParam(value = "folder", required = true)

2022-03-11 20:29 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/history/infrastructure/primary/HistoryResource.java
> +class HistoryResource {
Missing Integration test for this ressource

2022-03-11 20:29 UTC, Bolo89 commented on src/main/java/tech/jhipster/lite/generator/history/application/GeneratorHistoryApplicationService.java
> +  public List<GeneratorHistoryValue> get(Project project) {
Possible to rename as " getAll " or " getValues " or something else ?

2022-03-12 08:31 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/history/infrastructure/primary/HistoryResource.java
> +class HistoryResource {
agree, I'd prefer a real IT, instead of UnitTest

2022-03-12 08:35 UTC, pascalgrimaud requested changes

2022-03-12 08:35 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/history/infrastructure/primary/HistoryResource.java
> +  @Operation(summary = "Init project")
The summary of this operation is not correct

2022-03-12 08:35 UTC, pascalgrimaud commented on src/main/java/tech/jhipster/lite/generator/history/infrastructure/primary/RestHistory.java
> +public record RestHistory(@Schema(name = "Service Ids applied to project", required = true) Collection<String> serviceIds) {
I know you use RestXxxx in your project. But I wonder if we should stay consistent and use simply HistoryDTO instead ?

2022-03-12 08:35 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/history/infrastructure/primary/RestHistoryTest.java
> +    assertThat(history.getServiceIds()).isEqualTo(List.of("service1", "service42", "service3"));
you should use 33, 51 or 1664, if you understand what I'm talking about :)

2022-03-12 08:35 UTC, pascalgrimaud commented on src/test/java/tech/jhipster/lite/generator/history/infrastructure/primary/RestHistoryTest.java
> +    return ("{" + "\"serviceIds\":[\"service1\",\"service42\",\"service3\"]" + "}");
maybe try to use block text here?

2022-03-12 19:54 UTC, Bolo89 commented on src/test/java/tech/jhipster/lite/generator/history/infrastructure/primary/HistoryResourceIT.java
> +      .andExpect(content().string("{\"serviceIds\":[\"init\",\"maven\",\"github-actions\"]}"));
u can test json content field by field, it's more readable I think : 
```java
mockMvc
      .perform(get("/api/projects/history").param("folder", projectDTO.getFolder()))
      .andExpect(status().isOk())
      .andExpect(jsonPath("$.serviceIds", Matchers.hasSize(3)))
      .andExpect(jsonPath("$.serviceIds[0]").value("init"))
      .andExpect(jsonPath("$.serviceIds[1]").value("maven"))
      .andExpect(jsonPath("$.serviceIds[2]").value("github-actions"))
```

2022-03-13 15:22 UTC, pascalgrimaud approved these changes

2022-03-13 15:22 UTC, merged